(function(){
'use strict';
const apiBase=(window.ERISCHAT_API_BASE||window.ERIS_API||localStorage.getItem('erischat.apiBase')||'https://erischat-api-production.up.railway.app/v1').replace(/\/$/,'').replace(/\/v1$/,'');
const token=()=>localStorage.getItem('erischat.accessToken.v1')||localStorage.getItem('erischat_access_token')||'';
const req=async(path,opt={})=>{const r=await fetch(apiBase+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{}),Authorization:'Bearer '+token()}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||'İşlem başarısız');return b};
function addStyles(){if(document.getElementById('erisAdminCss'))return;const s=document.createElement('style');s.id='erisAdminCss';s.textContent=`
  .eris-admin-menu{grid-column:1/-1;min-height:76px;flex-direction:row;align-items:center;gap:14px;border-color:#8a5cff55;background:radial-gradient(240px 100px at 0 50%,#8a5cff26,transparent 75%),linear-gradient(120deg,#171222,#0c0a11)}
  .eris-admin-menu span{margin:0!important;width:46px;height:46px;display:grid;place-items:center;border:1px solid #a687ff55;border-radius:15px;background:#8a5cff18;font-size:23px!important}
  .eris-admin-menu strong{font-size:13px!important}.eris-admin-menu small{font-size:9px!important}.eris-admin-menu .ea-role{margin-left:auto;padding:7px 10px;border-radius:999px;background:#8a5cff18;color:#d9c8ff;font-size:9px;font-weight:900;letter-spacing:.7px}
  .eris-admin-overlay{position:fixed;inset:0;z-index:10000;display:grid;place-items:center;padding:16px;background:#030208d9;backdrop-filter:blur(14px)}
  .eris-admin-panel{width:min(760px,100%);max-height:min(90dvh,900px);overflow:auto;padding:clamp(16px,4vw,28px);border:1px solid #ffffff20;border-radius:26px;background:radial-gradient(600px 250px at 100% 0,#8a5cff20,transparent 70%),linear-gradient(155deg,#171321,#09080e 75%);color:#f8f6fc;box-shadow:0 32px 110px #000c}
  .ea-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;margin-bottom:18px}.ea-kicker{color:#b7a0ff;font-size:9px;font-weight:900;letter-spacing:1.5px}.ea-title{margin:4px 0;font-size:clamp(21px,5vw,30px);letter-spacing:-.7px}.ea-sub{color:#aaa1b1;font-size:11px}.ea-close{width:42px;height:42px;border:1px solid #ffffff16;border-radius:14px;background:#ffffff09;color:#fff;font-size:20px}
  .ea-profile{display:flex;align-items:center;gap:12px;padding:14px;border:1px solid #ffffff13;border-radius:17px;background:#ffffff06;margin-bottom:20px}.ea-shield{width:42px;height:42px;display:grid;place-items:center;border-radius:14px;background:linear-gradient(135deg,#7047d8,#a74bc1);font-size:20px}.ea-profile small{display:block;color:#a9a1b0;margin-top:4px;font-size:10px}.ea-role{margin-left:auto;padding:7px 10px;border-radius:99px;background:#8a5cff1c;color:#dbcaff;font-size:9px;font-weight:900;letter-spacing:.6px}
  .ea-section{margin:17px 0 8px;color:#a99db4;font-size:9px;font-weight:900;letter-spacing:1.2px;text-transform:uppercase}.eris-admin-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,210px),1fr));gap:9px}.eris-admin-grid button,.eris-admin-panel button.ea-action{min-height:58px;padding:12px;text-align:left;border:1px solid #ffffff14;border-radius:15px;background:linear-gradient(145deg,#1b1725,#100e17);color:#f6f1fb;font-size:11px;font-weight:800;transition:transform .18s,border-color .18s,background .18s}.eris-admin-grid button:hover{transform:translateY(-2px);border-color:#aa84ff88;background:#211934}.eris-admin-grid button:disabled,.eris-admin-panel button:disabled{opacity:.55;cursor:wait}
  .eris-admin-card{background:#ffffff07;border:1px solid #ffffff13;border-radius:15px;padding:14px;margin:9px 0;color:#eee9f4;font-size:11px;line-height:1.5}.eris-admin-panel h3{font-size:18px}.eris-admin-panel pre{white-space:pre-wrap;overflow:auto;font-size:10px;color:#d0c5dc}.ea-back{margin-top:14px!important;border:1px solid #ffffff18!important;border-radius:12px!important;background:#ffffff08!important;color:#fff!important;padding:10px 14px!important}
  .ea-float{position:fixed;right:14px;bottom:22px;z-index:22000;width:min(350px,calc(100vw - 28px));padding:18px 48px 18px 18px;border:1px solid #b495ec88;border-radius:19px;background:#261936ed;color:white;box-shadow:0 18px 55px #000b;backdrop-filter:blur(12px)}.ea-float button[data-close]{position:absolute;top:8px;right:9px}.ea-float button{border:1px solid #ffffff33;border-radius:10px;background:#ffffff18;color:white;padding:7px 10px}.ea-ban-person{display:flex;align-items:center;gap:12px}.ea-ban-portrait{position:relative;width:58px;height:58px;flex:none}.ea-ban-portrait img{width:52px;height:52px;border-radius:50%;object-fit:cover}.ea-ban-portrait img.frame{position:absolute;inset:0;width:58px;height:58px;object-fit:contain}.ea-ban-actions{display:flex;gap:8px;margin-top:12px}.ea-ban-actions button{flex:1;min-height:42px;border:0;border-radius:12px;color:white;font-weight:800}.ea-ban-actions .approve{background:#18835e}.ea-ban-actions .reject{background:#b43852}.ea-ban-proof{width:70px;height:70px;object-fit:cover;border-radius:8px;margin:5px;cursor:zoom-in}
  /* Match the room center's spacious cards and violet glass panel. */
  .eris-admin-panel{border-color:#b999db38;border-radius:30px;background:radial-gradient(circle at 100% 0,#9b4fbe32,transparent 50%),linear-gradient(155deg,#21172b,#100e17 72%)}
  .ea-kicker{font-size:11px;letter-spacing:2.2px}.ea-title{font-size:clamp(26px,5vw,38px)}.ea-sub{font-size:13px;line-height:1.5}
  .ea-section{font-size:11px;letter-spacing:1.8px;margin:22px 0 11px}
  .eris-admin-grid{gap:12px}.eris-admin-grid button{min-height:90px;padding:17px;border-radius:23px;font-size:13px;line-height:1.4}
  .ea-profile{border-radius:23px;padding:18px}.ea-shield{width:52px;height:52px;border-radius:17px}
  @media(max-width:520px){.eris-admin-overlay{padding:8px;align-items:end}.eris-admin-panel{max-height:94dvh;border-radius:28px 28px 18px 18px}.eris-admin-grid{grid-template-columns:1fr 1fr}.eris-admin-grid button{min-height:96px;font-size:12px;padding:13px}}
  @media(prefers-reduced-motion:reduce){.eris-admin-panel *{transition:none!important}}
`;document.head.appendChild(s)}
function adminMenu(me){const role=me.role,fa=role==='FA',da=role==='DA',ua=role==='UA';let html='<div class="ea-profile"><div class="ea-shield">🛡️</div><div><b>'+escapeHtml(me.nickname||'Yönetici')+'</b><small>Ghost Mode '+(me.ghost_mode?'açık':'kapalı')+'</small></div><span class="ea-role">'+escapeHtml(role)+'</span></div><div class="ea-section">Günlük operasyon</div><div class="eris-admin-grid">'+(da?'<button data-a="ghost">👻　Ghost Mode</button>':'')+'<button data-a="tickets">🎫　Destek talepleri</button>';if(fa||da)html+='<button data-a="announcement">📢　Duyuru gönder</button>';if(da)html+='<button data-a="gaps">🧩　Uygulama Geri Bildirimi Paneli</button>';if(ua||da)html+='<button data-a="ban">🚫　Kullanıcı Ban</button><button data-a="roomban">🏠　Oda Ban</button><button data-a="chatban">💬　CHAT/DM BAN</button>';html+='</div>';if(fa||da){html+='<div class="ea-section">Ban ve itiraz yönetimi</div><div class="eris-admin-grid"><button data-a="banrequests">🚫　Ban talepleri</button><button data-a="banlogs">📋　Ban işlem logları</button><button data-a="roombanrequests">🏠　Oda ban talepleri</button><button data-a="roombanlogs">📋　Oda ban işlem logları</button><button data-a="chatbanrequests">💬　Sohbet ban talepleri</button><button data-a="chatbanlogs">📋　Sohbet ban işlem logları</button><button data-a="banappeals">📝　İtiraz talepleri</button><button data-a="lidya">💰　Lidya işlemleri</button><button data-a="payments">🧾　Lidya Ödeme Bildirimleri Paneli</button></div>'}if(da)html+='<div class="ea-section">Geliştirici yönetimi</div><div class="eris-admin-grid"><button data-a="lookup">🔎　Kullanıcı ID sorgu</button><button data-a="calls">☎　Arama sorgu</button><button data-a="vip">👑　VIP seviyesi</button><button data-a="roles">👥　Yönetici rolleri</button><button data-a="faactions">📋　FA işlemleri</button></div>';return html}
function openPanel(me){addStyles();document.querySelector('.eris-admin-overlay')?.remove();const p=document.createElement('div');p.className='eris-admin-overlay';p.setAttribute('role','dialog');p.setAttribute('aria-modal','true');p.setAttribute('aria-label','Yönetim merkezi');p.innerHTML='<section class="eris-admin-panel"><header class="ea-head"><div><div class="ea-kicker">ERISCHAT • OPERASYON</div><h2 class="ea-title">Yönetim Merkezi</h2><div class="ea-sub">Yetki seviyene göre güvenli yönetim araçları.</div></div><button class="ea-close" data-close aria-label="Kapat">×</button></header><div id="eaBody"></div></section>';document.body.appendChild(p);p.querySelector('[data-close]').onclick=()=>p.remove();p.onclick=e=>{if(e.target===p)p.remove()};p.onkeydown=e=>{if(e.key==='Escape')p.remove()};const b=p.querySelector('#eaBody');b.innerHTML=adminMenu(me);b.querySelectorAll('[data-a]').forEach(x=>x.onclick=()=>action(x.dataset.a,me,p))};
async function action(a,me,p){try{
 if(a==='ghost'){if(me.role!=='DA')throw new Error('Ghost Mode yalnızca DA yetkililerine açıktır.');const r=await req('/v1/admin/ghost-mode',{method:'PATCH',body:JSON.stringify({enabled:!me.ghost_mode})});me.ghost_mode=r.enabled;window.toast?.('Ghost Mode '+(r.enabled?'açıldı':'kapatıldı'));p.remove();openPanel(me);if(r.enabled)showGhostNotice(me);return}
 if(a==='faactions'){await renderFaActions(p,me);return}
 if(a==='banrequests'){p.remove();window.ErisBan?.openRequests?.();return}
 if(a==='banlogs'){p.remove();window.ErisBan?.openLogs?.();return}
 if(a==='ban'){p.remove();window.ErisBan?.open?.();return}
 if(a==='chatban'){p.remove();window.ErisBan?.openChat?.();return}
 if(a==='chatbanrequests'){p.remove();window.ErisBan?.openChatRequests?.();return}
 if(a==='chatbanlogs'){p.remove();window.ErisBan?.openChatLogs?.();return}
 if(a==='roomban'){p.remove();window.ErisBan?.openRoom?.();return}
 if(a==='roombanrequests'){p.remove();window.ErisBan?.openRoomRequests?.();return}
 if(a==='roombanlogs'){p.remove();window.ErisBan?.openRoomLogs?.();return}
 if(a==='banappeals'){await renderBanAppeals(p,me);return}
 if(a==='gaps'){if(me.role!=='DA')throw new Error('Bu panel yalnızca DA yetkililerine açıktır.');p.remove();window.ErisSuggestions?.openAdmin?.();return}
 if(a==='lidya'){p.remove();window.ErisPurchases?.openManual?.();return}
 if(a==='payments'){p.remove();window.ErisPurchases?.openAdmin?.();return}
 if(a==='tickets'){p.remove();window.ErisSupport?.openAdmin?.();return}
 if(a==='announcement'){renderAnnouncement(p,me);return}
 if(['lookup','calls','vip','ban','roomban','chatban','roles','gaps'].includes(a)){showActionForm(a,me,p);return}
 if(a==='users'){const rows=await req('/v1/admin/users');showData(p,'👤 Gerçek Kullanıcılar',rows,me);return}
}catch(e){window.toast?.(e.message||'Yönetim işlemi başarısız')}}
async function showActionForm(actionKey,me,p){
 const body=p.querySelector('#eaBody'),titles={calls:'Arama sorgu',lookup:'Kullanıcı ID sorgu',lidya:'Lidya işlemleri',vip:'VIP seviyesi',ban:'Kullanıcı Ban',roomban:'Oda Ban',chatban:'CHAT/DM BAN',roles:'Yönetici rolleri',gaps:'Uygulama geri bildirimi'};
 body.replaceChildren();const title=document.createElement('h3');title.textContent=titles[actionKey];body.append(title);
 if(actionKey==='roles'){try{const rows=await req('/v1/admin/roles');const list=document.createElement('div');list.className='eris-admin-grid';for(const r of rows){const card=document.createElement('div');card.className='eris-admin-card';card.textContent=r.user_id+' • '+r.role+(r.ghost_mode?' • Ghost':'');list.append(card)}body.append(list)}catch(e){const err=document.createElement('div');err.className='eris-admin-card';err.textContent=e.message;body.append(err)}}
 const form=document.createElement('form');form.className='ea-form';form.style.cssText='display:grid;gap:10px;margin-top:12px';
 const fields={
   lookup:[['id','Kullanıcı ID veya 10 haneli profil ID','text']],
   calls:[['id','Kullanıcı ID veya 10 haneli profil ID','text']],
   vip:[['id','Kullanıcı ID veya 10 haneli profil ID','text'],['level','VIP seviyesi','number',0]],
   ban:[['id','Kullanıcı ID veya 10 haneli profil ID','text'],['operation','İşlem','select',['Hesap banı','Banı kaldır','Cihaz banı']],['days','Süre (gün); boş bırakınca süresiz','number',1],['reason','İşlem nedeni','text']],
   roomban:[['id','Oda ID veya 12 haneli oda ID','text'],['operation','İşlem','select',['Odayı yasakla','Banı kaldır']],['days','Süre (gün); boş bırakınca süresiz','number',1],['reason','İşlem nedeni','text']],
   chatban:[['id','Kullanıcı ID veya 10 haneli profil ID','text'],['operation','İşlem','select',['Sohbet banı','Banı kaldır']],['days','Süre (gün); boş bırakınca süresiz','number',1],['reason','İşlem nedeni','text']],
   roles:[['id','Kullanıcı ID veya 10 haneli profil ID','text'],['role','Yeni rol','select',['SA','UA','FA','DA']]],
   gaps:[['message','Geri bildirim / uygulama eksiği','textarea']]
 }[actionKey]||[];
 for(const [name,label,type,min] of fields){const wrap=document.createElement('label');wrap.className='ea-field';wrap.style.cssText='display:grid;gap:5px;color:#bcb3c7;font-size:10px;font-weight:750';const caption=document.createElement('span');caption.textContent=label;wrap.append(caption);let input;
   if(type==='select'){input=document.createElement('select');const values=actionKey==='lidya'?['add','remove']:actionKey==='roles'?min:actionKey==='ban'?['ban','unban','device']:['ban','unban'];min.forEach((text,i)=>{const opt=document.createElement('option');opt.value=values[i]||text;opt.textContent=text;input.append(opt)})}
   else if(type==='textarea'){input=document.createElement('textarea');input.rows=4;input.maxLength=2000;input.required=true}
   else{input=document.createElement('input');input.type=type;if(type==='number'){input.min=String(min);input.step='1';input.required=name!=='days';if(name==='level')input.max='12';if(name==='amount')input.max='1000000000';if(name==='days')input.max='3650';if(name==='level')input.value='0'}else{input.maxLength=128;input.required=true}}
   input.name=name;input.className='ea-input';input.style.cssText='width:100%;box-sizing:border-box;border:1px solid #ffffff1c;border-radius:12px;background:#0d0b13;color:#fff;padding:11px;font:inherit';wrap.append(input);form.append(wrap)
 }
 if(['ban','roomban','chatban'].includes(actionKey)){
   const days=form.elements.namedItem('days'),reason=form.elements.namedItem('reason');
   reason.required=true;reason.minLength=3;
   const choice=document.createElement('select');choice.name='duration_mode';choice.required=true;choice.innerHTML='<option value="">Ban süresini seçin</option><option value="limited">Gün sayısı</option><option value="indefinite">Süresiz</option>';choice.className='ea-input';choice.style.cssText='width:100%;padding:11px;border-radius:12px;background:#0d0b13;color:#fff';choice.onchange=()=>{days.required=choice.value==='limited';days.disabled=choice.value!=='limited';if(days.disabled)days.value=''};days.disabled=true;form.insertBefore(choice,form.firstChild);
   const note=document.createElement('small');note.textContent='Ban süresini ve nedenini doldurun.';form.append(note);
 }
 const status=document.createElement('div');status.className='ea-sub';status.setAttribute('role','status');const submit=document.createElement('button');submit.className='ea-action';submit.type='submit';submit.textContent='Devam et';form.append(submit,status);body.append(form);
 if(actionKey==='roles'){const revoke=document.createElement('button');revoke.type='button';revoke.className='ea-action';revoke.textContent='Yetki Al';revoke.onclick=async()=>{const id=form.elements.namedItem('id').value.trim();if(!id){status.textContent='Hedef kullanıcı ID girin.';return}revoke.disabled=true;try{await req('/v1/admin/roles/'+encodeURIComponent(id),{method:'DELETE'});status.textContent='Yetki kaldırıldı. Hesap standart kullanıcı oldu.'}catch(e){status.textContent=e.message}finally{revoke.disabled=false}};form.append(revoke)}
 const opField=form.elements.namedItem('operation'),reasonField=form.elements.namedItem('reason');if(opField&&reasonField){const toggleReason=()=>{const remove=opField.value==='unban',device=opField.value==='device',choice=form.elements.namedItem('duration_mode'),days=form.elements.namedItem('days');reasonField.required=!remove;choice.required=!remove;choice.disabled=remove;if(remove){days.required=false;days.disabled=true}else if(device){choice.value='indefinite';days.value='';days.disabled=true;days.required=false}else{days.disabled=choice.value!=='limited';days.required=choice.value==='limited'}};opField.addEventListener('change',toggleReason);toggleReason()}
 form.onsubmit=async event=>{event.preventDefault();submit.disabled=true;status.textContent='İşlem yapılıyor…';const v=Object.fromEntries(new FormData(form).entries()),id=encodeURIComponent(v.id||'');try{let result;
   if(!['lookup','calls','gaps'].includes(actionKey)&&!confirm(`${titles[actionKey]} işlemini ${v.id||''} için uygulamak istiyor musun?`)){submit.disabled=false;status.textContent='İşlem iptal edildi.';return}
   if(actionKey==='lookup')result=await req('/v1/admin/users/'+id);
   else if(actionKey==='calls'){result=await req('/v1/admin/calls/'+id);showCalls(p,result,me);return}
   else if(actionKey==='vip')result=await req('/v1/admin/users/'+id+'/vip',{method:'POST',body:JSON.stringify({level:Number(v.level)})});
   else if(actionKey==='roles')result=await req('/v1/admin/roles',{method:'PUT',body:JSON.stringify({user_id:v.id,role:v.role})});
   else if(actionKey==='gaps')result=await req('/v1/admin/application-gaps',{method:'POST',body:JSON.stringify({message:v.message})});
   else {const room=actionKey==='roomban',chat=actionKey==='chatban',device=actionKey==='ban'&&v.operation==='device',remove=v.operation==='unban';const path=room?'/v1/admin/rooms/'+id+'/ban':'/v1/admin/users/'+id+(chat?'/chat-ban':device?'/device-ban':'/ban');result=await req(path,{method:remove?'DELETE':'POST',...(remove?{}:{body:JSON.stringify({days:v.duration_mode==='indefinite'?null:Number(v.days),reason:v.reason})})});}
   if(result?.pending){openPanel(me);floating('Ban işleminiz yetkili DA’lara iletilmiştir.');return}
   showData(p,titles[actionKey],[result],me);window.toast?.('İşlem tamamlandı.');
  }catch(error){status.textContent=error.message||'İşlem başarısız.';submit.disabled=false}
 };
 const back=document.createElement('button');back.className='ea-back';back.type='button';back.textContent='← Yönetim merkezine dön';back.onclick=()=>openPanel(me);body.append(back)
}
function showGhostNotice(me){
 document.querySelector('[data-ghost-notice]')?.remove();
 floating('Ghost modu aktif, sevgili [DA] '+(me.nickname||'Yönetici')+'.\n\nOdalara görünmez girersin. Giriş bildirimi ve herkese açık giriş/çıkış kaydı gösterilmez.\n\n• Sohbete yazamazsın.\n• Kilitli odalara şifresiz girebilirsin.\n• Koltuğa oturamazsın veya mikrofon açamazsın.\n• Odalarda hediye gönderemezsin.\n\nNormal yetkilerine dönmek için Ghost Mode’u kapat. × yalnızca bu pencereyi gizler. Gizlilik esastır.');
 const box=document.querySelector('.ea-float:last-child');if(box){box.dataset.ghostNotice='';box.style.whiteSpace='pre-line';box.style.maxHeight='75dvh';box.style.overflowY='auto';box.style.background='#261936b8';}
}
function floating(message,appeal){addStyles();const box=document.createElement('div');box.className='ea-float';box.setAttribute('role','status');const label=document.createElement('div');label.textContent=message;const close=document.createElement('button');close.dataset.close='';close.textContent='×';close.setAttribute('aria-label','Kapat');close.onclick=()=>box.remove();box.append(label,close);if(appeal){const button=document.createElement('button');button.textContent='İtiraz et';button.style.marginTop='10px';button.onclick=()=>{box.remove();renderAppealModal(appeal)};box.append(button)}document.body.append(box)}
function portrait(asset,frame){const wrap=document.createElement('span');wrap.className='ea-ban-portrait';const img=document.createElement('img');img.src=window.ErisChatCosmetics?.assetUrl?.(asset)||'';img.alt='';wrap.append(img);if(frame){const border=document.createElement('img');border.className='frame';border.src=window.ErisChatCosmetics?.assetUrl?.(frame)||'';border.alt='';wrap.append(border)}return wrap}
function banCard(row,appeal){const card=document.createElement('article');card.className='eris-admin-card';const head=document.createElement('div');head.className='ea-ban-person';head.append(portrait(appeal?row.requester_avatar:row.target_avatar,appeal?row.requester_frame:row.target_frame));const title=document.createElement('b');title.textContent=appeal?row.requester_name:row.target_name;head.append(title);card.append(head);const meta=document.createElement('p');meta.textContent=(appeal?'İtiraz edilen: '+row.target_name+' • ID: '+row.target_id:'Süre: '+(row.days===null?'Süresiz':row.days+' gün'))+' • '+row.kind;card.append(meta);const reason=document.createElement('p');reason.textContent='Ban nedeni: '+row.reason;card.append(reason);return card}
async function renderBanRequests(p,me){const rows=await req('/v1/admin/ban-requests');const b=p.querySelector('#eaBody');b.replaceChildren();const h=document.createElement('h3');h.textContent='Ban talepleri';b.append(h);const pending=rows.filter(r=>r.status==='pending');if(!pending.length)b.append('Bekleyen talep yok.');for(const row of pending){const card=banCard(row,false),actions=document.createElement('div');actions.className='ea-ban-actions';for(const [label,action] of [['Ban onay','approve'],['Ban reddet','reject']]){const button=document.createElement('button');button.className=action;button.textContent=label;button.onclick=async()=>{button.disabled=true;try{await req('/v1/admin/ban-requests/'+row.id+'/decision',{method:'POST',body:JSON.stringify({action})});renderBanRequests(p,me)}catch(e){button.disabled=false;window.toast?.(e.message)}};actions.append(button)}card.append(actions);b.append(card)}const back=document.createElement('button');back.className='ea-back';back.textContent='← Yönetim merkezine dön';back.onclick=()=>openPanel(me);b.append(back)}
async function renderBanAppeals(p,me){const rows=await req('/v1/admin/ban-appeals');const b=p.querySelector('#eaBody');b.replaceChildren();const h=document.createElement('h3');h.textContent='İtiraz talepleri';b.append(h);const pending=rows.filter(r=>r.status==='pending');if(!pending.length)b.append('Bekleyen itiraz yok.');for(const appeal of pending){const row=appeal.request,card=banCard(row,true);for(const text of ['İtiraz nedeni: '+appeal.reason,'Açıklama: '+appeal.explanation]){const para=document.createElement('p');para.textContent=text;card.append(para)}for(const source of appeal.images){const image=document.createElement('img');image.className='ea-ban-proof';image.src=source;image.alt='İtiraz kanıtı';image.onclick=()=>{const modal=document.createElement('div');modal.className='eris-admin-overlay';const full=document.createElement('img');full.src=source;full.alt='Büyütülmüş kanıt';full.style.cssText='max-width:95vw;max-height:90vh;object-fit:contain';modal.append(full);modal.onclick=()=>modal.remove();document.body.append(modal)};card.append(image)}const actions=document.createElement('div');actions.className='ea-ban-actions';for(const [label,action] of [['İtirazı onayla','approve'],['İtirazı reddet','reject']]){const button=document.createElement('button');button.className=action;button.textContent=label;button.onclick=async()=>{button.disabled=true;try{await req('/v1/admin/ban-appeals/'+appeal.id+'/decision',{method:'POST',body:JSON.stringify({action})});renderBanAppeals(p,me)}catch(e){button.disabled=false;window.toast?.(e.message)}};actions.append(button)}card.append(actions);b.append(card)}const back=document.createElement('button');back.className='ea-back';back.textContent='← Yönetim merkezine dön';back.onclick=()=>openPanel(me);b.append(back)}
function renderAppealModal(row){addStyles();const overlay=document.createElement('div');overlay.className='eris-admin-overlay';overlay.innerHTML='<section class="eris-admin-panel"><h3>Ban talebine itiraz</h3><form class="ea-form" style="display:grid;gap:12px"><label>İtiraz nedeni<input name="reason" maxlength="200" minlength="3" required></label><label>Açıklama (en fazla 400 karakter)<textarea name="explanation" maxlength="400" required></textarea></label><label>Kanıt (en fazla 3 fotoğraf)<input name="images" type="file" accept="image/png,image/jpeg,image/webp" multiple></label><button class="ea-action" type="submit">İtirazı gönder</button><button type="button" data-close>Kapat</button></form></section>';document.body.append(overlay);overlay.querySelector('[data-close]').onclick=()=>overlay.remove();overlay.querySelector('form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,files=[...form.elements.images.files];if(files.length>3||files.some(f=>f.size>1500000)){window.toast?.('En fazla 3 fotoğraf, her biri 1,5 MB.');return}const images=await Promise.all(files.map(file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})));try{await req('/v1/admin/ban-requests/'+row.id+'/appeal',{method:'POST',body:JSON.stringify({reason:form.elements.reason.value,explanation:form.elements.explanation.value,images})});overlay.remove();floating('İtirazınız DA yetkililerine iletildi.')}catch(error){window.toast?.(error.message)}}}
let currentAdminId=null,currentAdminRole=null;let seenDecisions=new Set(JSON.parse(localStorage.getItem('eris.admin.decisions')||'[]'));
async function checkDecisions(){if(!token())return;try{const rows=await req('/v1/admin/ban-requests');for(const row of rows){if(row.workflow)continue;if(row.requester_id!==currentAdminId||!['approved','rejected'].includes(row.status)||seenDecisions.has(row.id))continue;seenDecisions.add(row.id);localStorage.setItem('eris.admin.decisions',JSON.stringify([...seenDecisions].slice(-200)));floating(row.target_name+' isimli kullanıcı için yapmış olduğunuz ban talebi '+(row.status==='approved'?'onaylanmıştır.':'reddedilmiştir.'),row.status==='rejected'&&!row.appeal_used?row:null)}const appeals=await req('/v1/admin/ban-appeals').catch(()=>[]);for(const appeal of appeals){if(appeal.request.requester_id!==currentAdminId||appeal.status!=='rejected')continue;const key='appeal-'+appeal.id;if(seenDecisions.has(key))continue;seenDecisions.add(key);localStorage.setItem('eris.admin.decisions',JSON.stringify([...seenDecisions].slice(-200)));floating(appeal.request.target_name+' isimli kullanıcı için yapmış olduğunuz ban itirazınız reddedilmiştir.')}}catch{}}
setInterval(checkDecisions,15000);
async function renderFaActions(p,me){const rows=await req('/v1/admin/fa-actions'),body=p.querySelector('#eaBody');body.replaceChildren();const title=document.createElement('h3');title.textContent='FA işlemleri';body.append(title);if(!rows.length){const empty=document.createElement('p');empty.textContent='Henüz FA işlemi yok.';body.append(empty)}for(const row of rows){const card=document.createElement('article');card.className='eris-admin-card';const head=document.createElement('b');head.textContent=new Date(row.created_at).toLocaleString('tr-TR',{dateStyle:'short',timeStyle:'medium'})+' • '+row.admin_name+' • '+row.action;const target=document.createElement('p');target.textContent=(row.target_name||'')+(row.target_id?' • ID: '+row.target_id:'');const details=document.createElement('pre');details.textContent=JSON.stringify(row.details,null,2);card.append(head,target,details);body.append(card)}const back=document.createElement('button');back.className='ea-back';back.textContent='← Yönetim merkezine dön';back.onclick=()=>openPanel(me);body.append(back)}
const incomingSeen=new Set(JSON.parse(sessionStorage.getItem('eris.admin.incoming')||'[]'));
async function checkIncoming(){if(!currentAdminId||!['FA','DA'].includes(currentAdminRole))return;try{const requests=await req('/v1/admin/ban-requests'),appeals=await req('/v1/admin/ban-appeals');for(const row of requests.filter(x=>x.status==='pending'&&!x.workflow)){const key='request-'+row.id;if(incomingSeen.has(key))continue;incomingSeen.add(key);incomingBubble(row,null)}for(const appeal of appeals.filter(x=>x.status==='pending')){const key='appeal-'+appeal.id;if(incomingSeen.has(key))continue;incomingSeen.add(key);incomingBubble(appeal.request,appeal)}sessionStorage.setItem('eris.admin.incoming',JSON.stringify([...incomingSeen].slice(-300)))}catch{}}
function incomingBubble(row,appeal){addStyles();const box=document.createElement('aside');box.className='ea-float ea-incoming';box.style.bottom='max(22px,env(safe-area-inset-bottom))';box.style.maxHeight='80vh';box.style.overflow='auto';const close=document.createElement('button');close.dataset.close='';close.textContent='×';close.setAttribute('aria-label','Kapat');close.onclick=()=>box.remove();const who=document.createElement('div');who.className='ea-ban-person';who.append(portrait(row.requester_avatar,row.requester_frame));const name=document.createElement('b');name.textContent=row.requester_name;who.append(name);box.append(close,who);for(const value of [appeal?'İtiraz talebi':'Ban talebi',row.target_name+' • ID: '+(row.target_id||'—'),row.kind+' • '+(row.days===null?'Süresiz':row.days+' gün'),'Ban nedeni: '+row.reason,...(appeal?['İtiraz nedeni: '+appeal.reason,'Açıklama: '+appeal.explanation]:[])]){const line=document.createElement('p');line.textContent=value;box.append(line)}if(appeal)for(const source of appeal.images){const image=document.createElement('img');image.className='ea-ban-proof';image.src=source;image.alt='İtiraz kanıtı';image.onclick=()=>{const modal=document.createElement('div');modal.className='eris-admin-overlay';const enlarged=document.createElement('img');enlarged.src=source;enlarged.alt='Büyütülmüş kanıt';enlarged.style.cssText='max-width:95vw;max-height:90vh;object-fit:contain';modal.append(enlarged);modal.onclick=()=>modal.remove();document.body.append(modal)};box.append(image)}const actions=document.createElement('div');actions.className='ea-ban-actions';for(const [label,action] of [['Ban onay','approve'],['Ban reddet','reject']]){const button=document.createElement('button');button.className=action;button.textContent=appeal?(action==='approve'?'İtirazı onayla':'İtirazı reddet'):label;button.onclick=async()=>{button.disabled=true;const path=appeal?'/v1/admin/ban-appeals/'+appeal.id:'/v1/admin/ban-requests/'+row.id;try{await req(path+'/decision',{method:'POST',body:JSON.stringify({action})});box.remove();window.toast?.('Karar kaydedildi.')}catch(e){button.disabled=false;window.toast?.(e.message)}};actions.append(button)}box.append(actions);document.body.append(box)}
setInterval(checkIncoming,12000);
function showCalls(p,result,me){const body=p.querySelector('#eaBody');body.replaceChildren();const h=document.createElement('h3');h.textContent='☎ Arama sorgu';body.append(h);const person=document.createElement('article');person.className='eris-admin-card';person.style.cssText='display:flex;align-items:center;gap:14px';const portrait=document.createElement('div');portrait.style.cssText='position:relative;width:58px;height:58px;flex:none';const avatar=document.createElement('img');avatar.src=window.ErisChatCosmetics?.assetUrl?.(result.user.avatar_asset)||'';avatar.alt='';avatar.style.cssText='width:50px;height:50px;border-radius:50%;object-fit:cover';portrait.append(avatar);if(result.user.frame_asset){const frame=document.createElement('img');frame.src=window.ErisChatCosmetics?.assetUrl?.(result.user.frame_asset)||'';frame.alt='';frame.style.cssText='position:absolute;inset:0;width:58px;height:58px;object-fit:contain';portrait.append(frame)}const label=document.createElement('b');label.textContent=result.user.nickname+' • '+result.user.public_id;person.append(portrait,label);body.append(person);for(const row of result.calls){const card=document.createElement('article');card.className='eris-admin-card';const date=new Date(row.created_at).toLocaleString('tr-TR');card.textContent=(row.kind==='video'?'📹':'☎')+' '+date+' • '+(row.incoming?'Gelen':'Giden')+' • '+row.peer_name+' • '+row.status+' • '+Math.floor(row.duration_seconds/60)+' dk '+row.duration_seconds%60+' sn';body.append(card)}if(!result.calls.length){const empty=document.createElement('p');empty.textContent='Arama kaydı yok.';body.append(empty)}const back=document.createElement('button');back.className='ea-back';back.textContent='← Yönetim merkezine dön';back.onclick=()=>openPanel(me);body.append(back)}
function showData(p,title,data,me){const b=p.querySelector('#eaBody');b.replaceChildren();const h=document.createElement('h3');h.textContent=title;b.append(h);const rows=Array.isArray(data)?data:[data];if(!rows.length){const empty=document.createElement('div');empty.className='eris-admin-card';empty.textContent='Gösterilecek kayıt yok.';b.append(empty)}for(const row of rows){const card=document.createElement('article');card.className='eris-admin-card';const heading=document.createElement('b');heading.textContent=row?.nickname||row?.subject||row?.name||row?.title||((row?.id||row?.user_id)?'#'+(row.id||row.user_id):'Kayıt');card.append(heading);const summary=document.createElement('div');summary.style.cssText='color:#aaa1b1;font-size:10px;margin-top:5px';summary.textContent=[row?.status,row?.role,row?.public_id,row?.created_at].filter(Boolean).join(' • ')||'Yönetim kaydı';card.append(summary);const details=document.createElement('details');details.style.marginTop='10px';const label=document.createElement('summary');label.textContent='Kayıt ayrıntıları';const pre=document.createElement('pre');pre.textContent=JSON.stringify(row,null,2);details.append(label,pre);card.append(details);b.append(card)}const back=document.createElement('button');back.className='ea-back';back.textContent='← Yönetim merkezine dön';back.onclick=()=>openPanel(me);b.append(back)}
function showTickets(p,rows,me){const b=p.querySelector('#eaBody');b.replaceChildren();const title=document.createElement('h3');title.textContent='🎫 Destek talepleri';b.append(title);if(!rows.length){const empty=document.createElement('div');empty.className='eris-admin-card';empty.textContent='Bekleyen destek talebi yok.';b.append(empty)}for(const ticket of rows){const card=document.createElement('div');card.className='eris-admin-card';const label=document.createElement('b');label.textContent='#'+ticket.id+' • '+ticket.subject;const meta=document.createElement('div');meta.textContent=(ticket.category||'Genel')+' • '+ticket.status+' • '+ticket.user_id+(ticket.has_attachments?' • 📷 Fotoğraf var':'');const open=document.createElement('button');open.className='ea-action';open.textContent='Talebi incele →';open.onclick=()=>showTicket(p,ticket.id,me);card.append(label,meta,open);b.append(card)}const back=document.createElement('button');back.className='ea-back';back.textContent='← Yönetim merkezine dön';back.onclick=()=>openPanel(me);b.append(back)}
async function showTicket(p,id,me){const b=p.querySelector('#eaBody');b.textContent='Talep yükleniyor…';try{const ticket=await req('/v1/admin/tickets/'+encodeURIComponent(id));b.replaceChildren();const title=document.createElement('h3');title.textContent='#'+ticket.id+' • '+ticket.subject;const meta=document.createElement('div');meta.className='eris-admin-card';meta.textContent=(ticket.category||'Genel')+' • '+ticket.status+' • '+ticket.user_id;b.append(title,meta);const messages=ticket.messages?.length?ticket.messages:[{sender_role:'USER',message:ticket.message,attachments:ticket.attachments||[]}];for(const row of messages){const item=document.createElement('article');item.className='eris-admin-card';const who=document.createElement('b');who.textContent=['USER','US'].includes(row.sender_role)?'Kullanıcı':'ErisChat Yönetim';const body=document.createElement('p');body.textContent=row.message||'';body.style.cssText='white-space:pre-wrap;line-height:1.5';item.append(who,body);(row.attachments||[]).forEach(src=>{const img=document.createElement(src.startsWith('data:video/')?'video':'img');img.src=src;if(img.tagName==='VIDEO'){img.controls=true;img.preload='metadata'}else img.alt='Destek talebine eklenen fotoğraf';img.style.cssText='display:block;width:min(100%,260px);max-height:260px;object-fit:contain;border-radius:12px;margin:7px 0';item.append(img)});b.append(item)}const controls=document.createElement('div');controls.className='eris-admin-grid';const button=(label,fn)=>{const x=document.createElement('button');x.textContent=label;x.onclick=fn;controls.append(x);return x};if(['pending','open'].includes(ticket.status))button('Kabul et',async()=>{await req('/v1/admin/tickets/'+id+'/accept',{method:'POST'});await showTicket(p,id,me)});if(['pending','open','accepted'].includes(ticket.status)){button('Reddet',async()=>{const note=prompt('Red nedeni (isteğe bağlı):','');if(note===null)return;await req('/v1/admin/tickets/'+id+'/reject',{method:'POST',body:JSON.stringify({note})});await showTicket(p,id,me)});const input=document.createElement('textarea');input.className='eris-admin-card';input.placeholder='Kullanıcıya yanıt yaz';input.maxLength=4000;input.style.cssText='width:100%;box-sizing:border-box;color:#fff;background:#111827';controls.append(input);button('Yanıt gönder',async()=>{const text=input.value.trim();if(!text)return window.toast?.('Yanıt metni yaz.');await req('/v1/admin/tickets/'+id+'/message',{method:'POST',body:JSON.stringify({message:text})});await showTicket(p,id,me)});button('Kapat',async()=>{const note=prompt('Sonuç: supported veya unsupported','supported');if(note===null)return;await req('/v1/admin/tickets/'+id+'/close',{method:'POST',body:JSON.stringify({note})});await showTicket(p,id,me)})}b.append(controls);const back=document.createElement('button');back.textContent='← Talepler';back.onclick=async()=>showTickets(p,await req('/v1/admin/tickets'),me);b.append(back)}catch(e){b.textContent=e.message||'Destek talebi açılamadı.'}}
function renderAnnouncement(p,me){const b=p.querySelector('#eaBody');b.replaceChildren();const title=document.createElement('h3');title.textContent='📢 Tüm kullanıcılara duyuru';const note=document.createElement('div');note.className='eris-admin-card';note.textContent='Duyuru tüm kullanıcılara “ErisChat Yönetim” adıyla görünür ve yanıtlanamaz.';const form=document.createElement('form');form.style.cssText='display:grid;gap:10px';const input=document.createElement('textarea');input.required=true;input.minLength=3;input.maxLength=4000;input.placeholder='Duyuru mesajı';input.style.cssText='width:100%;min-height:140px;box-sizing:border-box;padding:12px;border-radius:12px;background:#111827;color:white;border:1px solid #374151';const send=document.createElement('button');send.type='submit';send.className='ea-action';send.textContent='Duyuruyu yayınla';const status=document.createElement('div');status.className='ea-sub';status.setAttribute('role','status');form.append(input,send,status);form.onsubmit=async e=>{e.preventDefault();const message=input.value.trim();if(message.length<3)return;send.disabled=true;status.textContent='Yayınlanıyor…';try{const result=await req('/v1/admin/announcements',{method:'POST',body:JSON.stringify({message})});input.value='';status.textContent='Yayınlandı • '+new Date(result.created_at).toLocaleString('tr-TR')}catch(err){status.textContent=err.message||'Duyuru yayınlanamadı.'}finally{send.disabled=false}};const back=document.createElement('button');back.type='button';back.className='ea-back';back.textContent='← Yönetim merkezine dön';back.onclick=()=>openPanel(me);b.append(title,note,form,back)}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
window.ErisAdmin={clear:function(){document.querySelectorAll('.eris-admin-btn,.eris-admin-menu,.eris-admin-overlay').forEach(el=>el.remove())}};
async function boot(){window.ErisAdmin.clear();try{const me=await req('/v1/admin/me');currentAdminId=me.id;currentAdminRole=me.role;const mount=document.getElementById('adminMenuMount');if(!mount)return;addStyles();const btn=document.createElement('button');btn.type='button';btn.className='homeMenuItem eris-admin-menu';btn.setAttribute('aria-label','Yönetim merkezini aç');btn.innerHTML='<svg class="homeMenuIcon" aria-hidden="true"><use href="#home-security"></use></svg><div class="homeMenuCopy"><strong>Yönetim Merkezi</strong><small>Güvenlik, destek ve hesap araçları</small></div><b class="ea-role">'+escapeHtml(me.role)+'</b>';btn.onclick=()=>openPanel(me);mount.replaceChildren(btn);checkDecisions();checkIncoming()}catch(_){} }
if(document.readyState==='complete')setTimeout(boot,350);else window.addEventListener('load',()=>setTimeout(boot,350),{once:true});
window.addEventListener('erischat:auth',()=>setTimeout(boot,150));
})();
