(function(){
'use strict';
const apiBase=(window.ERISCHAT_API_BASE||window.ERIS_API||localStorage.getItem('erischat.apiBase')||'https://erischat-api-production.up.railway.app/v1').replace(/\/$/,'').replace(/\/v1$/,'');
const token=()=>localStorage.getItem('erischat.accessToken.v1')||localStorage.getItem('erischat_access_token')||'';
const req=async(path,opt={})=>{const r=await fetch(apiBase+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{}),Authorization:'Bearer '+token()}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||'İşlem başarısız');return b};
function addStyles(){if(document.getElementById('erisAdminCss'))return;const s=document.createElement('style');s.id='erisAdminCss';s.textContent='.eris-admin-btn{position:fixed;right:16px;bottom:16px;z-index:9998;padding:10px 14px;border:1px solid #7c3aed;border-radius:12px;background:#111827;color:#fff;font-weight:700;box-shadow:0 8px 30px #0008}.eris-admin-panel{position:fixed;inset:5%;z-index:10000;background:#0b1020;color:#eef2ff;border:1px solid #374151;border-radius:18px;padding:20px;overflow:auto;box-shadow:0 20px 80px #000c}.eris-admin-panel button{margin:5px;padding:9px 12px;border-radius:9px;border:1px solid #4b5563;background:#182033;color:#fff}.eris-admin-card{background:#111827;border:1px solid #263246;border-radius:12px;padding:12px;margin:10px 0}.eris-admin-danger{color:#fca5a5}.eris-admin-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:8px}';document.head.appendChild(s)}
function openPanel(me){addStyles();const p=document.createElement('div');p.className='eris-admin-panel';p.innerHTML='<h2>🛡️ Yönetim Merkezi</h2><div id="eaBody"></div><button id="eaClose">Kapat</button>';document.body.appendChild(p);p.querySelector('#eaClose').onclick=()=>p.remove();const b=p.querySelector('#eaBody');b.innerHTML='<div class="eris-admin-card"><b>['+me.role+'] '+escapeHtml(me.nickname)+'</b><br>Ghost Mode: '+(me.ghost_mode?'Açık':'Kapalı')+'</div><div class="eris-admin-grid"><button data-a="ghost">👻 Ghost Mode</button><button data-a="tickets">🎫 Destek Talepleri</button>'+(me.role!=='SA'?'<button data-a="reports">⚠️ Şikayetler</button><button data-a="gaps">🧩 Uygulama Eksikleri</button>':'')+(me.role!=='SA'?'<button data-a="ban">🚫 Ban / Unban</button><button data-a="roomban">🏠 Oda Ban</button><button data-a="chatban">💬 Chat Ban</button>':'')+(me.role==='DA'?'<button data-a="lookup">🔎 ID Sorgu</button><button data-a="lidya">💰 Lidya</button><button data-a="vip">👑 VIP</button><button data-a="roles">👥 SA / UA / DA</button></div>':'')+'</div>';b.querySelectorAll('[data-a]').forEach(x=>x.onclick=()=>action(x.dataset.a,me,p))};
async function action(a,me,p){try{
 if(a==='ghost'){const r=await req('/v1/admin/ghost-mode',{method:'PATCH',body:JSON.stringify({enabled:!me.ghost_mode})});me.ghost_mode=r.enabled;window.toast?.('Ghost Mode '+(r.enabled?'açıldı':'kapatıldı'));p.remove();openPanel(me);return}
 if(a==='tickets'){const rows=await req('/v1/admin/tickets');showTickets(p,rows,me);return}
 if(a==='users'){const rows=await req('/v1/admin/users');showData(p,'👤 Gerçek Kullanıcılar',rows);return}
 if(a==='reports'){const rows=await req('/v1/admin/reports');showData(p,'⚠️ Şikayetler',rows);return}
 if(a==='gaps'){const message=prompt('Uygulama eksiğini yaz:');if(message)await req('/v1/admin/application-gaps',{method:'POST',body:JSON.stringify({message})});window.toast?.('Eksik kaydedildi');return}
 if(a==='lookup'){const id=prompt('Kullanıcı ID:');if(!id)return;showData(p,'🔎 ID Sorgu',[await req('/v1/admin/users/'+encodeURIComponent(id))]);return}
 if(a==='lidya'){const id=prompt('Kullanıcı ID:');if(!id)return;const amount=Number(prompt('Miktar:'));if(!amount)return;const op=prompt('add = ekle, remove = çıkar','add');const r=await req('/v1/admin/users/'+encodeURIComponent(id)+'/lidya/'+(op==='remove'?'remove':'add'),{method:'POST',body:JSON.stringify({amount})});showData(p,'💰 Lidya',[r]);return}
 if(a==='ban'){const id=prompt('Kullanıcı ID:');if(!id)return;const days=prompt('Gün (boş = süresiz):');const op=prompt('ban / unban / device','ban');if(op==='unban'){await req('/v1/admin/users/'+encodeURIComponent(id)+'/ban',{method:'DELETE'});window.toast?.('Ban kaldırıldı')}else{await req('/v1/admin/users/'+encodeURIComponent(id)+(op==='device'?'/device-ban':'/ban'),{method:'POST',body:JSON.stringify({days:days===''||days===null?null:Number(days),reason:'DA yönetim işlemi'})});window.toast?.('Ban uygulandı')}return}
 if(a==='roomban'){const id=prompt('Oda ID:');if(!id)return;const days=prompt('Gün (boş = süresiz):');const op=prompt('ban / unban','ban');if(op==='unban')await req('/v1/admin/rooms/'+encodeURIComponent(id)+'/ban',{method:'DELETE'});else await req('/v1/admin/rooms/'+encodeURIComponent(id)+'/ban',{method:'POST',body:JSON.stringify({days:days===''||days===null?null:Number(days),reason:'DA yönetim işlemi'})});window.toast?.('Oda işlemi tamam');return}
 if(a==='chatban'){const id=prompt('Kullanıcı ID:');if(!id)return;const days=prompt('Gün (boş = süresiz):');const op=prompt('ban / unban','ban');if(op==='unban')await req('/v1/admin/users/'+encodeURIComponent(id)+'/chat-ban',{method:'DELETE'});else await req('/v1/admin/users/'+encodeURIComponent(id)+'/chat-ban',{method:'POST',body:JSON.stringify({days:days===''||days===null?null:Number(days),reason:'DA yönetim işlemi'})});window.toast?.('Chat ban işlemi tamam');return}
 if(a==='vip'){const id=prompt('Kullanıcı ID:');if(!id)return;const level=Number(prompt('VIP seviyesi (0-12):'));const r=await req('/v1/admin/users/'+encodeURIComponent(id)+'/vip',{method:'POST',body:JSON.stringify({level})});showData(p,'👑 VIP',[r]);return}
 if(a==='roles'){const rows=await req('/v1/admin/roles');showData(p,'👥 Yönetici Yetkileri',rows);const id=prompt('Yeni/değişecek admin kullanıcı ID (iptal = sadece liste):');if(id){const role=prompt('Rol: SA / UA / DA');if(role)await req('/v1/admin/roles',{method:'PUT',body:JSON.stringify({user_id:id,role})});}return}
}catch(e){window.toast?.(e.message||'Yönetim işlemi başarısız')}}
function showData(p,title,data){const b=p.querySelector('#eaBody');b.innerHTML='<h3>'+title+'</h3><pre class="eris-admin-card" style="white-space:pre-wrap">'+escapeHtml(JSON.stringify(data,null,2))+'</pre><button id="eaBack">← Yönetim</button>';b.querySelector('#eaBack').onclick=()=>{p.remove();location.reload()}}
function showTickets(p,rows,me){const b=p.querySelector('#eaBody');b.replaceChildren();const title=document.createElement('h3');title.textContent='🎫 Destek Talepleri';b.append(title);if(!rows.length){const empty=document.createElement('div');empty.className='eris-admin-card';empty.textContent='Bekleyen destek talebi yok.';b.append(empty)}for(const ticket of rows){const card=document.createElement('div');card.className='eris-admin-card';const label=document.createElement('b');label.textContent='#'+ticket.id+' • '+ticket.subject;const meta=document.createElement('div');meta.textContent=(ticket.category||'Genel')+' • '+ticket.status+' • '+ticket.user_id;const open=document.createElement('button');open.textContent='Talebi aç';open.onclick=()=>showTicket(p,ticket.id,me);card.append(label,meta,open);b.append(card)}const back=document.createElement('button');back.textContent='← Yönetim';back.onclick=()=>{p.remove();location.reload()};b.append(back)}
async function showTicket(p,id,me){const b=p.querySelector('#eaBody');b.textContent='Talep yükleniyor…';try{const ticket=await req('/v1/admin/tickets/'+encodeURIComponent(id));b.replaceChildren();const title=document.createElement('h3');title.textContent='#'+ticket.id+' • '+ticket.subject;const meta=document.createElement('div');meta.className='eris-admin-card';meta.textContent=(ticket.category||'Genel')+' • '+ticket.status+' • '+ticket.user_id;const message=document.createElement('div');message.className='eris-admin-card';message.textContent=ticket.message;b.append(title,meta,message);for(const row of ticket.messages||[]){const item=document.createElement('div');item.className='eris-admin-card';item.textContent=(row.sender_role||'')+': '+row.message;b.append(item)}
 const controls=document.createElement('div');controls.className='eris-admin-grid';const button=(label,fn)=>{const x=document.createElement('button');x.textContent=label;x.onclick=fn;controls.append(x);return x};
 if(['pending','open'].includes(ticket.status))button('Kabul et',async()=>{await req('/v1/admin/tickets/'+id+'/accept',{method:'POST'});await showTicket(p,id,me)});
 if(['pending','open','accepted'].includes(ticket.status)){
  button('Reddet',async()=>{const note=prompt('Red nedeni (isteğe bağlı):','');if(note===null)return;await req('/v1/admin/tickets/'+id+'/reject',{method:'POST',body:JSON.stringify({note})});await showTicket(p,id,me)});
  const input=document.createElement('textarea');input.className='eris-admin-card';input.placeholder='Kullanıcıya yanıt yaz';input.maxLength=4000;input.style.cssText='width:100%;box-sizing:border-box;color:#fff;background:#111827';controls.append(input);
  button('Yanıt gönder',async()=>{const text=input.value.trim();if(!text)return window.toast?.('Yanıt metni yaz.');await req('/v1/admin/tickets/'+id+'/message',{method:'POST',body:JSON.stringify({message:text})});await showTicket(p,id,me)});
  button('Kapat',async()=>{const note=prompt('Sonuç: supported veya unsupported','supported');if(note===null)return;await req('/v1/admin/tickets/'+id+'/close',{method:'POST',body:JSON.stringify({note})});await showTicket(p,id,me)});
 }
 b.append(controls);const back=document.createElement('button');back.textContent='← Talepler';back.onclick=async()=>showTickets(p,await req('/v1/admin/tickets'),me);b.append(back);
 }catch(e){b.textContent=e.message||'Destek talebi açılamadı.'}}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
window.ErisAdmin={clear:function(){document.querySelectorAll('.eris-admin-btn,.eris-admin-panel').forEach(el=>el.remove())}};
async function boot(){try{window.ErisAdmin.clear();const me=await req('/v1/admin/me');addStyles();const btn=document.createElement('button');btn.className='eris-admin-btn';btn.textContent='🛡️ Yönetim';btn.onclick=()=>openPanel(me);document.body.appendChild(btn)}catch(_){}}
window.addEventListener('load',()=>setTimeout(boot,600));
})();
