(() => {
  'use strict';
  const platform=()=>window.ErisPlatform;
  const api=(path,method='GET',body)=>platform().api('/anonymous-calls'+path,{method,...(body?{body:JSON.stringify(body)}:{})});
  let ui=null,mode='voice',quota=null,call=null,phase='select',stream=null,pc=null,music=null,cursor=0,clock=0,countdown=0,generation=0,busy=false,polling=false,offered=false,ice=[],notice='',extensionKey=null,disconnect=null,lastStatus=0,connectionPromise=null,remoteStream=null,joinPromise=null,endingPromise=null,pollFailures=0;
  const dialogs=new Set(),instant=()=>Date.now()+clock;
  const time=seconds=>`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
  function install(){
    if(document.getElementById('anonymous-style'))return;
    const style=document.createElement('style');style.id='anonymous-style';style.textContent=`
    .eris-anonymous{position:fixed;inset:0;z-index:23000;display:flex;flex-direction:column;align-items:center;gap:14px;padding:calc(20px + env(safe-area-inset-top)) 18px calc(20px + env(safe-area-inset-bottom));background:radial-gradient(circle at 50% 20%,#38214d,#090611 70%);color:#fff}.eris-anonymous [hidden]{display:none!important}.eris-anonymous button{color:#fff;background:#ffffff12;border:1px solid #ffffff28;border-radius:14px;padding:12px}.eris-anonymous button:disabled{opacity:.5}.anon-head{display:flex;align-items:center;justify-content:space-between;width:100%;gap:10px}.anon-count{border-radius:99px;background:#16754e;padding:8px 12px;font-size:12px}.anon-title{font-size:22px;text-align:center;margin:8px 0}.anon-time{font-size:38px;font-variant-numeric:tabular-nums}.anon-status,.anon-quota{color:#c5b2d5;text-align:center;font-size:13px}.anon-packages{display:flex;justify-content:center;align-items:center;gap:16px;flex:1;width:min(460px,100%)}.eris-anonymous .anon-package{position:relative;border:0;background:transparent;padding:0;max-width:48%}.anon-package img{display:block;width:100%;max-height:240px;object-fit:contain}.anon-package[data-locked=true] img{opacity:.5}.anon-lock{position:absolute;right:5%;top:5%;font-size:28px}.anon-stage{position:relative;width:100%;flex:1;min-height:0;overflow:hidden;border-radius:20px;background:#130d1e;display:grid;place-items:center}.anon-remote{width:100%;height:100%;object-fit:cover}.anon-self{position:absolute;right:12px;top:12px;width:95px;height:125px;object-fit:cover;border-radius:12px}.anon-voice{font-size:80px}.anon-actions{display:flex;gap:12px;align-items:center;justify-content:center;width:100%;margin-top:auto}.eris-anonymous .anon-hangup{background:#be304c;flex:1;max-width:260px}.anon-bubble{display:none}.eris-anonymous.mini{inset:auto 12px 100px auto;width:110px;height:120px;padding:8px;gap:0;border-radius:20px;border:1px solid #ad80d9;box-shadow:0 10px 30px #0008}.eris-anonymous.mini>*{display:none!important}.eris-anonymous.mini .anon-bubble{display:block!important;width:100%;height:100%;font-size:24px}.anon-dialog{position:fixed;inset:0;z-index:24000;background:#030109c9;display:grid;place-items:center;padding:20px}.anon-dialog section{position:relative;width:min(380px,100%);border:1px solid #a77aff66;border-radius:24px;padding:52px 22px 22px;background:#21152e;color:#fff;line-height:1.6;white-space:pre-line}.anon-dialog header{position:absolute;top:10px;left:12px;right:12px;display:flex;justify-content:space-between}.anon-dialog button{border:1px solid #ffffff25;border-radius:12px;padding:10px 16px;background:#ffffff15;color:#fff}.anon-dialog nav{display:flex;gap:12px;margin-top:20px}.anon-dialog nav button{flex:1}.anon-dialog [data-yes]{background:#188054}.anon-dialog [data-no]{background:#ab304a}
    `;document.head.append(style);
  }
  function dialog(text,{info=null,confirm=true,accept='Kabul Et'}={}){
    return new Promise(resolve=>{install();const root=document.createElement('div');root.className='anon-dialog';root.innerHTML='<section role="dialog" aria-modal="true"><header><button type="button" data-info aria-label="Bilgi">?</button><button type="button" data-close aria-label="Kapat">✕</button></header><div data-text></div><nav><button type="button" data-yes></button><button type="button" data-no>Reddet</button></nav></section>';
      root.querySelector('[data-text]').textContent=text;root.querySelector('[data-yes]').textContent=accept;root.querySelector('[data-no]').hidden=!confirm;root.querySelector('[data-info]').hidden=!info;
      let done=false;const finish=value=>{if(done)return;done=true;root.remove();dialogs.delete(finish);resolve(value);};dialogs.add(finish);
      root.querySelector('[data-yes]').onclick=()=>finish(true);root.querySelector('[data-no]').onclick=()=>finish(false);root.querySelector('[data-close]').onclick=()=>finish(false);root.querySelector('[data-info]').onclick=()=>dialog(info,{confirm:false,accept:'Satın alma penceresine dön'});root.onkeydown=e=>{if(e.key==='Escape')finish(false);};document.body.append(root);root.querySelector('[data-yes]').focus();
    });
  }
  function build(){
    install();ui=document.createElement('section');ui.className='eris-anonymous';ui.setAttribute('role','dialog');ui.setAttribute('aria-label','Anonim arama');ui.innerHTML='<header class="anon-head"><button type="button" data-peer hidden>👤 Profil</button><span class="anon-count" aria-label="Aktif kullanıcı sayısı">0 çevrim içi</span><button type="button" data-request hidden aria-label="Profil isteği gönder">👤＋</button><button type="button" data-close aria-label="Kapat">✕</button></header><h2 class="anon-title"></h2><div class="anon-status" role="status"></div><div class="anon-time"></div><div class="anon-quota"></div><div class="anon-packages"><button type="button" class="anon-package" data-standard><img alt="Standart arama"><span>Standart Arama</span></button><button type="button" class="anon-package" data-premium><img alt="Premium arama"><span>Premium Arama</span><span class="anon-lock">🔒</span></button></div><div class="anon-stage" hidden><video class="anon-remote" autoplay playsinline></video><video class="anon-self" autoplay playsinline muted></video><div class="anon-voice">☎</div></div><audio class="anon-audio" autoplay></audio><button type="button" data-music hidden>Bekleme müziğini aç</button><div class="anon-actions"><button type="button" data-extend hidden aria-label="Ek süre satın al">⌛</button><button type="button" data-mic hidden aria-label="Mikrofonu kapat">🎙</button><button type="button" data-camera hidden aria-label="Kamerayı kapat">📷</button><button type="button" class="anon-hangup" data-end hidden>Telefonu Kapat</button></div><button type="button" class="anon-bubble" aria-label="Aramaya dön">☎<small data-mini-time></small></button>';document.body.append(ui);ui.addEventListener('pointerup',()=>{const media=ui?.querySelector(mode==='video'?'.anon-remote':'.anon-audio');if(media?.srcObject)media.play().catch(()=>{})});
    ui.querySelector('[data-standard]').onclick=start;ui.querySelector('[data-premium]').onclick=()=>quota?.premium?start():purchase();ui.querySelector('[data-close]').onclick=end;ui.querySelector('[data-end]').onclick=end;ui.querySelector('[data-extend]').onclick=extend;ui.querySelector('[data-request]').onclick=profileRequest;
    ui.querySelector('[data-peer]').onclick=()=>{if(call?.peer){ui.classList.add('mini');window.openUserProfile?.(call.peer.user_id);}};ui.querySelector('.anon-bubble').onclick=()=>ui?.classList.remove('mini');
    for(const [selector,kind,on,off] of [['[data-mic]','audio','🎙','🎙̸'],['[data-camera]','video','📷','📷̸']])ui.querySelector(selector).onclick=()=>{const track=stream?.getTracks().find(t=>t.kind===kind);if(track){track.enabled=!track.enabled;ui.querySelector(selector).textContent=track.enabled?on:off;}};
    ui.querySelector('[data-music]').onclick=()=>music?.play().then(()=>{if(ui)ui.querySelector('[data-music]').hidden=true;}).catch(()=>window.toast?.('Bekleme müziği açılamadı.'));
  }
  function render(){
    if(!ui)return;const selecting=phase==='select',live=call?.status==='active';ui.querySelector('.anon-title').textContent=mode==='video'?'Anonim Görüntülü Arama':'Anonim Sesli Arama';ui.querySelector('.anon-status').textContent=selecting?'Arama paketini seç':phase==='countdown'?'Lütfen bekleyin, aramaya bağlanacaksınız':call?.status==='preparing'?'Aramaya katılıyorsunuz, hazırlanın':live?(pc?.connectionState==='connected'?'Görüşme sürüyor':'Canlı bağlantı kuruluyor…'):'Bağlanıyorsunuz...';ui.querySelector('.anon-quota').textContent=quota?`Bugün ${quota.remaining}/${quota.daily_limit} arama hakkı${quota.premium?' • Premium':''}`:'';
    ui.querySelector('.anon-packages').hidden=!selecting;ui.querySelector('[data-standard]').hidden=!!quota?.premium;ui.querySelector('[data-standard]').disabled=busy||!quota||quota.remaining<=0;ui.querySelector('[data-premium]').disabled=busy||!quota||(quota.premium&&quota.remaining<=0);ui.querySelector('[data-premium]').dataset.locked=String(!quota?.premium);ui.querySelector('.anon-lock').hidden=!!quota?.premium;
    for(const [selector,kind] of [['[data-standard]','standard'],['[data-premium]','premium']])ui.querySelector(selector+' img').src=`./anonymous-assets/${kind}-${mode}.png`;
    ui.querySelector('[data-end]').hidden=selecting;ui.querySelector('[data-extend]').hidden=!live;ui.querySelector('[data-mic]').hidden=!live;ui.querySelector('[data-camera]').hidden=!live||mode!=='video';ui.querySelector('[data-request]').hidden=!live||call?.profile_status==='accepted';ui.querySelector('[data-request]').disabled=call?.profile_status==='pending'||busy;ui.querySelector('[data-peer]').hidden=!call?.peer;ui.querySelector('.anon-stage').hidden=!live;ui.querySelector('.anon-remote').hidden=mode!=='video';ui.querySelector('.anon-self').hidden=mode!=='video';ui.querySelector('.anon-voice').hidden=mode==='video';
    const seconds=phase==='countdown'?Math.max(0,Math.ceil((countdown-Date.now())/1000)):call?.status==='preparing'?Math.max(0,Math.ceil((Date.parse(call.starts_at)-instant())/1000)):call?Math.max(0,Math.ceil((Date.parse(call.ends_at)-instant())/1000)):quota?.initial_seconds||60;ui.querySelector('.anon-time').textContent=selecting?'':time(seconds);ui.querySelector('[data-mini-time]').textContent=time(seconds);
  }
  async function purchase(){
    if(busy||!ui)return;const stamp=generation;const agreed=await dialog('Premium giriş özelliğini satın almak istiyor musunuz? 500 Lidya',{info:'Premium özellik neleri aktif eder?\n\nGünlük arama hakkınız 10’dan 20’ye çıkar.\nBaşlangıç süreniz 60 saniyeden 120 saniyeye çıkar.\n100 Lidya karşılığındaki süre uzatmanız 120 yerine 240 saniye olur.\n\nPremium özelliğiniz İstanbul saatine göre gece 24.00’a kadar geçerlidir.'});if(!agreed||stamp!==generation)return;busy=true;render();try{quota=await api('/premium','POST');}catch(e){window.toast?.(e.message);}finally{busy=false;render();}
  }
  function stopMusic(){music?.pause();if(ui)ui.querySelector('[data-music]').hidden=true;}
  function waitingMusic(){if(!music||phase!=='queued')return;music.loop=true;music.muted=false;music.play().catch(()=>{if(ui&&phase==='queued')ui.querySelector('[data-music]').hidden=false;});}
  async function start(){
    if(busy||!ui||quota?.remaining<=0)return;if(window.ErisLocationCalls?.isActive?.())return window.toast?.('Önce konuma göre eşleşmenizi sonlandırın.');if(window.ErisCalls?.isActive?.())return window.toast?.('Önce devam eden aramanızı kapatın.');if(!window.RTCPeerConnection||!navigator.mediaDevices?.getUserMedia)return window.toast?.('Bu tarayıcı sesli ve görüntülü aramayı desteklemiyor.');
    const stamp=generation;busy=true;render();music=new Audio('./anonymous-assets/waiting.mp3');music.volume=0.6;music.muted=true;const primed=music;primed.play().then(()=>{if(primed!==music){primed.pause();return;}if(phase!=='queued'){primed.pause();primed.currentTime=0;}primed.muted=false;}).catch(()=>{});
    try{window.ErisRoomRTC?.stop?.();const media=await navigator.mediaDevices.getUserMedia({audio:true,video:mode==='video'?{facingMode:'user'}:false});if(stamp!==generation){media.getTracks().forEach(track=>track.stop());return;}stream=media;ui.querySelector('.anon-self').srcObject=stream;phase='countdown';countdown=Date.now()+3000;render();}catch(e){if(stamp===generation){window.toast?.('Mikrofon/kamera izni verilmedi veya cihaz açılamadı.');phase='select';stopMusic();}}finally{if(stamp===generation){busy=false;render();}}
  }
  function join(){if(joinPromise)return joinPromise;joinPromise=joinRequest().finally(()=>{joinPromise=null});return joinPromise;}
  async function joinRequest(){
    if(busy||phase!=='countdown')return;const stamp=generation;busy=true;
    try{const data=await api('/queue','POST',{mode});if(stamp!==generation)return;quota=data.quota||quota;phase='queued';ui.querySelector('.anon-count').textContent=`${data.active_users||0} çevrim içi`;if(data.call)await adopt(data.call);else waitingMusic();}catch(e){if(stamp===generation){window.toast?.(e.message);cleanup();}}finally{if(stamp===generation){busy=false;render();}}
  }
  async function send(kind,payload,stamp=generation){if(stamp===generation&&call)await api('/'+call.id+'/signals','POST',{kind,payload});}
  async function connection(){if(pc)return pc;if(connectionPromise)return connectionPromise;const promise=createConnection();connectionPromise=promise;try{return await promise;}finally{if(connectionPromise===promise)connectionPromise=null;}}
  async function createConnection(){
    if(pc)return pc;const stamp=generation;const config=await platform().api('/calls/rtc-config');if(stamp!==generation||!stream)throw Error('Arama kapatıldı.');const peer=new RTCPeerConnection({iceServers:config.ice_servers});pc=peer;stream.getTracks().forEach(track=>peer.addTrack(track,stream));
    peer.onicecandidate=e=>{if(e.candidate)send('ice',e.candidate.toJSON(),stamp).catch(()=>{});};
    peer.ontrack=e=>{if(stamp!==generation||!ui)return;const element=ui.querySelector(mode==='video'?'.anon-remote':'.anon-audio');if(!remoteStream)remoteStream=new MediaStream();for(const track of (e.streams[0]?.getTracks()||[e.track])){if(!remoteStream.getTracks().some(t=>t.id===track.id))remoteStream.addTrack(track)}element.srcObject=remoteStream;element.play().catch(()=>window.toast?.('Sesi açmak için arama ekranına dokunun.'));};
    disconnect=setTimeout(()=>{if(stamp===generation&&peer.connectionState!=='connected'){window.toast?.('Arama bağlantısı kurulamadı. İnternet bağlantınızı kontrol edin.');end();}},20000);
    peer.onconnectionstatechange=()=>{if(stamp!==generation)return;if(peer.connectionState==='connected')clearTimeout(disconnect);else if(['failed','disconnected'].includes(peer.connectionState)){clearTimeout(disconnect);disconnect=setTimeout(()=>{if(pc===peer&&peer.connectionState!=='connected'){window.toast?.('Arama bağlantısı kesildi.');end();}},10000);}render();};return peer;
  }
  async function receive(event){
    const stamp=generation;const peer=await connection();if(stamp!==generation)return;
    if(event.kind==='ice'){if(peer.remoteDescription)await peer.addIceCandidate(event.payload).catch(()=>{});else if(ice.length<128)ice.push(event.payload);return;}
    if(event.kind==='offer'){await peer.setRemoteDescription(event.payload);for(const candidate of ice.splice(0))await peer.addIceCandidate(candidate).catch(()=>{});const answer=await peer.createAnswer();await peer.setLocalDescription(answer);await send('answer',peer.localDescription.toJSON(),stamp);}
    else if(event.kind==='answer'&&peer.signalingState==='have-local-offer'){await peer.setRemoteDescription(event.payload);for(const candidate of ice.splice(0))await peer.addIceCandidate(candidate).catch(()=>{});}
  }
  async function offer(){
    if(offered||!call?.initiator||call.status!=='active')return;const stamp=generation;offered=true;
    try{const peer=await connection();const value=await peer.createOffer();await peer.setLocalDescription(value);await send('offer',peer.localDescription.toJSON(),stamp);}catch(e){if(stamp===generation){window.toast?.(e.message||'Canlı bağlantı kurulamadı.');await end();}}
  }
  async function adopt(value){
    if(!ui)return;call=value;mode=value.mode;phase='call';clock=value.server_now?Date.parse(value.server_now)-Date.now():0;stopMusic();render();
    if(value.status==='ended'){window.toast?.(value.reason==='time'?'Arama süresi doldu.':'Arama sona erdi.');cleanup();return;}
    if(!stream){window.toast?.('Arama başka bir ekranınızda açık.');cleanup();return;}if(value.status==='active')await offer();
    if(value.profile_incoming&&notice!=='pending'){notice='pending';const stamp=generation;dialog('Karşı taraf profilinize erişmek istedi, onaylıyor musunuz?').then(async accepted=>{if(stamp!==generation||!call)return;try{await api('/'+call.id+'/profile-response','POST',{action:accepted?'accept':'reject'});}catch(e){window.toast?.(e.message);}});}
    else if(value.profile_status==='rejected'&&value.profile_outgoing&&notice!=='rejected'){notice='rejected';dialog('Karşı taraf profil isteğinizi reddetti',{confirm:false,accept:'Tamam'});}else if(value.profile_status!=='pending')notice=value.profile_status;
  }
  async function poll(){
    if(!ui||polling||busy||phase==='countdown')return;if(phase==='select'&&Date.now()-lastStatus<5000)return;polling=true;const stamp=generation;
    try{if(phase==='select'){lastStatus=Date.now();const data=await api('/status?mode='+mode);if(stamp!==generation)return;quota=data.quota;ui.querySelector('.anon-count').textContent=`${data.active_users} çevrim içi`;if(data.call||data.queued){window.toast?.('Anonim arama başka bir ekranınızda açık.');cleanup();}}
      else if(call){const data=await api('/'+call.id+'/events?after='+cursor);if(stamp!==generation)return;ui.querySelector('.anon-count').textContent=`${data.active_users} çevrim içi`;await adopt(data.call);if(stamp!==generation||!call)return;for(const event of data.events){await receive(event);if(event.id)cursor=event.id;}cursor=data.cursor;}
      else{const data=await api('/heartbeat','POST');if(stamp!==generation)return;quota=data.quota;ui.querySelector('.anon-count').textContent=`${data.active_users} çevrim içi`;if(data.call)await adopt(data.call);else if(!data.queued){window.toast?.('Arama kuyruğu bağlantınız sona erdi.');cleanup();}}
      pollFailures=0;
    }catch(e){if(stamp===generation&&++pollFailures>=3){window.toast?.(e.message||'Arama bağlantısı kurulamadı.');await end();}}finally{polling=false;render();}
  }
  async function extend(){
    if(busy||!call)return;const stamp=generation;const agreed=await dialog('100 Lidya karşılığında ek süre almak istiyor musunuz?');if(!agreed||stamp!==generation||!call)return;busy=true;extensionKey=extensionKey||crypto.randomUUID();render();
    try{const data=await api('/'+call.id+'/extend','POST',{request_key:extensionKey});if(stamp!==generation)return;extensionKey=null;await adopt(data.call);window.toast?.(`${data.seconds} saniye ortak süreye eklendi.`);}catch(e){window.toast?.(e.message);}finally{busy=false;render();}
  }
  async function profileRequest(){if(busy||!call)return;busy=true;try{await api('/'+call.id+'/profile-request','POST');notice='';window.toast?.('Profil isteği gönderildi.');}catch(e){window.toast?.(e.message);}finally{busy=false;render();}}
  function cleanup(){generation++;for(const close of [...dialogs])close(false);clearTimeout(disconnect);pc?.close();pc=null;connectionPromise=null;remoteStream=null;pollFailures=0;stream?.getTracks().forEach(track=>track.stop());stream=null;stopMusic();music=null;ui?.remove();ui=null;call=null;cursor=0;ice=[];offered=false;notice='';extensionKey=null;busy=false;phase='select';}
  async function end(){if(endingPromise)return endingPromise;const existed=phase==='queued'||!!call||!!joinPromise;const pending=joinPromise;cleanup();endingPromise=(async()=>{await pending?.catch(()=>{});if(existed)await api('/cancel','POST').catch(()=>{});})();try{await endingPromise;}finally{endingPromise=null;}}
  async function open(kind){
    if(endingPromise)await endingPromise;
    if(ui)return ui.classList.remove('mini');if(!platform()?.getAccessToken?.())return window.toast?.('Önce giriş yap.');mode=kind==='video'?'video':'voice';build();phase='select';busy=true;render();const stamp=generation;
    try{const data=await api('/status?mode='+mode);if(stamp!==generation)return;quota=data.quota;if(data.call||data.queued){window.toast?.('Anonim arama başka bir ekranınızda açık.');cleanup();return;}ui.querySelector('.anon-count').textContent=`${data.active_users||0} çevrim içi`;}catch(e){if(stamp===generation){window.toast?.(e.message);cleanup();}}finally{if(stamp===generation){busy=false;render();}}
  }
  function exit(){if(!ui)return;cleanup();const base=(window.ERIS_API||'https://erischat-api-production.up.railway.app/v1').replace(/\/$/,'');fetch(base+'/anonymous-calls/cancel',{method:'POST',headers:{Authorization:'Bearer '+platform()?.getAccessToken?.()},keepalive:true}).catch(()=>{});}
  window.ErisAnonymousCalls={open,end,isActive:()=>phase!=='select'&&!!ui};
  setInterval(()=>{if(!ui)return;render();if(phase==='countdown'&&Date.now()>=countdown)join();else poll();},1000);
  window.addEventListener('pagehide',exit);window.addEventListener('erischat:auth',event=>{if(event.detail?.state==='logged_out')cleanup();});
})();
