(() => {
 'use strict';
 const api=(p,o)=>window.ErisPlatform.api(p,o),labels={days:'Günlük ziyaret',room_messages:'Oda sohbeti',messages:'Mesajlaşma',rooms:'Oda keşfi',follows:'Dost çemberi',room_follows:'Oda takibi',posts:'Paylaşımlar',stories:'Hikâyeler'},requests=new WeakMap();
 const style=document.createElement('style');style.textContent=`
.appearance-tasks{max-width:720px;margin:auto;min-width:0}.appearance-tasks-heading small{font-size:10px;letter-spacing:1.7px;color:#bf9ed6;font-weight:700}.appearance-tasks-heading h3{font-size:24px!important;margin:7px 0!important}.appearance-tasks-heading p{color:#a899b7;font-size:12px;line-height:1.7;margin:0 0 18px}.appearance-task-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-bottom:20px}.appearance-task-summary>div{border:1px solid #ffffff16;border-radius:15px;padding:13px 10px;background:#a66bd409;text-align:center}.appearance-task-summary b{display:block;font-size:21px;color:#dfc6f0}.appearance-task-summary span{display:block;font-size:10px;color:#aa98b8;margin-top:4px}
.eph-overlay .appearance-tasks .task-filters,.appearance-tasks .task-filters{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:20px}.eph-overlay .appearance-tasks .task-filters button,.appearance-tasks .task-filters button{width:auto!important;min-height:42px!important;height:auto!important;font-size:11px!important;padding:10px 12px!important;border:1px solid #ffffff1b!important;border-radius:13px!important;background:#ffffff04!important;color:#ad9dbb!important;white-space:normal!important;box-shadow:none!important}.eph-overlay .appearance-tasks .task-filters button[aria-pressed=true],.appearance-tasks .task-filters button[aria-pressed=true]{color:#f0e5fa!important;border-color:#b88bdd80!important;background:#ad6ed523!important}
.appearance-task-grid{display:grid;gap:13px}.eph-overlay .appearance-tasks .appearance-task,.appearance-tasks .appearance-task{border:1px solid #ffffff17!important;border-radius:20px!important;padding:16px!important;background:#15101e!important;margin:0!important;min-width:0}.appearance-tasks .appearance-task[data-ready=true]{border-color:#b08bd86b!important;background:linear-gradient(125deg,#2c1b37,#15101e)!important}.appearance-task-reward{display:grid;place-items:center;min-height:70px;padding:10px;border-radius:13px;background:#0b0812;margin-bottom:13px}.appearance-task-reward img{width:100%!important;height:55px!important;object-fit:contain!important;max-width:320px}.appearance-task-title{display:flex;gap:8px;align-items:center;justify-content:space-between;flex-wrap:wrap}.appearance-task-title b{font-size:14px;overflow-wrap:anywhere}.appearance-task-tag{font-size:10px;color:#c09eda;background:#a877cd17;border-radius:8px;padding:5px 8px}.appearance-task p{color:#b3a1c2;font-size:12px;line-height:1.6;margin:12px 0}.appearance-task-count{display:flex;justify-content:space-between;gap:10px;color:#a38eaf;font-size:11px;margin-top:12px}.appearance-tasks progress{display:block;width:100%;height:8px;margin:9px 0 14px;accent-color:#b884dd;border:0;border-radius:20px;overflow:hidden}.eph-overlay .appearance-tasks .appearance-task button,.appearance-tasks .appearance-task button{width:100%!important;min-height:44px!important;height:auto!important;padding:11px!important;border:1px solid #ad82d13d!important;border-radius:13px!important;font-size:12px!important;line-height:1.5!important;background:#a872d219!important;color:#d8bde9!important;box-shadow:none!important}.appearance-task[data-ready=true] button{background:linear-gradient(125deg,#8653c3,#bb498f)!important;color:#fff!important;border:0!important;font-weight:700}.appearance-task button:disabled{opacity:.5}.appearance-task[data-claimed=true] button{opacity:1;color:#aa97ba!important;background:#ffffff04!important}.appearance-task-feedback{font-size:11px;line-height:1.6;color:#d7b6e9;margin-top:8px;overflow-wrap:anywhere}.appearance-task-empty{border:1px dashed #ab85ce37;border-radius:19px;padding:32px 18px;text-align:center;color:#b09cbf;font-size:13px;line-height:1.7}.appearance-task-empty b{display:block;color:#dfcce9;font-size:16px;margin-bottom:7px}.appearance-tasks button:focus-visible{outline:2px solid #c497ea;outline-offset:3px}
`;document.head.append(style);
 async function render(root,current=()=>true){
  const generation=(requests.get(root)||0)+1;requests.set(root,generation);const valid=()=>current()&&root.isConnected&&requests.get(root)===generation;
  root.innerHTML='<section class="appearance-tasks"><div class="appearance-task-empty" role="status">Görevler yükleniyor…</div></section>';const section=root.firstElementChild;section.setAttribute('aria-busy','true');let data;
  try{data=await api('/me/appearance-tasks')}catch(e){if(valid()){section.setAttribute('aria-busy','false');section.replaceChildren();const state=document.createElement('div');state.className='appearance-task-empty';state.setAttribute('role','status');const message=document.createElement('p');message.textContent=e.message||'Görevler yüklenemedi.';const retry=document.createElement('button');retry.type='button';retry.textContent='Tekrar dene';retry.onclick=()=>render(root,current);state.append(message,retry);section.append(state)}return}if(!valid())return;
  const items=Array.isArray(data.items)?data.items:[];
  section.setAttribute('aria-busy','false');section.innerHTML='<header class="appearance-tasks-heading"><small>ADIM ADIM ÖDÜLLERE</small><h3>Görevler ve ünvanlar</h3><p>Kalıcı ünvanlarını kazan. Aldığın ödülleri Koleksiyon → Ünvan bölümünden kullanabilirsin. Günlük ziyaret Türkiye saatine göre sayılır.</p></header><div class="appearance-task-summary"></div><div class="task-filters" role="group" aria-label="Görev kategorileri"></div><div class="appearance-task-grid" data-tasks></div>';
  const summary=section.querySelector('.appearance-task-summary'),filters=section.querySelector('.task-filters'),grid=section.querySelector('[data-tasks]');let filter='all';
  function counts(){summary.replaceChildren();for(const [name,value] of [['Görev',items.length],['Hazır ödül',items.filter(q=>q.complete&&!q.claimed).length],['Alınan',items.filter(q=>q.claimed).length]]){const box=document.createElement('div'),amount=document.createElement('b'),label=document.createElement('span');amount.textContent=value;label.textContent=name;box.append(amount,label);summary.append(box)}}
  function draw(){counts();grid.replaceChildren();filters.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filter)));const rows=items.filter(q=>filter==='all'||(filter==='ready'?q.complete&&!q.claimed:filter==='claimed'?q.claimed:q.metric===filter));
   for(const q of rows){const card=document.createElement('article');card.className='appearance-task';card.dataset.ready=String(q.complete&&!q.claimed);card.dataset.claimed=String(!!q.claimed);const visual=document.createElement('div');visual.className='appearance-task-reward';const img=document.createElement('img');img.src=window.ErisChatCosmetics.assetUrl(q.reward.asset_key);img.alt=q.reward.name;img.loading='lazy';img.onerror=()=>{img.remove();visual.textContent=q.reward.name;visual.style.fontSize='12px'};visual.append(img);const title=document.createElement('div');title.className='appearance-task-title';const name=document.createElement('b');name.textContent=q.reward.name;const tag=document.createElement('span');tag.className='appearance-task-tag';tag.textContent=labels[q.metric]||'Görev';title.append(name,tag);const desc=document.createElement('p');desc.textContent=q.description;const count=document.createElement('div');count.className='appearance-task-count';const progress=Math.max(0,Number(q.progress)||0),target=Math.max(1,Number(q.target)||1);count.innerHTML='<span></span><span></span>';count.children[0].textContent=progress.toLocaleString('tr-TR')+' / '+target.toLocaleString('tr-TR');count.children[1].textContent=Math.min(100,Math.floor(progress/target*100))+'%';const bar=document.createElement('progress');bar.value=Math.min(progress,target);bar.max=target;bar.setAttribute('aria-label',q.description);const button=document.createElement('button');button.type='button';button.textContent=q.claimed?'✓ Koleksiyonunda':q.complete?'Ünvanı al':'Görev sürüyor';button.disabled=q.claimed||!q.complete;const feedback=document.createElement('div');feedback.className='appearance-task-feedback';feedback.setAttribute('role','status');
    button.onclick=async()=>{button.disabled=true;button.textContent='Ödül alınıyor…';feedback.textContent='';try{await api('/me/appearance-tasks/'+encodeURIComponent(q.id)+'/claim',{method:'POST'});q.claimed=true;try{await window.ErisChatCosmetics?.load?.()}catch{}window.dispatchEvent(new Event('erischat:cosmetics-updated'));if(valid()){draw();window.toast?.('Ünvan koleksiyonuna eklendi.')}}catch(e){if(valid()){button.disabled=false;button.textContent='Ünvanı al';feedback.textContent=e.message||'Ödül alınamadı. Tekrar dene.'}}};card.append(visual,title,desc,count,bar,button,feedback);grid.append(card)}
   if(!rows.length){const empty=document.createElement('div');empty.className='appearance-task-empty';empty.innerHTML='<b>Şimdilik görev yok</b>';empty.append(filter==='ready'?'Alınmayı bekleyen ödülün yok. Görevleri tamamlayarak ünvan kazanabilirsin.':filter==='claimed'?'Aldığın ödüller burada görünecek.':'Bu kategoride görev bulunmuyor.');grid.append(empty)}
  }
  for(const [key,name] of Object.entries({all:'Tümü',ready:'Hazır ödüller',claimed:'Alınanlar',...labels})){const button=document.createElement('button');button.type='button';button.dataset.filter=key;button.textContent=name;button.onclick=()=>{filter=key;draw()};filters.append(button)}draw();
 }
 window.ErisAppearanceTasks={render};
})();
