(() => {
 'use strict';const api=(p,o)=>window.ErisPlatform.api(p,o),labels={days:'Günlük ziyaret',room_messages:'Oda sohbeti',messages:'Mesajlaşma',rooms:'Oda keşfi',follows:'Dost çemberi',room_follows:'Oda takibi',posts:'Paylaşımlar',stories:'Hikâyeler'};
 async function render(root,current=()=>true){
  root.textContent='Görevler yükleniyor…';let data;try{data=await api('/me/appearance-tasks')}catch(e){if(current())root.textContent=e.message||'Görevler yüklenemedi.';return}if(!current()||!root.isConnected)return;
  root.innerHTML='<style>.appearance-task{border:1px solid #ffffff24;border-radius:16px;padding:14px;margin:10px 0;background:#141120}.appearance-task img{display:block;width:min(230px,100%);height:52px;object-fit:contain}.appearance-task p{font-size:12px;line-height:1.5;color:#c1b4d0}.appearance-task progress{display:block;width:100%;height:9px;margin:12px 0;accent-color:#b294ee}.task-filters{display:flex;gap:6px;flex-wrap:wrap}.task-filters button[aria-pressed=true]{border-color:#b79cf3}.appearance-task button{width:100%}</style><h3>Görevler ve ünvanlar</h3><p class="eph-muted">80 kalıcı ünvan. Ödülünü aldıktan sonra Koleksiyon → Ünvan bölümünden kullan. Günlük ziyaret Türkiye saatine göre sayılır.</p><div class="task-filters"></div><div data-tasks></div>';
  let filter='all';const filters=root.querySelector('.task-filters'),grid=root.querySelector('[data-tasks]');function draw(){grid.replaceChildren();filters.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filter)));const rows=data.items.filter(q=>filter==='all'||(filter==='ready'?q.complete&&!q.claimed:q.metric===filter));
   for(const q of rows){const card=document.createElement('article');card.className='appearance-task';const img=document.createElement('img');img.src=window.ErisChatCosmetics.assetUrl(q.reward.asset_key);img.alt=q.reward.name;img.loading='lazy';const name=document.createElement('b');name.textContent=q.reward.name;const desc=document.createElement('p');desc.textContent=q.description+' · '+q.progress.toLocaleString('tr-TR')+' / '+q.target.toLocaleString('tr-TR');const bar=document.createElement('progress');bar.value=q.progress;bar.max=q.target;bar.setAttribute('aria-label',q.description);const b=document.createElement('button');b.type='button';b.textContent=q.claimed?'✓ Koleksiyonunda':q.complete?'Ünvanı al':'Görev sürüyor';b.disabled=q.claimed||!q.complete;b.onclick=async()=>{b.disabled=true;try{await api('/me/appearance-tasks/'+encodeURIComponent(q.id)+'/claim',{method:'POST'});q.claimed=true;b.textContent='✓ Koleksiyonunda';await window.ErisChatCosmetics.load();window.toast?.('Ünvan koleksiyonuna eklendi.')}catch(e){b.disabled=false;window.toast?.(e.message)}};card.append(img,name,desc,bar,b);grid.append(card)}if(!rows.length)grid.textContent='Bu bölümde alınmayı bekleyen ödül yok.';
  }for(const [key,name] of Object.entries({all:'Tümü',ready:'Hazır ödüller',...labels})){const b=document.createElement('button');b.type='button';b.dataset.filter=key;b.textContent=name;b.onclick=()=>{filter=key;draw()};filters.append(b)}draw();
 }
 window.ErisAppearanceTasks={render};
})();
