(() => {
  'use strict';
  const api=()=>window.ErisPlatform;
  let call=null,pc=null,local=null,screen=null,remote=null,timer=null,ui=null,cursor=0;
  let cameraOn=true,micOn=true,face='user',controlsVisible=true,mini=false,offering=false,ending=false,polling=false,pendingIce=[],disconnectTimer=null,remoteVideoOn=true,remoteScreenOn=false,audioOutput="speaker",ringTimer=null,ringContext=null;
  const showToast=text=>window.toast?.(text);
  const request=(path,method='GET',body)=>api().api('/calls'+path,{method, ...(body?{body:JSON.stringify(body)}:{})});
  try{navigator.mediaDevices?.setCaptureHandleConfig?.({handle:'erischat-current-tab',exposeOrigin:true,permittedOrigins:[location.origin]})}catch{}
  const humanTime=seconds=>`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
  function install(){
    if(document.getElementById('eris-call-style'))return;
    const style=document.createElement('style');style.id='eris-call-style';style.textContent=`
      #chat .chatHead .grow{min-width:0;overflow:hidden}#chat .chatHead .grow b{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}#chat .dm-call-head{display:flex;gap:5px;flex:none;margin-left:auto}#chat .dm-call-head[hidden]{display:none!important}#chat .dm-call-head button{width:35px;height:35px;flex:none;border:1px solid #ffffff25;border-radius:11px;background:#ffffff0b;color:white;font-size:18px}
      .eris-call{position:fixed;inset:0;z-index:21000;background:radial-gradient(circle at 50% 25%,#422553,#0c0914 58%);color:#fff;display:flex;flex-direction:column;align-items:center;padding:calc(24px + env(safe-area-inset-top)) 18px calc(24px + env(safe-area-inset-bottom));font-family:inherit}.eris-call [hidden],.eris-call[hidden]{display:none!important}
      .eris-call .call-status{font-size:13px;color:#c9bbd6}.eris-call .call-time{font-size:16px;margin:6px}.eris-call .call-peer{display:flex;flex-direction:column;align-items:center;gap:12px;margin:8vh 0 20px}.eris-call .call-portrait{width:120px;height:120px;position:relative;display:grid;place-items:center}.eris-call .call-portrait .call-avatar{width:84px;height:84px;border-radius:50%;object-fit:cover;background:#452960}.eris-call .call-portrait .call-frame{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;pointer-events:none}.eris-call .call-name{font-size:23px;font-weight:800}.eris-call button{border:1px solid #ffffff28;border-radius:16px;background:#ffffff15;color:white;padding:12px;font-weight:700}.eris-call .call-stage{position:relative;flex:1;align-self:stretch;min-height:0;overflow:hidden;border-radius:18px}.eris-call .call-remote{width:100%;height:100%;object-fit:cover;background:#11101a}.eris-call .call-self{position:absolute;right:12px;top:12px;width:105px;height:145px;object-fit:cover;border:2px solid #ad79ea;border-radius:15px;background:#211a30;touch-action:none;z-index:3}.eris-call .call-self[hidden],.eris-call .call-remote[hidden]{display:none!important}.eris-call .call-flip{position:absolute;right:15px;top:15px;z-index:4;padding:5px 8px}.eris-call .call-actions{display:flex;justify-content:center;gap:12px;align-items:center;width:100%;flex-wrap:wrap;margin-top:auto;padding-top:18px;z-index:2}.eris-call .call-actions button{width:52px;height:52px;border-radius:50%;font-size:21px;padding:0}.eris-call .call-actions button[aria-pressed=true]{border-color:#b58dff;background:#604090}.eris-call .call-actions .end,.eris-call .reject{background:#ba3651;border-color:#e75b72}.eris-call .accept{background:#198b5b;border-color:#48d997}.eris-call .call-incoming{display:grid;gap:12px;width:min(300px,100%);margin:auto 0}.eris-call .call-incoming .call-choice{display:flex;gap:12px}.eris-call .call-incoming .call-choice button{flex:1}.eris-call.mini{inset:12px 12px auto auto;width:96px;height:96px;min-height:0;padding:6px;border:1px solid #a882db;border-radius:50%;overflow:hidden;box-shadow:0 12px 32px #000a;touch-action:none;cursor:grab}.eris-call.mini>*{display:none!important}.eris-call.mini .call-bubble{display:grid!important;place-items:center;width:100%;height:100%;border-radius:50%;background:#3a2460;font-size:24px}.eris-call .call-bubble{display:none}
      .eris-call .call-phone{position:absolute;inset:0;display:grid;place-items:center;background:#171023;font-size:76px;z-index:1}.eris-call .call-phone[hidden]{display:none!important}
      .eris-call-consent{position:fixed;inset:0;z-index:22000;display:grid;place-items:center;padding:20px;background:#070411b8;backdrop-filter:blur(10px)}.eris-call-consent section{width:min(360px,100%);padding:24px;border:1px solid #ab80e855;border-radius:24px;background:linear-gradient(145deg,#30213cdd,#130c1fef);color:#fff;text-align:center}.eris-call-consent img{width:22px;height:22px;vertical-align:middle}.eris-call-consent nav{display:flex;gap:12px;margin-top:20px}.eris-call-consent button{flex:1;padding:12px;border-radius:13px;color:#fff;font-weight:800;border:0}.eris-call-consent .agree{background:#16875a}.eris-call-consent .decline{background:#ad304b}
    `;document.head.append(style);
  }
  function portrait(host){
    const wrap=host.querySelector('.call-portrait');wrap.replaceChildren();
    const avatar=document.createElement('img');avatar.className='call-avatar';avatar.alt='';
    const asset=call.avatar_asset&&window.ErisChatCosmetics?.assetUrl?.(call.avatar_asset);
    if(asset)avatar.src=asset;else avatar.alt='👤';wrap.append(avatar);
    const frame=call.frame_asset&&window.ErisChatCosmetics?.assetUrl?.(call.frame_asset);
    if(frame){const img=document.createElement('img');img.className='call-frame';img.alt='';img.src=frame;wrap.append(img)}
  }
  function build(){
    install();ui=document.createElement('section');ui.className='eris-call';ui.setAttribute('role','dialog');ui.setAttribute('aria-label','Arama');
    ui.innerHTML='<div class="call-time"></div><div class="call-status"></div><div class="call-peer"><div class="call-portrait"></div><div class="call-name"></div></div><div class="call-stage"><video class="call-remote" autoplay playsinline></video><div class="call-phone" hidden aria-label="Karşı tarafın kamerası kapalı">📱</div><video class="call-self" autoplay playsinline muted hidden></video><button type="button" class="call-flip" hidden aria-label="Kamerayı değiştir">↺</button></div><audio class="call-audio" autoplay></audio><div class="call-incoming" hidden><button type="button" data-incoming-camera>Kameramı kapat</button><button type="button" data-unavailable>Müsait değilim</button><div class="call-choice"><button type="button" class="accept" data-accept>☎ Kabul et</button><button type="button" class="reject" data-reject>☎ Reddet</button></div></div><div class="call-actions"><button type="button" data-mic aria-label="Mikrofonu kapat">🎙</button><button type="button" data-output aria-label="Hoparlör ve ahize arasında geçiş">🔊</button><button type="button" data-camera aria-label="Kamerayı aç">📷</button><button type="button" data-share aria-label="Ekranı paylaş">▣</button><button type="button" class="end" data-end aria-label="Aramayı bitir">☎</button><button type="button" data-message aria-label="Mesajlara dön">✉</button></div><div class="call-bubble">☎</div>';
    document.body.append(ui);ui.querySelector('[data-accept]').onclick=()=>accept();ui.querySelector('[data-reject]').onclick=()=>respond('reject');ui.querySelector('[data-unavailable]').onclick=()=>respond('unavailable');
    ui.querySelector('[data-incoming-camera]').onclick=()=>{cameraOn=!cameraOn;render()};
    ui.querySelector('[data-end]').onclick=()=>end();ui.querySelector('[data-mic]').onclick=toggleMic;ui.querySelector('[data-output]').onclick=toggleOutput;ui.querySelector('[data-camera]').onclick=toggleCamera;ui.querySelector('[data-share]').onclick=toggleShare;ui.querySelector('[data-message]').onclick=minimize;ui.querySelector('.call-flip').onclick=flipCamera;
    ui.querySelector('.call-bubble').onclick=()=>{if(!mini)return;mini=false;ui.classList.remove('mini');ui.style.left='';ui.style.top='';ui.style.right='';render();ui.querySelector(call.kind==='voice'?'.call-audio':'.call-remote')?.play?.().catch(()=>{})};
    ui.querySelector('.call-stage').onclick=e=>{if(call?.kind==='video'&&call?.status==='active'&&!e.target.closest('button')&&!e.target.classList.contains('call-self')){controlsVisible=!controlsVisible;render()}};
    drag(ui.querySelector('.call-self'),ui.querySelector('.call-stage'));drag(ui,document.body,true);
  }
  function drag(element,bounds,bubble=false){let sx=0,sy=0,moved=false;
    element.addEventListener('pointerdown',e=>{if(bubble&&!mini)return;if(e.target.closest('button'))return;sx=e.clientX;sy=e.clientY;moved=false;element.setPointerCapture(e.pointerId)});
    element.addEventListener('pointermove',e=>{if(!element.hasPointerCapture(e.pointerId))return;const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.abs(dx)+Math.abs(dy)<4)return;moved=true;sx=e.clientX;sy=e.clientY;const box=element.getBoundingClientRect(),limit=bounds.getBoundingClientRect();const x=Math.max(limit.left,Math.min(box.left+dx,limit.right-box.width)),y=Math.max(limit.top,Math.min(box.top+dy,limit.bottom-box.height));element.style.left=(bubble?x:x-limit.left)+'px';element.style.top=(bubble?y:y-limit.top)+'px';element.style.right='auto'});
    element.addEventListener('pointerup',e=>{if(element.hasPointerCapture(e.pointerId))element.releasePointerCapture(e.pointerId);if(moved){e.preventDefault();e.stopPropagation()}},true);
  }
  function render(){if(!call)return;if(!ui)build();ui.classList.toggle('mini',mini);ui.classList.toggle('video',call.kind==='video');
    ui.querySelector('.call-name').textContent=call.peer_name;portrait(ui);
    const active=call.status==='active',ring=call.status==='ringing';ui.querySelector('.call-status').textContent=ring?(call.incoming?'Gelen '+(call.kind==='video'?'görüntülü':'sesli')+' arama':'Aranıyor…'):active?'Görüşme sürüyor':call.status;
    ui.querySelector('.call-incoming').hidden=!(ring&&call.incoming);ui.querySelector('.call-actions').hidden=ring&&call.incoming;
    const incomingCamera=ui.querySelector('[data-incoming-camera]');incomingCamera.hidden=call.kind!=='video';incomingCamera.textContent=cameraOn?'Kameramı kapat':'Kameramı aç';
    ui.querySelector('[data-end]').hidden=ring&&call.incoming;
    const camera=ui.querySelector('[data-camera]');camera.hidden=ring&&call.kind==='voice';camera.textContent=cameraOn?'📷':'📷̸';camera.setAttribute('aria-pressed',String(cameraOn));
    ui.querySelector('.call-phone').hidden=!(active&&(call.kind==='video'||remoteScreenOn)&&!remoteVideoOn);ui.querySelector('[data-output]').hidden=!active||call.kind!=='voice';ui.querySelector('[data-output]').textContent=audioOutput==='speaker'?'🔊':'📱';ui.querySelector('[data-share]').hidden=!active;ui.querySelector('[data-share]').setAttribute('aria-pressed',String(!!screen));
    const mic=ui.querySelector('[data-mic]');mic.hidden=!active;mic.textContent=micOn?'🎙':'🎙̸';mic.setAttribute('aria-pressed',String(micOn));mic.setAttribute('aria-label',micOn?'Mikrofonu kapat':'Mikrofonu aç');
    ui.querySelector('[data-message]').hidden=!active;ui.querySelector('.call-flip').hidden=!local?.getVideoTracks().length||!!screen||!cameraOn;
    const video=active&&(call.kind==='video'||remoteScreenOn||!!screen);ui.querySelector('.call-peer').hidden=video;ui.querySelector('.call-stage').hidden=!video&&!local?.getVideoTracks().length;
    ui.querySelector('.call-self').hidden=!local?.getVideoTracks().length||!cameraOn;
    ui.querySelector('.call-actions').style.visibility=video&&!controlsVisible?'hidden':'';
    ui.querySelector('.call-status').style.visibility=video&&!controlsVisible?'hidden':'';
    if(video){ui.querySelector('.call-name').textContent=call.peer_name;ui.querySelector('.call-name').style.position='absolute';ui.querySelector('.call-name').style.top='16px';ui.querySelector('.call-name').style.left='16px';ui.querySelector('.call-name').style.zIndex='2';ui.querySelector('.call-peer').hidden=false;ui.querySelector('.call-portrait').hidden=true;ui.querySelector('.call-peer').style.margin='0';ui.querySelector('.call-peer').style.alignSelf='flex-start'}else{ui.querySelector('.call-portrait').hidden=false;ui.querySelector('.call-name').style.position='';ui.querySelector('.call-peer').style.margin='8vh 0 20px'}
    ui.querySelector('.call-time').textContent=active&&call.accepted_at?humanTime(Math.max(0,Math.floor((Date.now()-Date.parse(call.accepted_at))/1000))):'';
  }
  async function media(){if(local)return;local=await navigator.mediaDevices.getUserMedia({audio:true,video:call.kind==='video'&&cameraOn?{facingMode:face}:false});local.getAudioTracks().forEach(t=>t.enabled=micOn);ui.querySelector('.call-self').srcObject=local;render()}
  async function signal(kind,payload){if(call?.status==='active')await request('/'+call.id+'/signals','POST',{kind,payload})}
  async function connection(){if(pc)return pc;const cfg=await request('/rtc-config');pc=new RTCPeerConnection({iceServers:cfg.ice_servers});
    pc.onicecandidate=e=>{if(e.candidate)signal('ice',e.candidate.toJSON()).catch(()=>{})};
    pc.ontrack=e=>{if(!remote)remote=new MediaStream();if(!remote.getTracks().some(t=>t.id===e.track.id))remote.addTrack(e.track);const element=ui.querySelector('.call-remote');element.srcObject=remote;element.muted=call.kind==='voice';const audio=ui.querySelector('.call-audio');audio.srcObject=remote;audio.muted=call.kind==='video';if(call.kind==='video')element.play().catch(()=>{});else audio.play().catch(()=>showToast('Sesi duymak için arama ekranına dokunun.'))};
    pc.onconnectionstatechange=()=>{clearTimeout(disconnectTimer);if(['failed','disconnected'].includes(pc?.connectionState))disconnectTimer=setTimeout(()=>{if(pc?.connectionState!=='connected'){showToast('Arama bağlantısı kesildi.');end()}},10000)};
    if(!local)await media();for(const t of local.getTracks())pc.addTrack(t,local);
    if(!local.getVideoTracks().length)pc.addTransceiver('video',{direction:'sendrecv'});
    return pc;
  }
  async function offer(){if(offering||!call||call.status!=='active')return;offering=true;try{const peer=await connection();if(peer.signalingState!=='stable')return;const desc=await peer.createOffer();await peer.setLocalDescription(desc);await signal('offer',peer.localDescription.toJSON())}finally{offering=false}}
  async function receive(event){const peer=await connection();if(event.kind==='offer'){await peer.setRemoteDescription(new RTCSessionDescription(event.payload));for(const ice of pendingIce.splice(0))await peer.addIceCandidate(new RTCIceCandidate(ice)).catch(()=>{});const answer=await peer.createAnswer();await peer.setLocalDescription(answer);await signal('answer',peer.localDescription.toJSON())}else if(event.kind==='answer'){if(peer.signalingState==='have-local-offer'){await peer.setRemoteDescription(new RTCSessionDescription(event.payload));for(const ice of pendingIce.splice(0))await peer.addIceCandidate(new RTCIceCandidate(ice)).catch(()=>{})}}else if(event.kind==='ice'){if(peer.remoteDescription)await peer.addIceCandidate(new RTCIceCandidate(event.payload)).catch(()=>{});else if(pendingIce.length<64)pendingIce.push(event.payload)}else if(event.kind==='screen-stop'){remoteScreenOn=false;remoteVideoOn=!!event.payload?.camera;render();showToast('Karşı taraf ekran paylaşımını kapattı.')}else if(event.kind==='video-state'||event.kind==='screen-state'){if(event.kind==='screen-state'){remoteScreenOn=!!event.payload?.enabled;if(remoteScreenOn)ui?.querySelector('.call-remote')?.play?.().catch(()=>{})}remoteVideoOn=!!event.payload?.enabled;render()}}
  async function tick(){if(polling||ending||document.visibilityState!=='visible'||!api()?.getAccessToken?.())return;polling=true;try{
    if(!call){const found=await request('/active');if(found.id){call=found;cursor=0;cameraOn=call.kind==='video';remoteVideoOn=call.kind==='video';micOn=true;mini=false;render();startRing(call.incoming)}return}
    const data=await request('/'+call.id+'/events?after='+cursor);cursor=data.cursor||cursor;const was=call.status;call=data.call;
    if(call.status==='active'&&was==='ringing'&&!call.incoming){stopRing();await media();await offer()}
    if(call.status==='active'){stopRing();for(const event of data.events)await receive(event)}
    if(!['active','ringing'].includes(call.status)){if(call.status==='reject')showToast('Meşgul');if(call.status==='missed'||(call.status==='ended'&&was==='ringing'))showToast('Ulaşılamıyor. 40 Lidya iade edildi.');if(call.status==='unavailable')showToast('Şu anda müsait değil.');cleanup();window.ErisChatDM?.load?.();return}
    render();
  }catch(error){console.warn('[ErisChat] call poll',error)}finally{polling=false}}
  function cleanup(){stopRing();clearTimeout(disconnectTimer);disconnectTimer=null;if(pc){pc.close();pc=null}local?.getTracks().forEach(t=>t.stop());local=null;screen?.getTracks().forEach(t=>t.stop());screen=null;remote=null;cursor=0;pendingIce=[];call=null;mini=false;ui?.remove();ui=null;offering=false;ending=false}
  async function end(){if(!call||ending)return;ending=true;const id=call.id;try{await request('/'+id+'/end','POST')}catch{}finally{cleanup()}}
  async function respond(action){if(!call||ending)return;try{if(action==='accept')await media();call=await request('/'+call.id+'/respond','POST',{action});if(action==='accept'){stopRing();await connection();await signal('video-state',{enabled:cameraOn})}else{cleanup();window.ErisChatDM?.load?.()}}catch(e){showToast(e.message||'Çağrı yanıtlanamadı.');await end()}}
  async function accept(){await respond('accept')}
  async function start(kind){if(window.ErisLocationCalls?.isActive?.())return showToast('Önce konuma göre eşleşmenizi sonlandırın.');if(window.ErisAnonymousCalls?.isActive?.())return showToast("Önce anonim aramanızı kapatın.");const id=window.ErisChatDM?.activeId?.();if(!id)return showToast('Birebir konuşma açın.');if(call)return showToast('Zaten bir arama devam ediyor.');if(!window.RTCPeerConnection||!navigator.mediaDevices?.getUserMedia)return showToast('Bu tarayıcı aramaları desteklemiyor.');
    try{if(!await consent(kind))return;const conversation=await api().conversation(id);if(conversation.type!=='dm')return showToast('Arama yalnızca birebir sohbetlerde kullanılabilir.');const me=await api().getMe();const target=conversation.members?.find(member=>String(member.user_id)!==String(me.id))?.user_id;if(!target)return showToast('Aranacak kişi bulunamadı.');window.__erisActiveDmUserId=target;call=await request('','POST',{conversation_id:id,target_id:target,kind});cameraOn=kind==='video';remoteVideoOn=kind==='video';micOn=true;mini=false;render();startRing(false);await media();window.ErisRoomRTC?.stop?.()}catch(e){showToast(e.message||'Arama başlatılamadı.');if(call)await end()}}
  async function toggleMic(){micOn=!micOn;local?.getAudioTracks().forEach(t=>t.enabled=micOn);render();showToast(micOn?'Mikrofon açıldı.':'Mikrofon kapatıldı.')}
  async function toggleCamera(){cameraOn=!cameraOn;try{if(cameraOn){const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:face}});const track=s.getVideoTracks()[0];if(!local)local=new MediaStream();const old=local.getVideoTracks()[0];if(old){local.removeTrack(old);old.stop()}local.addTrack(track);const sender=pc?.getSenders().find(x=>x.track?.kind==='video')||pc?.getTransceivers().find(x=>x.receiver.track.kind==='video')?.sender;if(sender)await sender.replaceTrack(track);ui.querySelector('.call-self').srcObject=local}else{const track=local?.getVideoTracks()[0];if(track){const sender=pc?.getSenders().find(x=>x.track===track);if(sender)await sender.replaceTrack(null);local.removeTrack(track);track.stop()}}}catch(e){cameraOn=false;showToast('Kamera açılamadı.')}if(call?.status==='active'&&!screen)await signal('video-state',{enabled:cameraOn}).catch(()=>{});render()}
  async function flipCamera(){const old=local?.getVideoTracks()[0];if(old){const sender=pc?.getSenders().find(s=>s.track===old);if(sender)await sender.replaceTrack(null);local.removeTrack(old);old.stop()}face=face==='user'?'environment':'user';cameraOn=false;await toggleCamera()}
  async function toggleShare(){if(screen){screen.getTracks().forEach(t=>t.stop());screen=null;await signal('screen-stop',{camera:cameraOn});if(cameraOn){const track=local?.getVideoTracks()[0];const sender=pc?.getTransceivers().find(x=>x.receiver.track.kind==='video')?.sender;if(sender)await sender.replaceTrack(track||null)}render();return}
    if(!navigator.mediaDevices?.getDisplayMedia)return showToast('Bu tarayıcı ekran paylaşımını desteklemiyor.');try{screen=await navigator.mediaDevices.getDisplayMedia({video:{displaySurface:'browser'},audio:false,preferCurrentTab:true,selfBrowserSurface:'include'});const track=screen.getVideoTracks()[0];const handle=track.getCaptureHandle?.();if(track.getSettings().displaySurface!=='browser'||handle?.handle!=='erischat-current-tab'||handle?.origin!==location.origin){screen.getTracks().forEach(t=>t.stop());screen=null;return showToast('Yalnızca bu ErisChat sekmesi paylaşılabilir; tarayıcınız bunu doğrulayamadı.')}const sender=pc?.getTransceivers().find(x=>x.receiver.track.kind==='video')?.sender;if(sender)await sender.replaceTrack(track);else{screen.getTracks().forEach(t=>t.stop());screen=null;return showToast('Görüntü bağlantısı hazır değil.')}await signal('screen-state',{enabled:true});track.onended=()=>{if(screen)toggleShare().catch(()=>{})};render()}catch(e){screen=null;showToast('Ekran paylaşımı başlatılamadı.')}}

  function stopRing(){if(ringTimer){clearInterval(ringTimer);ringTimer=null}ringContext?.close?.().catch(()=>{});ringContext=null}
  function startRing(incoming){stopRing();try{ringContext=new (window.AudioContext||window.webkitAudioContext)();const play=()=>{if(!ringContext||!call||call.status!=='ringing')return;ringContext.resume().then(()=>{const oscillator=ringContext.createOscillator(),gain=ringContext.createGain();oscillator.type='sine';oscillator.frequency.value=incoming?660:440;gain.gain.value=.045;oscillator.connect(gain).connect(ringContext.destination);oscillator.start();oscillator.stop(ringContext.currentTime+.28)}).catch(()=>{})};play();ringTimer=setInterval(play,incoming?1500:2200)}catch{}}
  function consent(kind){return new Promise(resolve=>{install();const modal=document.createElement('div');modal.className='eris-call-consent';modal.innerHTML='<section role="dialog" aria-modal="true" aria-label="Arama ücreti"><h2>Aramayı başlat</h2><p>'+ (kind==='video'?'Görüntülü':'Sesli') +' arama için <strong>40 <img src="./lidya-coin.png" alt="Lidya"></strong> tahsil edilir. Arama kabul edilirse karşı tarafa 20 Lidya aktarılır; kabul edilmez veya ulaşılmazsa 40 Lidya iade edilir.</p><nav><button class="decline" type="button">Reddet</button><button class="agree" type="button">Kabul et</button></nav></section>';document.body.append(modal);const done=value=>{modal.remove();resolve(value)};modal.querySelector('.decline').onclick=()=>done(false);modal.querySelector('.agree').onclick=()=>done(true);modal.onclick=e=>{if(e.target===modal)done(false)};modal.onkeydown=e=>{if(e.key==='Escape')done(false)};modal.querySelector('.agree').focus()})}
  async function toggleOutput(){const audio=ui?.querySelector('.call-audio');if(!audio)return;try{if(typeof audio.setSinkId!=='function')throw Error('Bu tarayıcı ahize yönlendirmesini desteklemiyor.');const devices=await navigator.mediaDevices.enumerateDevices();const outputs=devices.filter(d=>d.kind==='audiooutput');const target=audioOutput==='speaker'?outputs.find(d=>/earpiece|receiver|ahize/i.test(d.label)):outputs.find(d=>/speaker|hoparlör/i.test(d.label));if(!target)throw Error('Bu cihazda ayrı ahize ve hoparlör çıkışı bulunamadı.');await audio.setSinkId(target.deviceId);audioOutput=audioOutput==='speaker'?'earpiece':'speaker';render();showToast(audioOutput==='speaker'?'Hoparlör açık.':'Ahize açık.')}catch(e){showToast(e.message||'Ses çıkışı değiştirilemedi.')}}
  function minimize(){if(!call)return;cameraOn=false;screen?.getTracks().forEach(t=>t.stop());screen=null;const track=local?.getVideoTracks()[0];if(track){pc?.getSenders().find(s=>s.track===track)?.replaceTrack(null).catch(()=>{});local.removeTrack(track);track.stop()}if(call.status==='active')signal('video-state',{enabled:false}).catch(()=>{});mini=true;render();window.ErisChatDM?.open?.(call.conversation_id,call.peer_name,call.avatar_asset||'',call.peer_id)?.catch?.(()=>{})}
  function syncChat(){install();const chat=document.getElementById('chat'),head=chat?.querySelector('.chatHead');if(!head)return;let actions=head.querySelector('.dm-call-head');if(!actions){actions=document.createElement('div');actions.className='dm-call-head';actions.innerHTML='<button type="button" data-video aria-label="Görüntülü ara" title="Görüntülü ara">📷</button><button type="button" data-voice aria-label="Sesli ara" title="Sesli ara">☎</button>';head.insertBefore(actions,head.querySelector('.close'));actions.querySelector('[data-voice]').onclick=()=>start('voice');actions.querySelector('[data-video]').onclick=()=>start('video')}actions.hidden=false;const id=window.ErisChatDM?.activeId?.();if(id)api()?.conversation?.(id).then(conversation=>{if(window.ErisChatDM?.activeId?.()===id)actions.hidden=conversation.type!=='dm'}).catch(()=>{})}
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&call){render();tick()}});window.addEventListener('pagehide',()=>{if(call){const id=call.id;cleanup();const token=api()?.getAccessToken?.();fetch((window.ERIS_API||'https://erischat-api-production.up.railway.app/v1')+'/calls/'+encodeURIComponent(id)+'/end',{method:'POST',headers:{Authorization:'Bearer '+token},keepalive:true}).catch(()=>{})}});
  window.ErisCalls={start,syncChat,end,isActive:()=>!!call};timer=window.ErisApiTransport.poll(tick,3000);setTimeout(tick,600);
  window.addEventListener('erischat:auth',event=>{if(event.detail?.state==='logged_out'&&call)end()});
})();
