(() => {
  'use strict';
  let revision=0,initialized=false;
  const notifications={enabled:true,apply(p){if(!p||p.hide_notifications===undefined)return;const enabled=!p.hide_notifications,changed=enabled!==this.enabled;this.enabled=enabled;document.documentElement.classList.toggle('notifications-hidden',!enabled);document.querySelectorAll('[data-privacy-key="hide_notifications"] .switch').forEach(el=>el.classList.toggle('on',!enabled));if(changed){window.dispatchEvent(new CustomEvent('erischat:notification-settings',{detail:{enabled}}));if(enabled)window.ErisAnnouncements?.load?.();}},async load(){const index=++revision;try{const p=await window.ErisPlatform?.api('/me/privacy');if(index===revision)this.apply(p);}catch{}}};
  window.ErisNotifications=notifications;
  window.addEventListener('erischat:auth',e=>{if(e.detail?.state==='ready')notifications.load();else if(e.detail?.state==='logged_out'){revision++;notifications.apply({hide_notifications:false})}});
  window.addEventListener('erischat:profile',e=>{if(e.detail?.notifications_enabled!==undefined)notifications.apply({hide_notifications:!e.detail.notifications_enabled})});
  const setup=()=>{if(initialized)return;initialized=true;const pages=new Set(['search','shop','vip','anon','support','family','wallet','collection','messages','explore','profile']);let close=document.getElementById('homeMenuPageClose');if(!close){close=document.createElement('button');close.id='homeMenuPageClose';close.className='menu-page-close';close.type='button';close.textContent='×';close.setAttribute('aria-label','Ana sayfaya dön');close.hidden=true;close.onclick=()=>window.showView?.('home');document.body.append(close)}const sync=()=>{if(!document)return;const view=document.querySelector('.content>.view.show');const active=view&&pages.has(view.id);document.querySelectorAll('.content>.view').forEach(v=>{if(v.classList.contains('menu-page')!==pages.has(v.id))v.classList.toggle('menu-page',pages.has(v.id))});close.hidden=!active;};new MutationObserver(sync).observe(document.querySelector('.content')||document.body,{attributes:true,attributeFilter:['class'],subtree:true});sync();notifications.load();};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup,{once:true});else setup();
})();
