(() => {
  'use strict';
  const platform=()=>window.ErisPlatform;
  const api=(path,method='GET',body)=>platform().api('/location-calls'+path,{method,...(body?{body:JSON.stringify(body)}:{})});
  let radius=30,locationRequired=false,locationHidden=false,ui=null,mode='voice',quota=null,call=null,phase='select',stream=null,pc=null,music=null,cursor=0,clock=0,countdown=0,generation=0,busy=false,polling=false,offered=false,ice=[],notice='',extensionKey=null,disconnect=null,lastStatus=0,connectionPromise=null,remoteStream=null,joinPromise=null,endingPromise=null,pollFailures=0;
  const dialogs=new Set(),instant=()=>Date.now()+clock;
  const time=seconds=>`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
  function install(){
    if(document.getElementById('location-style'))return;
    const style=document.createElement('style');style.id='location-style';style.textContent=`
    .eris-location{position:fixed;inset:0;z-index:23000;display:flex;flex-direction:column;align-items:center;gap:14px;padding:calc(20px + env(safe-area-inset-top)) 18px calc(20px + env(safe-area-inset-bottom));background:radial-gradient(circle at 50% 20%,#38214d,#090611 70%);color:#fff}.eris-location [hidden]{display:none!important}.eris-location button{color:#fff;background:#ffffff12;border:1px solid #ffffff28;border-radius:14px;padding:12px}.eris-location button:disabled{opacity:.5}.loc-head{display:flex;align-items:center;justify-content:space-between;width:100%;gap:10px}.loc-count{border-radius:99px;background:#16754e;padding:8px 12px;font-size:12px}.loc-title{font-size:22px;text-align:center;margin:8px 0}.loc-time{font-size:38px;font-variant-numeric:tabular-nums}.loc-status,.loc-quota{color:#c5b2d5;text-align:center;font-size:13px}.loc-packages{display:flex;justify-content:center;align-items:center;gap:16px;flex:1;width:min(460px,100%)}.eris-location .loc-package{position:relative;border:0;background:transparent;padding:0;max-width:48%}.loc-package img{display:block;width:100%;max-height:240px;object-fit:contain}.loc-package[data-locked=true] img{opacity:.65}.loc-lock{position:absolute;right:5%;top:5%;font-size:28px}.loc-stage{position:relative;width:100%;flex:1;min-height:0;overflow:hidden;border-radius:20px;background:#130d1e;display:grid;place-items:center}.loc-remote{width:100%;height:100%;object-fit:cover}.loc-self{position:absolute;right:12px;top:12px;width:95px;height:125px;object-fit:cover;border-radius:12px}.loc-voice{font-size:80px}.loc-actions{display:flex;gap:12px;align-items:center;justify-content:center;width:100%;margin-top:auto}.eris-location .loc-hangup{background:#be304c;flex:1;max-width:260px}.loc-bubble{display:none}.eris-location.mini{inset:auto 12px 100px auto;width:110px;height:120px;padding:8px;gap:0;border-radius:20px;border:1px solid #ad80d9;box-shadow:0 10px 30px #0008}.eris-location.mini>*{display:none!important}.eris-location.mini .loc-bubble{display:block!important;width:100%;height:100%;font-size:24px}.loc-dialog{position:fixed;inset:0;z-index:24000;background:#030109c9;display:grid;place-items:center;padding:20px}.loc-dialog section{position:relative;width:min(380px,100%);border:1px solid #a77aff66;border-radius:24px;padding:52px 22px 22px;background:#21152e;color:#fff;line-height:1.6;white-space:pre-line}.loc-dialog header{position:absolute;top:10px;left:12px;right:12px;display:flex;justify-content:space-between}.loc-dialog button{border:1px solid #ffffff25;border-radius:12px;padding:10px 16px;background:#ffffff15;color:#fff}.loc-dialog nav{display:flex;gap:12px;margin-top:20px}.loc-dialog nav button{flex:1}.loc-dialog [data-yes]{background:#188054}.loc-dialog [data-no]{background:#ab304a}
    `;document.head.append(style);
  }
  function dialog(text,{info=null,confirm=true,accept='Kabul Et'}={}){
    return new Promise(resolve=>{install();const root=document.createElement('div');root.className='loc-dialog';root.innerHTML='<section role="dialog" aria-modal="true"><header><button type="button" data-info aria-label="Bilgi">?</button><button type="button" data-close aria-label="Kapat">✕</button></header><div data-text></div><nav><button type="button" data-yes></button><button type="button" data-no>Reddet</button></nav></section>';
      root.querySelector('[data-text]').textContent=text;root.querySelector('[data-yes]').textContent=accept;root.querySelector('[data-no]').hidden=!confirm;root.querySelector('[data-info]').hidden=!info;
      let done=false;const finish=value=>{if(done)return;done=true;root.remove();dialogs.delete(finish);resolve(value);};dialogs.add(finish);
      root.querySelector('[data-yes]').onclick=()=>finish(true);root.querySelector('[data-no]').onclick=()=>finish(false);root.querySelector('[data-close]').onclick=()=>finish(false);root.querySelector('[data-info]').onclick=()=>dialog(info,{confirm:false,accept:'Satın alma penceresine dön'});root.onkeydown=e=>{if(e.key==='Escape')finish(false);};document.body.append(root);root.querySelector('[data-yes]').focus();
    });
  }
  function build(){
    install();ui=document.createElement('section');ui.className='eris-location';ui.setAttribute('role','dialog');ui.setAttribute('aria-label','Konuma göre eşleşme');ui.innerHTML='<header class="loc-head"><button type="button" data-peer hidden>👤 Profil</button><span class="loc-count" aria-label="Aktif kullanıcı sayısı">0 çevrim içi</span><button type="button" data-request hidden aria-label="Profil isteği gönder">👤＋</button><button type="button" data-close aria-label="Kapat">✕</button></header><h2 class="loc-title"></h2><div class="loc-status" role="status"></div><div class="loc-time"></div><div class="loc-quota"></div><div class="loc-packages"><button type="button" class="loc-package" data-standard><img alt="Standart arama"><span>Standart Eşleşme</span></button><button type="button" class="loc-package" data-premium><img alt="Premium arama"><span>Premium Eşleşme</span><span class="loc-lock">🔒</span></button></div><div class="loc-stage" hidden><video class="loc-remote" autoplay playsinline></video><video class="loc-self" autoplay playsinline muted></video><div class="loc-voice">☎</div></div><audio class="loc-audio" autoplay></audio><button type="button" data-location>Konumumu güncelle</button><button type="button" data-music hidden>Bekleme müziğini aç</button><div class="loc-actions"><button type="button" data-extend hidden aria-label="Ek süre satın al">⌛</button><button type="button" data-mic hidden aria-label="Mikrofonu kapat">🎙</button><button type="button" data-camera hidden aria-label="Kamerayı kapat">📷</button><button type="button" class="loc-hangup" data-end hidden>Eşleşmeyi Sonlandır</button></div><button type="button" class="loc-bubble" aria-label="Eşleşmeye dön">☎<small data-mini-time></small></button>';document.body.append(ui);ui.addEventListener('pointerup',()=>{const media=ui?.querySelector(mode==='video'?'.loc-remote':'.loc-audio');if(media?.srcObject)media.play().catch(()=>{})});
    ui.querySelector('[data-location]').onclick=async()=>{if(locationHidden){await end();window.showView?.('anon');window.ErisPrivacy?.load?.();return;}try{await updateLocation();locationRequired=false;render();}catch(e){window.toast?.(e.message);}};
    ui.querySelector('[data-standard]').onclick=start;ui.querySelector('[data-premium]').onclick=()=>quota?.premium?start():purchase();ui.querySelector('[data-close]').onclick=end;ui.querySelector('[data-end]').onclick=end;ui.querySelector('[data-extend]').onclick=extend;ui.querySelector('[data-request]').onclick=profileRequest;
    ui.querySelector('[data-peer]').onclick=()=>{if(call?.peer){ui.classList.add('mini');window.openUserProfile?.(call.peer.user_id);}};ui.querySelector('.loc-bubble').onclick=()=>ui?.classList.remove('mini');
    for(const [selector,kind,on,off] of [['[data-mic]','audio','🎙','🎙̸'],['[data-camera]','video','📷','📷̸']])ui.querySelector(selector).onclick=()=>{const track=stream?.getTracks().find(t=>t.kind===kind);if(track){track.enabled=!track.enabled;ui.querySelector(selector).textContent=track.enabled?on:off;}};
    ui.querySelector('[data-music]').onclick=()=>music?.play().then(()=>{if(ui)ui.querySelector('[data-music]').hidden=true;}).catch(()=>window.toast?.('Bekleme müziği açılamadı.'));
  }
  function render(){
    if(!ui)return;if(phase==='landing')return;const selecting=phase==='select',live=call?.status==='active';ui.querySelector('.loc-title').textContent=mode==='video'?'Görüntülü Eşleşme':'Sesli Eşleşme';ui.querySelector('.loc-status').textContent=selecting?(locationHidden?'Konumunuz gizli. Eşleşmek için Gizlilik ayarlarından görünürlüğü açın.':locationRequired?'Başlamak için konum izni gerekli.':'Eşleşme paketini seç'):phase==='countdown'?'Hazırlanıyoruz... Yakınındaki uygun bir kullanıcı aranıyor.':call?.status==='preparing'?'Eşleşme bulundu! Hazırlanın, bağlantınız kuruluyor.':live?(pc?.connectionState==='connected'?'Görüşme sürüyor':'Canlı bağlantı kuruluyor…'):'Yakınındaki uygun kişi aranıyor...';ui.querySelector('.loc-quota').textContent=quota?`Kalan ${quota.remaining}/${quota.daily_limit} eşleşme hakkı${quota.premium?' • Premium':''} • ${radius} km yakınlık alanı`:'';
    ui.querySelector('.loc-packages').hidden=!selecting;ui.querySelector('[data-standard]').hidden=!!quota?.premium;ui.querySelector('[data-standard]').disabled=busy||locationHidden||!quota||quota.remaining<=0;ui.querySelector('[data-premium]').disabled=busy||!quota||(quota.used>=20||quota.premium&&quota.remaining<=0);ui.querySelector('[data-premium]').dataset.locked=String(!quota?.premium);ui.querySelector('.loc-lock').hidden=!!quota?.premium;ui.querySelector('[data-location]').hidden=!selecting;ui.querySelector('[data-location]').textContent=locationHidden?'Gizlilik ayarlarını aç':'Konum izni ver / güncelle';ui.querySelector('[data-location]').disabled=busy;
    for(const [selector,kind] of [['[data-standard]','standard'],['[data-premium]','premium']])ui.querySelector(selector+' img').src=`./anonymous-assets/${kind}-${mode}.png`;
    ui.querySelector('[data-end]').hidden=selecting;ui.querySelector('[data-extend]').hidden=!live;ui.querySelector('[data-mic]').hidden=!live;ui.querySelector('[data-camera]').hidden=!live||mode!=='video';ui.querySelector('[data-request]').hidden=!live||call?.profile_status==='accepted';ui.querySelector('[data-request]').disabled=call?.profile_status==='pending'||busy;ui.querySelector('[data-peer]').hidden=!call?.peer;ui.querySelector('.loc-stage').hidden=!live;ui.querySelector('.loc-remote').hidden=mode!=='video';ui.querySelector('.loc-self').hidden=mode!=='video';ui.querySelector('.loc-voice').hidden=mode==='video';
    const seconds=phase==='countdown'?Math.max(0,Math.ceil((countdown-Date.now())/1000)):call?.status==='preparing'?Math.max(0,Math.ceil((Date.parse(call.starts_at)-instant())/1000)):call?Math.max(0,Math.ceil((Date.parse(call.ends_at)-instant())/1000)):quota?.initial_seconds||60;ui.querySelector('.loc-time').textContent=selecting?'':time(seconds);ui.querySelector('[data-mini-time]').textContent=time(seconds);
  }
  async function purchase(){
    if(busy||!ui)return;const stamp=generation;const agreed=await dialog('Premium eşleşme özelliğini satın almak istiyor musunuz? 1.000 Lidya',{info:'Premium özellik neleri aktif eder?\n\nGünlük eşleşme hakkınız 10’dan 20’ye çıkar.\nBaşlangıç süreniz 60 saniyeden 120 saniyeye çıkar.\n200 Lidya karşılığındaki süre uzatmanız 120 yerine 240 saniye olur.\n\nPremium özelliğiniz İstanbul saatine göre gece 24.00’a veya günlük 20 hakkınız dolana kadar geçerlidir.'});if(!agreed||stamp!==generation)return;busy=true;render();try{quota=await api('/premium','POST');}catch(e){window.toast?.(e.message);}finally{busy=false;render();}
  }
  function stopMusic(){music?.pause();const button=ui?.querySelector('[data-music]');if(button)button.hidden=true;}
  function waitingMusic(){if(!music||phase!=='queued')return;music.loop=true;music.muted=false;music.play().catch(()=>{if(ui&&phase==='queued')ui.querySelector('[data-music]').hidden=false;});}
  async function updateLocation(){
    if(!navigator.geolocation)throw Error('Bu cihazda konum kullanılamıyor.');
    const stamp=generation;
    const position=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,()=>reject(Error('Yakındaki kişilerle eşleşmek için konum izni gerekli.')),{enableHighAccuracy:true,timeout:15000,maximumAge:60000}));
    if(stamp!==generation)throw Error('Eşleşme kapatıldı.');
    await platform().setLocation({latitude:position.coords.latitude,longitude:position.coords.longitude,city:'Yakınım'});
  }
  async function start(){
    if(busy||!ui||quota?.remaining<=0)return;if(window.ErisAnonymousCalls?.isActive?.())return window.toast?.('Önce anonim aramanızı kapatın.');if(locationHidden)return window.toast?.('Önce konum gizliliğinizi açın.');if(window.ErisCalls?.isActive?.())return window.toast?.('Önce devam eden aramanızı kapatın.');if(!window.RTCPeerConnection||!navigator.mediaDevices?.getUserMedia)return window.toast?.('Bu tarayıcı sesli ve görüntülü aramayı desteklemiyor.');
    const stamp=generation;busy=true;render();music=new Audio('./anonymous-assets/waiting.mp3');music.volume=0.6;music.muted=true;const primed=music;primed.play().then(()=>{if(primed!==music){primed.pause();return;}if(phase!=='queued'){primed.pause();primed.currentTime=0;}primed.muted=false;}).catch(()=>{});
    try{await updateLocation();if(stamp!==generation)return;locationRequired=false;window.ErisRoomRTC?.stop?.();const media=await navigator.mediaDevices.getUserMedia({audio:true,video:mode==='video'?{facingMode:'user'}:false});if(stamp!==generation){media.getTracks().forEach(track=>track.stop());return;}stream=media;ui.querySelector('.loc-self').srcObject=stream;phase='countdown';countdown=Date.now()+3000;render();}catch(e){if(stamp===generation){window.toast?.(e.message||'Mikrofon/kamera izni verilmedi veya cihaz açılamadı.');phase='select';stopMusic();}}finally{if(stamp===generation){busy=false;render();}}
  }
  function join(){if(joinPromise)return joinPromise;joinPromise=joinRequest().finally(()=>{joinPromise=null});return joinPromise;}
  async function joinRequest(){
    if(busy||phase!=='countdown')return;const stamp=generation;busy=true;
    try{const data=await api('/queue','POST',{mode});if(stamp!==generation)return;quota=data.quota||quota;phase='queued';ui.querySelector('.loc-count').textContent=`${data.active_users||0} çevrim içi`;if(data.call)await adopt(data.call);else waitingMusic();}catch(e){if(stamp===generation){window.toast?.(e.message);cleanup();}}finally{if(stamp===generation){busy=false;render();}}
  }
  async function send(kind,payload,stamp=generation){if(stamp===generation&&call)await api('/'+call.id+'/signals','POST',{kind,payload});}
  async function connection(){if(pc)return pc;if(connectionPromise)return connectionPromise;const promise=createConnection();connectionPromise=promise;try{return await promise;}finally{if(connectionPromise===promise)connectionPromise=null;}}
  async function createConnection(){
    if(pc)return pc;const stamp=generation;const config=await platform().api('/calls/rtc-config');if(stamp!==generation||!stream)throw Error('Eşleşme kapatıldı.');const peer=new RTCPeerConnection({iceServers:config.ice_servers});pc=peer;stream.getTracks().forEach(track=>peer.addTrack(track,stream));
    peer.onicecandidate=e=>{if(e.candidate)send('ice',e.candidate.toJSON(),stamp).catch(()=>{});};
    peer.ontrack=e=>{if(stamp!==generation||!ui)return;const element=ui.querySelector(mode==='video'?'.loc-remote':'.loc-audio');if(!remoteStream)remoteStream=new MediaStream();for(const track of (e.streams[0]?.getTracks()||[e.track])){if(!remoteStream.getTracks().some(t=>t.id===track.id))remoteStream.addTrack(track)}element.srcObject=remoteStream;element.play().catch(()=>window.toast?.('Sesi açmak için arama ekranına dokunun.'));};
    disconnect=setTimeout(()=>{if(stamp===generation&&peer.connectionState!=='connected'){window.toast?.('Eşleşme bağlantısı kurulamadı. İnternet bağlantınızı kontrol edin.');end();}},20000);
    peer.onconnectionstatechange=()=>{if(stamp!==generation)return;if(peer.connectionState==='connected')clearTimeout(disconnect);else if(['failed','disconnected'].includes(peer.connectionState)){clearTimeout(disconnect);disconnect=setTimeout(()=>{if(pc===peer&&peer.connectionState!=='connected'){window.toast?.('Eşleşme bağlantısı kesildi.');end();}},10000);}render();};return peer;
  }
  async function receive(event){
    const stamp=generation;const peer=await connection();if(stamp!==generation)return;
    if(event.kind==='ice'){if(peer.remoteDescription)await peer.addIceCandidate(event.payload).catch(()=>{});else if(ice.length<128)ice.push(event.payload);return;}
    if(event.kind==='offer'){await peer.setRemoteDescription(event.payload);for(const candidate of ice.splice(0))await peer.addIceCandidate(candidate).catch(()=>{});const answer=await peer.createAnswer();await peer.setLocalDescription(answer);await send('answer',peer.localDescription.toJSON(),stamp);}
    else if(event.kind==='answer'&&peer.signalingState==='have-local-offer'){await peer.setRemoteDescription(event.payload);for(const candidate of ice.splice(0))await peer.addIceCandidate(candidate).catch(()=>{});}
  }
  async function offer(){
    if(offered||!call?.initiator||call.status!=='active')return;const stamp=generation;offered=true;
    try{const peer=await connection();const value=await peer.createOffer();await peer.setLocalDescription(value);await send('offer',peer.localDescription.toJSON(),stamp);}catch(e){if(stamp===generation){window.toast?.(e.message||'Canlı bağlantı kurulamadı.');await end();}}
  }
  async function adopt(value){
    if(!ui)return;call=value;mode=value.mode;phase='call';clock=value.server_now?Date.parse(value.server_now)-Date.now():0;stopMusic();render();
    if(value.status==='ended'){window.toast?.(value.reason==='time'?'Eşleşme süresi doldu.':'Eşleşme sona erdi.');cleanup();return;}
    if(!stream){window.toast?.('Eşleşme başka bir ekranınızda açık.');cleanup();return;}if(value.status==='active')await offer();
    if(value.profile_incoming&&notice!=='pending'){notice='pending';const stamp=generation;dialog('Karşı taraf profilinize erişmek istedi, onaylıyor musunuz?').then(async accepted=>{if(stamp!==generation||!call)return;try{await api('/'+call.id+'/profile-response','POST',{action:accepted?'accept':'reject'});}catch(e){window.toast?.(e.message);}});}
    else if(value.profile_status!=='pending')notice=value.profile_status;
  }
  async function poll(){
    if(!ui||polling||busy||phase==='countdown'||phase==='landing')return;if(phase==='select'&&Date.now()-lastStatus<5000)return;polling=true;const stamp=generation;
    try{if(phase==='select'){lastStatus=Date.now();const data=await api('/status?mode='+mode);if(stamp!==generation)return;quota=data.quota;radius=data.radius_km||radius;locationRequired=!!data.location_required;locationHidden=!!data.location_hidden;ui.querySelector('.loc-count').textContent=`${data.active_users} çevrim içi`;if(data.call||data.queued){window.toast?.('Konuma göre eşleşme başka bir ekranınızda açık.');cleanup();}}
      else if(call){const data=await api('/'+call.id+'/events?after='+cursor);if(stamp!==generation)return;ui.querySelector('.loc-count').textContent=`${data.active_users} çevrim içi`;await adopt(data.call);if(stamp!==generation||!call)return;for(const event of data.events){await receive(event);if(event.id)cursor=event.id;}cursor=data.cursor;}
      else{const data=await api('/heartbeat','POST');if(stamp!==generation)return;quota=data.quota;radius=data.radius_km||radius;locationRequired=!!data.location_required;locationHidden=!!data.location_hidden;ui.querySelector('.loc-count').textContent=`${data.active_users} çevrim içi`;if(data.call)await adopt(data.call);else if(!data.queued){window.toast?.('Eşleşme kuyruğu bağlantınız sona erdi.');cleanup();}}
      pollFailures=0;
    }catch(e){if(stamp===generation&&++pollFailures>=3){window.toast?.(e.message||'Eşleşme bağlantısı kurulamadı.');await end();}}finally{polling=false;render();}
  }
  async function extend(){
    if(busy||!call)return;const stamp=generation;const agreed=await dialog('200 Lidya karşılığında ek süre almak istiyor musunuz?');if(!agreed||stamp!==generation||!call)return;busy=true;extensionKey=extensionKey||crypto.randomUUID();render();
    try{const data=await api('/'+call.id+'/extend','POST',{request_key:extensionKey});if(stamp!==generation)return;extensionKey=null;await adopt(data.call);window.toast?.(`${data.seconds} saniye ortak süreye eklendi.`);}catch(e){window.toast?.(e.message);}finally{busy=false;render();}
  }
  async function profileRequest(){if(busy||!call)return;busy=true;try{await api('/'+call.id+'/profile-request','POST');notice='';window.toast?.('Profil isteği gönderildi.');}catch(e){window.toast?.(e.message);}finally{busy=false;render();}}
  function cleanup(){generation++;for(const close of [...dialogs])close(false);clearTimeout(disconnect);pc?.close();pc=null;connectionPromise=null;remoteStream=null;pollFailures=0;stream?.getTracks().forEach(track=>track.stop());stream=null;stopMusic();music=null;ui?.remove();ui=null;call=null;cursor=0;ice=[];offered=false;notice='';extensionKey=null;busy=false;phase='select';}
  async function end(){if(endingPromise)return endingPromise;const existed=phase==='queued'||!!call||!!joinPromise;const pending=joinPromise;cleanup();endingPromise=(async()=>{await pending?.catch(()=>{});if(existed)await api('/cancel','POST').catch(()=>{});})();try{await endingPromise;}finally{endingPromise=null;}}
  function landing(){
    install();ui=document.createElement('section');ui.className='eris-location';ui.setAttribute('role','dialog');ui.setAttribute('aria-label','Konuma göre eşleşme');ui.innerHTML='<header class="loc-head"><strong>📍 Konuma Göre Eşleşme</strong><button type="button" data-close aria-label="Kapat">✕</button></header><p class="loc-status">Konumuna göre yakınındaki aktif kullanıcılarla sesli veya görüntülü olarak eşleş.</p><div class="loc-packages"><button type="button" class="loc-package" data-mode="voice"><img src="./anonymous-assets/standard-voice.png" alt="Sesli Eşleşme"><strong>Sesli Eşleşme</strong><p>Yakınındaki bir kullanıcıyla sesli bağlantı kur.</p></button><button type="button" class="loc-package" data-mode="video"><img src="./anonymous-assets/standard-video.png" alt="Görüntülü Eşleşme"><strong>Görüntülü Eşleşme</strong><p>Yakınındaki bir kullanıcıyla görüntülü bağlantı kur.</p></button></div>';document.body.append(ui);phase='landing';ui.querySelector('[data-close]').onclick=end;ui.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>open(button.dataset.mode));
  }
  async function open(kind){
    if(endingPromise)await endingPromise;
    if(ui&&phase==='landing'&&kind){ui.remove();ui=null;generation++;}
    if(ui)return ui.classList.remove('mini');
    if(!platform()?.getAccessToken?.())return window.toast?.('Önce giriş yap.');
    if(!kind){landing();return;}
    mode=kind==='video'?'video':'voice';build();phase='select';busy=true;render();const stamp=generation;
    try{const data=await api('/status?mode='+mode);if(stamp!==generation)return;quota=data.quota;radius=data.radius_km||radius;locationRequired=!!data.location_required;locationHidden=!!data.location_hidden;if(data.call||data.queued){window.toast?.('Konuma göre eşleşme başka bir ekranınızda açık.');cleanup();return;}ui.querySelector('.loc-count').textContent=`${data.active_users||0} çevrim içi`;}catch(e){if(stamp===generation){window.toast?.(e.message);cleanup();}}finally{if(stamp===generation){busy=false;render();}}
  }
  function exit(){if(!ui)return;const active=phase==='queued'||!!call;cleanup();if(!active)return;const base=(window.ERIS_API||'https://erischat-api-production.up.railway.app/v1').replace(/\/$/,'');fetch(base+'/location-calls/cancel',{method:'POST',headers:{Authorization:'Bearer '+platform()?.getAccessToken?.()},keepalive:true}).catch(()=>{});}
  window.ErisLocationCalls={open,end,isActive:()=>!['select','landing'].includes(phase)&&!!ui};
  setInterval(()=>{if(!ui)return;render();if(phase==='countdown'&&Date.now()>=countdown)join();else poll();},1000);
  window.addEventListener('pagehide',exit);window.addEventListener('erischat:auth',event=>{if(event.detail?.state==='logged_out')cleanup();});
})();
