(() => {
  'use strict';
  const mounted=new Map();
  window.addEventListener('erischat:auth',()=>{for(const [root,entry] of mounted){if(!root.isConnected||!entry.valid()){mounted.delete(root);continue}if(entry.account!==token()){root.textContent='Hesap değişti. Ayarlar menüsünü yeniden aç.';mounted.delete(root)}}});
  const token=()=>window.ErisPlatform?.getAccessToken?.()||'';
  const api=(p,o)=>window.ErisPlatform.api(p,o);
  const style=document.createElement('style');style.textContent=`.eps{min-width:0;color:#f7f0fc}.eps .eps-intro{color:#b7a6c5;font-size:14px;line-height:1.6;margin:0 0 20px}.eps .eps-card{padding:18px;margin:14px 0;border:1px solid #a978cb30;border-radius:20px;background:linear-gradient(140deg,#261a31,#15111d)}.eps h3{margin:0 0 8px;font-size:16px}.eps small,.eps p{color:#b7a6c5;font-size:13px;line-height:1.6;overflow-wrap:anywhere}.eps .eps-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.eps button.eps-button{width:auto!important;height:auto!important;min-height:44px;max-width:100%;border:1px solid #a578cb44!important;border-radius:13px!important;padding:11px 16px!important;background:#392344;color:#f0deff;font:inherit;font-size:14px!important;white-space:normal!important;cursor:pointer}.eps button:disabled{opacity:.5;cursor:wait}.eps button:focus-visible,.eps select:focus-visible{outline:2px solid #d9a5ff;outline-offset:3px}.eps select{width:100%;box-sizing:border-box;min-height:48px;padding:12px;border:1px solid #9665b444;border-radius:14px;background:#1b1224;color:white;font:inherit;font-size:14px}.eps .eps-row{display:flex;align-items:center;justify-content:space-between;gap:12px}.eps .eps-row>div{min-width:0;flex:1}.eps .eps-danger{border-color:#ed8f9e44;color:#ffbdc8;background:#41212d}.eps .eps-status{min-height:24px;color:#c9a9e2;font-size:13px;line-height:1.6}.eps .eps-visitor{padding:15px;margin:10px 0;border:1px solid #a578cb33;border-radius:17px;background:#1a1322}.eph-overlay .eph-dialog-content [data-erischat-profile-controls]{display:none!important}`;document.head.append(style);
  function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
  function button(text,fn){const b=el('button','eps-button',text);b.type='button';b.onclick=fn;return b}
  async function render(root,valid=()=>true){
    const account=token();const active=()=>root.isConnected&&valid()&&account===token();let busy=false,privacy=null,restriction=null;
    for(const [r,e] of mounted)if(!r.isConnected||!e.valid())mounted.delete(r);
    mounted.set(root,{account,valid});
    root.classList.add('eps');root.replaceChildren();root.append(el('p','eps-intro','Bildirimlerini, mesaj tercihlerini ve hesabını tek yerden yönet.'));
    const status=el('p','eps-status');status.setAttribute('role','status');
    function card(title,description){const c=el('section','eps-card');c.append(el('h3','',title),el('p','',description));root.append(c);return c}
    const notification=card('Uygulama bildirimleri','Uygulama içindeki bildirim listesini ve yeni bildirim kartlarını açıp kapat.');
    const noticeState=el('small','', 'Yükleniyor…'),toggle=button('Yükleniyor…',async()=>{if(!privacy)return;await save(async()=>{const next=!privacy.hide_notifications;const result=await api('/me/privacy',{method:'PATCH',body:JSON.stringify({hide_notifications:next})});if(!active())return;privacy=result;window.ErisNotifications?.apply?.(privacy);privacy=await api('/me/privacy');if(active()){if(privacy.hide_notifications!==next)throw Error('Bildirim ayarı doğrulanamadı.');window.ErisNotifications?.apply?.(privacy);window.dispatchEvent(new CustomEvent('erischat:privacy',{detail:privacy}))}})});toggle.setAttribute('role','switch');toggle.setAttribute('aria-label','Uygulama bildirimleri');toggle.setAttribute('aria-checked','false');toggle.disabled=true;const noticeRow=el('div','eps-row');noticeRow.append(noticeState,toggle);notification.append(noticeRow);
    const message=card('Mesajları kısıtla','Açıkken sana ilk kez yazacak kişi seçtiğin hediyeyi göndermeden mesaj gönderemez.');const lockState=el('p'),label=el('label','', 'Gerekli hediye');label.htmlFor='epsGiftChoice';const choice=el('select');choice.id='epsGiftChoice';choice.setAttribute('aria-label','Gerekli hediye');choice.disabled=true;const lockToggle=button('Yükleniyor…',()=>{if(restriction)save(async()=>{await writeRestriction(!restriction.enabled,choice.value)})});const lockSave=button('Hediye seçimini kaydet',()=>{if(restriction)save(async()=>{await writeRestriction(restriction.enabled,choice.value)})});lockToggle.disabled=lockSave.disabled=true;const actions=el('div','eps-actions');actions.append(lockToggle,lockSave);message.append(lockState,label,choice,actions);
    const shortcuts=card('Profil ve görünürlük','Kullanıcı adı değişikliği Bilgilerim bölümünde 150 Lidya ile yapılır. Diğer profil tercihlerini ilgili bölümden yönetebilirsin.');const links=el('div','eps-actions');for(const [key,name] of [['info','Bilgilerim'],['privacy','Gizlilik'],['rooms','Odalarım']])links.append(button(name,()=>{if(active())window.ErisProfileHub?.show(key)}));links.append(button('Profilime bakanlar',()=>visitors(root,active)));shortcuts.append(links);
    const session=card('Oturum','Bu cihazdaki hesabından çıkış yap.');const sessionActions=el('div','eps-actions');const logout=button('Oturumu kapat',()=>{if(!active())return;sessionActions.replaceChildren();const cancel=button('Vazgeç',()=>sessionActions.replaceChildren(logout));const yes=button('Evet, çıkış yap',async()=>{if(!active()||busy)return;yes.disabled=cancel.disabled=true;try{await window.ErisAuth.logout();if(active())status.textContent='Oturum kapatıldı.'}catch(e){if(active()){status.textContent=e.message||'Çıkış yapılamadı.';yes.disabled=cancel.disabled=false}}});yes.classList.add('eps-danger');sessionActions.append(yes,cancel)});logout.classList.add('eps-danger');sessionActions.append(logout);session.append(sessionActions);const reload=button('Ayarları yenile',load);root.append(status,reload);
    function sync(){if(!active())return;toggle.disabled=busy||!privacy;toggle.textContent=privacy&&!privacy.hide_notifications?'Açık':'Kapalı';toggle.setAttribute('aria-checked',String(!!privacy&&!privacy.hide_notifications));noticeState.textContent=privacy?(privacy.hide_notifications?'Bildirimler kapalı.':'Bildirimler açık.'):'Ayar yüklenemedi.';choice.disabled=busy||!restriction;lockToggle.disabled=lockSave.disabled=busy||!restriction;reload.disabled=busy;lockToggle.textContent=restriction?.enabled?'Kısıtlamayı kapat':'Kısıtlamayı aç';lockState.textContent=restriction?(restriction.enabled?'Açık · İlk mesaj için hediye gerekli.':'Kapalı · İlk mesaj için hediye gerekli değil.'):'Mesaj ayarı yüklenemedi.';if(restriction&&!busy)choice.value=restriction.gift_key}
    async function writeRestriction(enabled,gift_key){await window.ErisPlatform.setMessageRestriction({enabled,gift_key});if(!active())return;restriction=await window.ErisPlatform.getMessageRestriction();if(active()&&(restriction.enabled!==enabled||restriction.gift_key!==gift_key))throw Error('Mesaj ayarı doğrulanamadı.')}
    async function save(fn){if(busy||!active())return;busy=true;sync();status.textContent='Kaydediliyor…';try{await fn();if(active())status.textContent='Ayar kaydedildi.'}catch(e){if(active())status.textContent=e.message||'Ayar kaydedilemedi. Yenile ve tekrar dene.'}finally{busy=false;sync()}}
    async function load(){if(busy||!active())return;busy=true;sync();status.textContent='Ayarlar yükleniyor…';try{const results=await Promise.allSettled([api('/me/privacy'),window.ErisPlatform.getMessageRestriction(),window.ErisPlatform.messageGifts()]);if(!active())return;privacy=results[0].status==='fulfilled'?results[0].value:null;restriction=results[1].status==='fulfilled'?results[1].value:null;choice.replaceChildren();if(results[2].status==='fulfilled'){for(const gift of results[2].value){const option=el('option','',gift.gift_key+' · '+Number(gift.unit_price||0).toLocaleString('tr-TR')+' Lidya');option.value=gift.gift_key;choice.append(option)}}else restriction=null;if(restriction&&!Array.from(choice.options).some(x=>x.value===restriction.gift_key))restriction=null;if(privacy)window.ErisNotifications?.apply?.(privacy);status.textContent=results.every(r=>r.status==='fulfilled')?'Ayarların hesabına kaydedilir.':'Bazı ayarlar yüklenemedi. Yenile ve tekrar dene.'}finally{busy=false;sync()}}
    await load();
  }
  async function visitors(root,active){if(!active())return;root.replaceChildren();root.append(button('← Ayarlar',()=>window.ErisProfileHub?.show('settings')),el('h3','','Profilime bakanlar'));const list=el('div');list.setAttribute('aria-live','polite');root.append(list);async function load(){list.textContent='Yükleniyor…';try{const rows=await api('/me/profile-visitors');if(!active())return;list.replaceChildren();if(!rows.length)list.textContent='Henüz profilini ziyaret eden yok.';for(const row of rows){const card=el('article','eps-visitor');const name=el('b','',row.nickname||'Kullanıcı');window.ErisRoleBadges?.bind?.(name,row);const date=new Date(row.visited_at);card.append(name,el('p','',Number.isNaN(date.getTime())?'':date.toLocaleString('tr-TR')),button('Profili aç',()=>{if(active())window.openUserProfile?.(row.user_id)}));list.append(card)}}catch(e){if(active()){list.textContent=e.message||'Ziyaretçiler yüklenemedi.';list.append(button('Tekrar dene',load))}}}await load()}
  window.ErisSettings={render};
})();
