(function(){
  'use strict';
  const token=()=>window.ErisPlatform?.getAccessToken?.()||localStorage.getItem('erischat.accessToken.v1')||localStorage.getItem('erischat_access_token')||localStorage.getItem('token')||'';
  const base=()=> (window.ERIS_API||'https://erischat-api-production.up.railway.app/v1').replace(/\/$/,'');
  let locked=false,review=null,identity=token(),checking=false,eventPanel=null;
  const req=async(path,options={})=>{const sessionToken=token();const response=await fetch(base()+path,{...options,headers:{'Content-Type':'application/json',Authorization:'Bearer '+sessionToken,...(options.headers||{})}});const result=await response.json().catch(()=>({}));if(sessionToken!==token())throw new Error('Oturum değişti.');if(!response.ok)throw new Error(typeof result.detail==='string'?result.detail:result.detail?.message||'İşlem başarısız');return result;};
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function styles(){if(document.getElementById('erisSuggestionStyle'))return;const css=document.createElement('style');css.id='erisSuggestionStyle';css.textContent=`
    .esi-overlay{position:fixed;inset:0;z-index:25000;display:grid;place-items:center;padding:18px;background:#06020b99;backdrop-filter:blur(13px);color:#f7f2ff;box-sizing:border-box;font:14px/1.55 system-ui}.esi-panel{width:min(560px,100%);max-height:88dvh;overflow:auto;border:1px solid #c3a0ef66;border-radius:26px;padding:22px;box-sizing:border-box;background:linear-gradient(145deg,#281d37e8,#130e1fe8);box-shadow:0 24px 90px #0009}.esi-panel header{display:flex;gap:16px;align-items:center;justify-content:space-between;margin-bottom:16px}.esi-panel h2{font-size:21px;margin:0}.esi-panel button{border:1px solid #ffffff25;border-radius:12px;background:#ffffff0d;color:#fff;padding:11px 15px;font:inherit;cursor:pointer}.esi-panel button[data-close]{width:42px;height:42px;padding:0;font-size:26px;flex:none}.esi-panel button.primary{background:linear-gradient(135deg,#8554d5,#ab5aa4);border:0;font-weight:750}.esi-panel button:disabled{opacity:.45;cursor:default}.esi-panel textarea{width:100%;box-sizing:border-box;min-height:180px;resize:vertical;margin:9px 0;padding:14px;border:1px solid #ffffff26;border-radius:15px;background:#100a1bcc;color:#fff;font:inherit}.esi-panel label{display:block;color:#e5d7f4}.esi-count{color:#c5b3d9;text-align:right;font-size:12px;margin-bottom:14px}.esi-actions{display:flex;gap:9px;flex-wrap:wrap}.esi-actions button{flex:1}.esi-error{color:#ffadc1;min-height:20px;margin-top:12px}.esi-list{display:grid;gap:10px}.esi-list>button{text-align:left;padding:15px}.esi-list small{display:block;color:#c5b3d9;margin-top:5px}.esi-message{white-space:pre-wrap;overflow-wrap:anywhere;border:1px solid #ffffff18;border-radius:15px;background:#ffffff07;padding:16px;margin:14px 0;max-height:40dvh;overflow:auto;overscroll-behavior:contain}.esi-person{padding:12px;border-radius:14px;background:#ffffff07;overflow-wrap:anywhere}.esi-note{color:#c5b3d9;font-size:12px}.esi-overlay[data-review]{z-index:26000}.esi-overlay[data-review] .esi-panel{display:flex;flex-direction:column;overflow:hidden}.esi-overlay[data-review] [data-body]{min-height:0;overflow:auto}@media(max-width:520px){.esi-overlay{padding:10px}.esi-panel{padding:18px;border-radius:22px}.esi-panel h2{font-size:19px}}
  `;document.head.append(css);}
  function close(overlay){if(overlay?.hasAttribute('data-review'))return;overlay?.remove();}
  function popup(title,{reviewing=false,onClose}={}){styles();const overlay=document.createElement('div');overlay.className='esi-overlay';if(reviewing)overlay.dataset.review='';overlay.innerHTML='<section class="esi-panel" role="dialog" aria-modal="true" aria-label="'+escape(title)+'"><header><h2>'+escape(title)+'</h2>'+(reviewing?'':'<button type="button" data-close aria-label="Kapat">×</button>')+'</header><div data-body></div></section>';if(!reviewing){const dismiss=()=>onClose?onClose():close(overlay);overlay.querySelector('[data-close]').onclick=dismiss;overlay.onclick=e=>{if(e.target===overlay)dismiss();};overlay.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();dismiss();}};}document.body.append(overlay);return overlay;}
  function notify(message){const overlay=popup('ErisChat Yönetimi');const text=document.createElement('p');text.textContent=message;overlay.querySelector('[data-body]').append(text);overlay.querySelector('[data-close]').focus();return overlay;}
  async function action(button,fn,error){button.disabled=true;try{await fn();}catch(e){if(error)error.textContent=e.message;else window.toast?.(e.message);}finally{if(button.isConnected)button.disabled=false;}}
  function open(){if(locked)return;if(!token()){window.toast?.('Gelişim fikri göndermek için giriş yap.');return;}const overlay=popup('Gelişim Fikri');overlay.querySelector('[data-body]').innerHTML='<form><label for="esiIdeaText">Gelişim Konusu</label><textarea id="esiIdeaText" name="message" required maxlength="1000" placeholder="ErisChat için gelişim fikrini yaz…"></textarea><div class="esi-count" aria-live="polite">0 / 1000</div><div class="esi-actions"><button type="submit" class="primary">Gönder</button><button type="button" data-mine>Gönderdiğim fikirler</button></div><div class="esi-error" role="alert"></div></form>';const form=overlay.querySelector('form'),text=form.elements.message;const count=form.querySelector('.esi-count');text.oninput=()=>{count.textContent=text.value.length+' / 1000';};form.querySelector('[data-mine]').onclick=()=>{close(overlay);mine().catch(e=>window.toast?.(e.message));};form.onsubmit=e=>{e.preventDefault();const message=text.value.trim();if(!message){form.querySelector('.esi-error').textContent='Gelişim konusunu yaz.';return;}action(form.querySelector('[type=submit]'),async()=>{await req('/suggestions',{method:'POST',body:JSON.stringify({message})});close(overlay);notify('Gelişim fikri verdiğiniz ve gerekli zamanınızı ayırdığınız için ErisChat yönetimi olarak size teşekkür ederiz.');},form.querySelector('.esi-error'));};text.focus();}
  async function mine(){const rows=await req('/suggestions/mine');if(locked)return;const overlay=popup('Gönderdiğim Gelişim Fikirleri');const body=overlay.querySelector('[data-body]');body.className='esi-list';if(!rows.length){body.textContent='Henüz gelişim fikri göndermedin.';return;}for(const row of rows){const card=document.createElement('article');card.className='esi-person';const title=document.createElement('b');title.textContent='Öneri No: '+row.number+' · '+(row.read?'Okundu':'İnceleme bekliyor');const message=document.createElement('p');message.className='esi-message';message.textContent=row.message;card.append(title,message);if(row.read&&!row.thanked){const b=document.createElement('button');b.textContent='Teşekkür Et';b.onclick=()=>action(b,async()=>{await req('/suggestions/'+row.id+'/thank',{method:'POST'});b.textContent='Teşekkürün iletildi';b.disabled=true;},null).then(()=>{if(b.textContent==='Teşekkürün iletildi')b.disabled=true;});card.append(b);}body.append(card);}}
  async function openAdmin(before=null){if(locked)return;const result=await req('/suggestions/admin'+(before?'?before='+before:''));if(result.pending_id){await detail(result.pending_id);return;}document.querySelectorAll('.esi-overlay[data-admin-list]').forEach(p=>p.remove());const overlay=popup('Uygulama Geri Bildirimi Paneli');overlay.dataset.adminList='';const body=overlay.querySelector('[data-body]');body.className='esi-list';if(!result.items.length)body.textContent='Henüz gelişim fikri bulunmuyor.';for(const row of result.items){const b=document.createElement('button');b.innerHTML='<b>Öneri No: '+escape(row.number)+'</b><small>'+escape(row.read?'Okundu':'Okunmadı')+' · '+escape(new Date(row.created_at).toLocaleString('tr-TR'))+'</small>';b.onclick=()=>action(b,async()=>{await detail(row.id);close(overlay);});body.append(b);}if(result.next_before){const next=document.createElement('button');next.textContent='Önceki öneriler';next.onclick=()=>action(next,()=>openAdmin(result.next_before));body.append(next);}}
  async function detail(id){if(locked)return;const row=await req('/suggestions/admin/'+id);review={id:row.id,token:token()};locked=true;eventPanel?.remove();eventPanel=null;const overlay=popup('Öneri No: '+row.number,{reviewing:true});overlay.querySelector('[data-body]').innerHTML='<div class="esi-person"><b data-name></b><div data-full></div><div data-id></div></div><h3>Geliştirme fikri</h3><div class="esi-message" tabindex="0" data-message></div><p class="esi-note">Öneriyi inceleyip aşağıdaki butonla onayla.</p><button type="button" class="primary" data-ack disabled>Okudum Anladım</button><div class="esi-error" role="alert"></div>';overlay.querySelector('[data-name]').textContent='Kullanıcı Adı: '+row.nickname;overlay.querySelector('[data-full]').textContent=row.full_name?'Ad Soyad: '+row.full_name:'';overlay.querySelector('[data-id]').textContent='Kullanıcı ID: '+row.user_public_id;const message=overlay.querySelector('[data-message]');message.textContent=row.message;const ack=overlay.querySelector('[data-ack]');const readToEnd=()=>{if(message.scrollTop+message.clientHeight>=message.scrollHeight-5)ack.disabled=false;};message.onscroll=readToEnd;requestAnimationFrame(readToEnd);message.focus();ack.onclick=()=>action(ack,async()=>{await req('/suggestions/admin/'+row.id+'/read',{method:'POST'});locked=false;review=null;overlay.remove();await openAdmin();},overlay.querySelector('.esi-error'));}
  async function poll(){if(window.ErisNotifications?.enabled===false||checking||!token()||document.hidden)return;checking=true;try{const sessionToken=token();if(identity!==sessionToken){identity=sessionToken;locked=false;review=null;eventPanel=null;document.querySelectorAll('.esi-overlay').forEach(p=>p.remove());}if(locked||eventPanel?.isConnected)return;const events=await req('/suggestions/events');if(locked||token()!==sessionToken||!events.length)return;const row=events[0];const acknowledge=async()=>{await req('/suggestions/events/'+row.id+'/seen',{method:'POST'});eventPanel?.remove();eventPanel=null;};const panel=popup('Gelişim Fikri Bildirimi',{onClose:()=>{const b=panel.querySelector('[data-close]');action(b,acknowledge,panel.querySelector('.esi-error'));}});eventPanel=panel;panel.dataset.erischatNotification='';const body=panel.querySelector('[data-body]'),text=document.createElement('p');text.textContent=row.message;body.append(text);if(row.kind==='read'){const b=document.createElement('button');b.className='primary';b.textContent='Teşekkür Et';b.onclick=()=>action(b,async()=>{await req('/suggestions/'+row.suggestion_id+'/thank',{method:'POST'});await acknowledge();},body.querySelector('.esi-error'));body.append(b);}const error=document.createElement('div');error.className='esi-error';error.setAttribute('role','alert');body.append(error);panel.querySelector('[data-close]').focus();}catch{}finally{checking=false;}}
  document.addEventListener('keydown',e=>{if(!locked)return;const overlay=document.querySelector('.esi-overlay[data-review]');if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();return;}if(e.key==='Tab'&&overlay){e.preventDefault();const ack=overlay.querySelector('[data-ack]');(ack.disabled?overlay.querySelector('[data-message]'):ack).focus();}},true);
  document.addEventListener('click',e=>{if(locked&&!e.target.closest('.esi-overlay[data-review]')){e.preventDefault();e.stopImmediatePropagation();}},true);
  window.addEventListener('erischat:auth',()=>{if(!token()||identity!==token()){identity=token();locked=false;review=null;eventPanel=null;document.querySelectorAll('.esi-overlay').forEach(p=>p.remove());}poll();});
  window.addEventListener('load',poll);document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll();});window.ErisApiTransport.poll(poll,15000);
  window.ErisSuggestions={open,openAdmin:()=>openAdmin().catch(e=>window.toast?.(e.message)),isReviewing:()=>locked};
})();
