(function(){
  'use strict';
  const token=()=>window.ErisPlatform?.getAccessToken?.()||localStorage.getItem('erischat.accessToken.v1')||localStorage.getItem('erischat_access_token')||localStorage.getItem('token')||'';
  const base=()=> (window.ERIS_API||'https://erischat-api-production.up.railway.app/v1').replace(/\/$/,'');
  let locked=false,review=null,identity=token(),checking=false,eventPanel=null;
  const req=async(path,options={})=>{const sessionToken=token();const response=await fetch(base()+path,{...options,headers:{'Content-Type':'application/json',Authorization:'Bearer '+sessionToken,...(options.headers||{})}});const result=await response.json().catch(()=>({}));if(sessionToken!==token())throw new Error('Oturum değişti.');if(!response.ok)throw new Error(typeof result.detail==='string'?result.detail:result.detail?.message||'İşlem başarısız');return result;};
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function styles(){if(document.getElementById('erisSuggestionStyle'))return;const css=document.createElement('style');css.id='erisSuggestionStyle';css.textContent=`
    .esi-overlay{position:fixed;inset:0;z-index:25000;display:grid;place-items:center;padding:18px;background:#06020b99;backdrop-filter:blur(13px);color:#f7f2ff;box-sizing:border-box;font:14px/1.55 system-ui}.esi-panel{width:min(560px,100%);max-height:88dvh;overflow:auto;border:1px solid #c3a0ef66;border-radius:26px;padding:22px;box-sizing:border-box;background:linear-gradient(145deg,#281d37e8,#130e1fe8);box-shadow:0 24px 90px #0009}.esi-panel header{display:flex;gap:16px;align-items:center;justify-content:space-between;margin-bottom:16px}.esi-panel h2{font-size:21px;margin:0}.esi-panel button{border:1px solid #ffffff25;border-radius:12px;background:#ffffff0d;color:#fff;padding:11px 15px;font:inherit;cursor:pointer}.esi-panel button[data-close]{width:42px;height:42px;padding:0;font-size:26px;flex:none}.esi-panel button.primary{background:linear-gradient(135deg,#8554d5,#ab5aa4);border:0;font-weight:750}.esi-panel button:disabled{opacity:.45;cursor:default}.esi-panel textarea{width:100%;box-sizing:border-box;min-height:180px;resize:vertical;margin:9px 0;padding:14px;border:1px solid #ffffff26;border-radius:15px;background:#100a1bcc;color:#fff;font:inherit}.esi-panel label{display:block;color:#e5d7f4}.esi-count{color:#c5b3d9;text-align:right;font-size:12px;margin-bottom:14px}.esi-actions{display:flex;gap:9px;flex-wrap:wrap}.esi-actions button{flex:1}.esi-error{color:#ffadc1;min-height:20px;margin-top:12px}.esi-list{display:grid;gap:10px}.esi-list>button{text-align:left;padding:15px}.esi-list small{display:block;color:#c5b3d9;margin-top:5px}.esi-message{white-space:pre-wrap;overflow-wrap:anywhere;border:1px solid #ffffff18;border-radius:15px;background:#ffffff07;padding:16px;margin:14px 0;max-height:40dvh;overflow:auto;overscroll-behavior:contain}.esi-person{padding:12px;border-radius:14px;background:#ffffff07;overflow-wrap:anywhere}.esi-note{color:#c5b3d9;font-size:12px}.esi-overlay[data-review]{z-index:26000}.esi-overlay[data-review] .esi-panel{display:flex;flex-direction:column;overflow:hidden}.esi-overlay[data-review] [data-body]{min-height:0;overflow:auto}@media(max-width:520px){.esi-overlay{padding:10px}.esi-panel{padding:18px;border-radius:22px}.esi-panel h2{font-size:19px}}
    .esi-overlay[data-user-page]{padding:0;display:block;background:#0c0812;backdrop-filter:none;overflow:auto;overscroll-behavior:contain}.esi-overlay[data-user-page] .esi-panel{width:100%;max-width:720px;margin:0 auto;min-height:100%;max-height:none;overflow:visible;border:0;border-radius:0;box-shadow:none;background:radial-gradient(circle at 20% 0,#5a356a33,transparent 40%),#0c0812;padding:calc(24px + env(safe-area-inset-top)) 20px calc(30px + env(safe-area-inset-bottom))}.esi-overlay[data-user-page] header{padding-bottom:20px;border-bottom:1px solid #aa78cc22;margin-bottom:24px}.esi-overlay[data-user-page] h2{font-size:25px;line-height:1.3}.esi-overlay[data-user-page] button{min-height:44px;font-size:14px;white-space:normal;overflow-wrap:anywhere}.esi-overlay[data-user-page] button[data-close]{min-width:44px}.esi-overlay[data-user-page] textarea{min-height:220px;max-width:100%;font-size:16px;border-radius:20px;background:#191020;line-height:1.6}.esi-overlay[data-user-page] .esi-person{padding:18px;border:1px solid #ad80cf30;border-radius:20px;background:#1d1427}.esi-overlay[data-user-page] .esi-message{max-height:none;overflow:visible;padding:0;background:none;border:0;font-size:14px;line-height:1.7}.esi-overlay[data-user-page] .esi-intro{color:#bca8cf;font-size:14px;line-height:1.7;margin-bottom:22px}.esi-overlay[data-user-page] .esi-state{padding:30px 18px;border:1px dashed #a77bb647;border-radius:20px;text-align:center;font-size:14px}.esi-overlay[data-user-page] button:focus-visible,.esi-overlay[data-user-page] textarea:focus-visible{outline:2px solid #d3a2f1;outline-offset:3px}@media(max-width:360px){.esi-overlay[data-user-page] .esi-panel{padding-left:16px;padding-right:16px}.esi-overlay[data-user-page] h2{font-size:23px}}
  `;document.head.append(css);}
  function close(overlay){if(overlay?.hasAttribute('data-review'))return;overlay?.remove();}
  function popup(title,{reviewing=false,onClose}={}){styles();const overlay=document.createElement('div');overlay.className='esi-overlay';if(reviewing)overlay.dataset.review='';overlay.innerHTML='<section class="esi-panel" role="dialog" aria-modal="true" aria-label="'+escape(title)+'"><header><h2>'+escape(title)+'</h2>'+(reviewing?'':'<button type="button" data-close aria-label="Kapat">×</button>')+'</header><div data-body></div></section>';if(!reviewing){const dismiss=()=>onClose?onClose():close(overlay);overlay.querySelector('[data-close]').onclick=dismiss;overlay.onclick=e=>{if(e.target===overlay)dismiss();};overlay.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();dismiss();}};}document.body.append(overlay);return overlay;}
  function notify(message){const overlay=popup('ErisChat Yönetimi');const text=document.createElement('p');text.textContent=message;overlay.querySelector('[data-body]').append(text);overlay.querySelector('[data-close]').focus();return overlay;}
  async function action(button,fn,error){button.disabled=true;try{await fn();}catch(e){if(error)error.textContent=e.message;else window.toast?.(e.message);}finally{if(button.isConnected)button.disabled=false;}}
  function userPage(title){document.querySelectorAll('.esi-overlay[data-user-page]').forEach(p=>p.remove());const overlay=popup(title);overlay.dataset.userPage='';return overlay;}
  function open(){
    if(locked)return;if(!token()){window.toast?.('Gelişim fikri göndermek için giriş yap.');return}
    const overlay=userPage('Gelişim Fikri'),body=overlay.querySelector('[data-body]');
    body.innerHTML='<p class="esi-intro">ErisChat’i birlikte geliştirelim. İyileştirmek istediğin bir özelliği veya yeni fikrini anlat.</p><form><label for="esiIdeaText">Fikrin</label><textarea id="esiIdeaText" name="message" required maxlength="1000" placeholder="Neyi geliştirebiliriz? Örneğini ve önerini yaz…"></textarea><div class="esi-count" aria-live="polite">0 / 1000</div><div class="esi-actions"><button type="submit" class="primary">Fikrimi gönder</button><button type="button" data-mine>Gönderdiğim fikirler</button></div><div class="esi-error" role="alert"></div></form>';
    const form=body.querySelector('form'),text=form.elements.message,count=form.querySelector('.esi-count'),submit=form.querySelector('[type=submit]'),history=form.querySelector('[data-mine]'),error=form.querySelector('.esi-error');let sending=false;
    text.oninput=()=>count.textContent=text.value.length+' / 1000';history.onclick=()=>mine();
    form.onsubmit=async e=>{
      e.preventDefault();if(sending)return;const message=text.value.trim();if(!message){error.textContent='Fikrini yazdıktan sonra gönderebilirsin.';return}
      sending=true;submit.disabled=history.disabled=text.disabled=true;error.textContent='Gönderiliyor…';
      try{await req('/suggestions',{method:'POST',body:JSON.stringify({message})});if(!overlay.isConnected)return;body.innerHTML='<div class="esi-state"><h3>Fikrin bize ulaştı</h3><p>Gelişim fikrini paylaştığın için teşekkür ederiz. Yönetim incelemesini gönderdiğin fikirler bölümünden takip edebilirsin.</p></div><div class="esi-actions" style="margin-top:20px"><button type="button" data-new>Yeni fikir yaz</button><button type="button" class="primary" data-mine>Gönderdiğim fikirler</button></div>';body.querySelector('[data-new]').onclick=open;body.querySelector('[data-mine]').onclick=()=>mine();}
      catch(e){if(overlay.isConnected){error.textContent=e.message||'Fikrin gönderilemedi. Tekrar dene.';sending=false;submit.disabled=history.disabled=text.disabled=false}}
    };
  }
  async function mine(){
    if(locked||!token())return;const overlay=userPage('Gönderdiğim Fikirler'),body=overlay.querySelector('[data-body]');body.className='esi-list';
    const back=document.createElement('button');back.type='button';back.textContent='← Yeni fikir yaz';back.onclick=open;body.append(back);
    const list=document.createElement('div');list.className='esi-list';list.setAttribute('aria-live','polite');list.textContent='Fikirlerin yükleniyor…';body.append(list);
    async function load(){
      list.textContent='Fikirlerin yükleniyor…';try{const rows=await req('/suggestions/mine');if(!overlay.isConnected||locked)return;list.replaceChildren();if(!rows.length){const empty=document.createElement('div');empty.className='esi-state';empty.textContent='Henüz fikir göndermedin. İlk fikrini paylaşabilirsin.';list.append(empty);return}
        for(const row of rows){const card=document.createElement('article');card.className='esi-person';const title=document.createElement('b');title.textContent='Öneri No: '+row.number+' · '+(row.read?'Okundu':'İnceleme bekliyor');const message=document.createElement('p');message.className='esi-message';message.textContent=row.message;const date=document.createElement('small');const time=new Date(row.created_at);date.textContent=Number.isNaN(time.getTime())?'':time.toLocaleString('tr-TR');card.append(title,date,message);
          if(row.read&&!row.thanked){const feedback=document.createElement('div');feedback.className='esi-error';feedback.setAttribute('role','alert');const b=document.createElement('button');b.type='button';b.textContent='Teşekkür et';b.onclick=()=>action(b,async()=>{await req('/suggestions/'+row.id+'/thank',{method:'POST'});if(!overlay.isConnected)return;b.textContent='Teşekkürün iletildi';b.disabled=true;},feedback).then(()=>{if(b.textContent==='Teşekkürün iletildi')b.disabled=true});card.append(b,feedback)}else if(row.thanked){const note=document.createElement('small');note.textContent='Teşekkürün iletildi';card.append(note)}list.append(card)}
      }catch(e){if(!overlay.isConnected)return;list.textContent=e.message||'Fikirlerin yüklenemedi.';const retry=document.createElement('button');retry.type='button';retry.textContent='Tekrar dene';retry.onclick=load;list.append(retry)}
    }await load();
  }
  async function openAdmin(before=null){if(locked)return;const result=await req('/suggestions/admin'+(before?'?before='+before:''));if(result.pending_id){await detail(result.pending_id);return;}document.querySelectorAll('.esi-overlay[data-admin-list]').forEach(p=>p.remove());const overlay=popup('Uygulama Geri Bildirimi Paneli');overlay.dataset.adminList='';const body=overlay.querySelector('[data-body]');body.className='esi-list';if(!result.items.length)body.textContent='Henüz gelişim fikri bulunmuyor.';for(const row of result.items){const b=document.createElement('button');b.innerHTML='<b>Öneri No: '+escape(row.number)+'</b><small>'+escape(row.read?'Okundu':'Okunmadı')+' · '+escape(new Date(row.created_at).toLocaleString('tr-TR'))+'</small>';b.onclick=()=>action(b,async()=>{await detail(row.id);close(overlay);});body.append(b);}if(result.next_before){const next=document.createElement('button');next.textContent='Önceki öneriler';next.onclick=()=>action(next,()=>openAdmin(result.next_before));body.append(next);}}
  async function detail(id){if(locked)return;const row=await req('/suggestions/admin/'+id);review={id:row.id,token:token()};locked=true;eventPanel?.remove();eventPanel=null;const overlay=popup('Öneri No: '+row.number,{reviewing:true});overlay.querySelector('[data-body]').innerHTML='<div class="esi-person"><b data-name></b><div data-full></div><div data-id></div></div><h3>Geliştirme fikri</h3><div class="esi-message" tabindex="0" data-message></div><p class="esi-note">Öneriyi inceleyip aşağıdaki butonla onayla.</p><button type="button" class="primary" data-ack disabled>Okudum Anladım</button><div class="esi-error" role="alert"></div>';overlay.querySelector('[data-name]').textContent='Kullanıcı Adı: '+row.nickname;overlay.querySelector('[data-full]').textContent=row.full_name?'Ad Soyad: '+row.full_name:'';overlay.querySelector('[data-id]').textContent='Kullanıcı ID: '+row.user_public_id;const message=overlay.querySelector('[data-message]');message.textContent=row.message;const ack=overlay.querySelector('[data-ack]');const readToEnd=()=>{if(message.scrollTop+message.clientHeight>=message.scrollHeight-5)ack.disabled=false;};message.onscroll=readToEnd;requestAnimationFrame(readToEnd);message.focus();ack.onclick=()=>action(ack,async()=>{await req('/suggestions/admin/'+row.id+'/read',{method:'POST'});locked=false;review=null;overlay.remove();await openAdmin();},overlay.querySelector('.esi-error'));}
  async function poll(){if(window.ErisNotifications?.enabled===false||checking||!token()||document.hidden)return;checking=true;try{const sessionToken=token();if(identity!==sessionToken){identity=sessionToken;locked=false;review=null;eventPanel=null;document.querySelectorAll('.esi-overlay').forEach(p=>p.remove());}if(locked||eventPanel?.isConnected)return;const events=await req('/suggestions/events');if(locked||token()!==sessionToken||!events.length)return;const row=events[0];const acknowledge=async()=>{await req('/suggestions/events/'+row.id+'/seen',{method:'POST'});eventPanel?.remove();eventPanel=null;};const panel=popup('Gelişim Fikri Bildirimi',{onClose:()=>{const b=panel.querySelector('[data-close]');action(b,acknowledge,panel.querySelector('.esi-error'));}});eventPanel=panel;panel.dataset.erischatNotification='';const body=panel.querySelector('[data-body]'),text=document.createElement('p');text.textContent=row.message;body.append(text);if(row.kind==='read'){const b=document.createElement('button');b.className='primary';b.textContent='Teşekkür Et';b.onclick=()=>action(b,async()=>{await req('/suggestions/'+row.suggestion_id+'/thank',{method:'POST'});await acknowledge();},body.querySelector('.esi-error'));body.append(b);}const error=document.createElement('div');error.className='esi-error';error.setAttribute('role','alert');body.append(error);panel.querySelector('[data-close]').focus();}catch{}finally{checking=false;}}
  document.addEventListener('keydown',e=>{if(!locked)return;const overlay=document.querySelector('.esi-overlay[data-review]');if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();return;}if(e.key==='Tab'&&overlay){e.preventDefault();const ack=overlay.querySelector('[data-ack]');(ack.disabled?overlay.querySelector('[data-message]'):ack).focus();}},true);
  document.addEventListener('click',e=>{if(locked&&!e.target.closest('.esi-overlay[data-review]')){e.preventDefault();e.stopImmediatePropagation();}},true);
  window.addEventListener('erischat:auth',()=>{if(!token()||identity!==token()){identity=token();locked=false;review=null;eventPanel=null;document.querySelectorAll('.esi-overlay').forEach(p=>p.remove());}poll();});
  window.addEventListener('load',poll);document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll();});window.ErisApiTransport.poll(poll,15000);
  window.ErisSuggestions={open,openAdmin:()=>openAdmin().catch(e=>window.toast?.(e.message)),isReviewing:()=>locked};
})();
