(function(){
  'use strict';
  const api=(window.ERIS_API||'https://erischat-api-production.up.railway.app/v1').replace(/\/$/,'');
  const token=()=>localStorage.getItem('erischat.accessToken.v1')||localStorage.getItem('erischat_access_token')||localStorage.getItem('token')||'';
  const req=async(path,opt={})=>{const r=await fetch(api+path,{...opt,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token(),...(opt.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||'İşlem başarısız');return b};
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function mount(){const root=document.getElementById('supportLiveMount');if(!root||root.dataset.ready)return;root.dataset.ready='1';root.innerHTML='<div class="card" style="padding:16px"><div style="display:flex;align-items:center;justify-content:space-between;gap:10px"><div><b>Destek merkezi</b><small class="muted" style="display:block;margin-top:4px">Talebini takip et, ekibimizle aynı konuşmada yazış.</small></div><button class="primary" id="supportNew">＋ Yeni talep</button></div></div><div id="supportList" class="list" style="margin-top:12px"></div><div id="supportDetail"></div>';
    root.querySelector('#supportNew').onclick=()=>newTicket(root);
  }
  function filesToImages(files){return Promise.all([...files].slice(0,3).map(file=>new Promise((resolve,reject)=>{if(!file.type.startsWith('image/'))return reject(new Error('Yalnızca fotoğraf eklenebilir.'));if(file.size>8*1024*1024)return reject(new Error('Bir fotoğraf en fazla 8 MB olabilir.'));const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{const scale=Math.min(1,1280/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);canvas.toBlob(blob=>{if(!blob)return reject(new Error('Fotoğraf küçültülemedi.'));const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Fotoğraf okunamadı.'));reader.readAsDataURL(blob)},'image/jpeg',.8)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Fotoğraf açılamadı.'))};img.src=url})))}
  async function newTicket(root){const box=root.querySelector('#supportDetail');box.innerHTML='<form class="card" id="supportForm" style="padding:16px;margin-top:12px"><h3 style="margin:0 0 12px">Yeni destek talebi</h3><select name="category" required style="width:100%;padding:11px;border-radius:12px;background:#17121f;color:white;border:1px solid #ffffff22"><option value="account">Hesap</option><option value="payment">Ödeme</option><option value="room">Oda</option><option value="safety">Güvenlik</option><option value="other">Diğer</option></select><input name="subject" required maxlength="120" placeholder="Konu" style="width:100%;margin-top:9px;padding:11px;border-radius:12px;background:#17121f;color:white;border:1px solid #ffffff22"><textarea name="message" required minlength="3" maxlength="4000" placeholder="Sorunu anlat" style="width:100%;min-height:110px;margin-top:9px;padding:11px;border-radius:12px;background:#17121f;color:white;border:1px solid #ffffff22"></textarea><label style="display:block;margin:10px 0;color:#cfc6d8;font-size:11px">Fotoğraf ekle (en fazla 3)<input name="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple style="display:block;margin-top:6px"></label><div class="muted" data-photo-count style="font-size:10px">Fotoğraflar güvenli biçimde küçültülür.</div><button class="primary" type="submit" style="height:40px;margin-top:10px">Talebi gönder</button><button type="button" class="close" data-cancel style="margin-left:8px">İptal</button><div data-error style="color:#ff91ad;font-size:11px;margin-top:8px"></div></form>';const form=box.querySelector('#supportForm');form.querySelector('[name=photos]').onchange=e=>{const fs=e.target.files;form.querySelector('[data-photo-count]').textContent=fs.length>3?'En fazla 3 fotoğraf seçebilirsin.':fs.length+' fotoğraf seçildi.'};form.querySelector('[data-cancel]').onclick=()=>box.replaceChildren();form.onsubmit=async e=>{e.preventDefault();const err=form.querySelector('[data-error]');try{const input=form.querySelector('[name=photos]');if(input.files.length>3)throw new Error('En fazla 3 fotoğraf ekleyebilirsin.');const attachments=await filesToImages(input.files);await req('/support/tickets',{method:'POST',body:JSON.stringify({category:form.category.value,subject:form.subject.value,message:form.message.value,attachments})});await load(root);box.replaceChildren()}catch(x){err.textContent=x.message}}}
  function renderTicket(root,t){const box=root.querySelector('#supportDetail');box.innerHTML='<div class="card" style="padding:15px;margin-top:12px"><button class="link" id="supportBack">← Talepler</button><h3 style="margin:8px 0">#'+t.id+' · '+esc(t.subject)+'</h3><small class="muted">'+esc(t.category)+' · '+esc(t.status)+'</small><div id="supportMessages" class="list" style="margin-top:10px"></div><div id="supportReply"></div></div>';box.querySelector('#supportBack').onclick=()=>{box.replaceChildren();load(root)};const list=box.querySelector('#supportMessages');(t.messages||[]).forEach(m=>{const card=document.createElement('article');card.className='card';card.style.cssText='padding:12px';const who=document.createElement('b');who.textContent=m.sender_role==='USER'?'Sen':'ErisChat Yönetim';const body=document.createElement('p');body.textContent=m.message;body.style.cssText='white-space:pre-wrap;font-size:12px;line-height:1.5';card.append(who,body);(m.attachments||[]).forEach(src=>{const img=document.createElement(src.startsWith('data:video/')?'video':'img');img.src=src;if(img.tagName==='VIDEO'){img.controls=true;img.preload='metadata'}else img.alt='Destek fotoğrafı';img.style.cssText='width:min(100%,220px);max-height:220px;object-fit:cover;border-radius:12px;margin:4px';card.append(img)});list.append(card)});if(!['closed','rejected'].includes(t.status)){const reply=document.createElement('form');reply.innerHTML='<textarea required maxlength="4000" placeholder="Yanıtını yaz" style="width:100%;min-height:76px;padding:10px;border-radius:12px;background:#17121f;color:white;border:1px solid #ffffff22"></textarea><button class="primary" style="height:38px;margin-top:8px">Yanıt gönder</button>';reply.onsubmit=async e=>{e.preventDefault();try{await req('/support/tickets/'+t.id+'/messages',{method:'POST',body:JSON.stringify({message:reply.querySelector('textarea').value})});const fresh=await req('/support/tickets/'+t.id);renderTicket(root,fresh)}catch(err){window.toast?.(err.message)}};box.querySelector('#supportReply').append(reply)}}
  async function load(root=document.getElementById('supportLiveMount')){if(!root)return;mount();const list=root.querySelector('#supportList');if(!token()){list.textContent='Destek taleplerini görmek için giriş yap.';return}list.innerHTML='<div class="card" style="padding:14px">Talepler yükleniyor…</div>';try{const rows=await req('/support/tickets');list.replaceChildren();if(!rows.length){list.innerHTML='<div class="card" style="padding:14px;color:#aaa">Açık talebin bulunmuyor.</div>';return}rows.forEach(t=>{const b=document.createElement('button');b.className='item card';b.innerHTML='<span class="ava">🎫</span><span class="grow"><b>'+esc(t.subject)+'</b><small>#'+t.id+' · '+esc(t.status)+' · '+(t.messages||[]).length+' mesaj</small></span><span>›</span>';b.onclick=async()=>{try{renderTicket(root,await req('/support/tickets/'+t.id))}catch(e){window.toast?.(e.message)}};list.append(b)})}catch(e){list.innerHTML='<div class="card" style="padding:14px;color:#ff91ad">'+esc(e.message)+'</div>'}}
  window.ErisSupport={open(){mount();window.showView?.('support');load()},load};
  window.addEventListener('load',()=>{mount()});
})();
