(function(){
  'use strict';
  const api=()=> (window.ERIS_API||'https://erischat-api-production.up.railway.app/v1').replace(/\/$/,'');
  const token=()=>window.ErisPlatform?.getAccessToken?.()||localStorage.getItem('erischat.accessToken.v1')||localStorage.getItem('erischat_access_token')||localStorage.getItem('token')||'';
  let identity='',role=null,roleAt=0,heartbeatAt=0,current=null,box=null,polling=false,restrictedUntil=0,restrictionBox=null,adminList=false;
  const announced=new Set();
  const req=async(path,opt={})=>{const response=await fetch(api()+path,{...opt,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token(),...(opt.headers||{})}});const result=await response.json().catch(()=>({}));if(!response.ok){if(result.detail?.code==='support_restricted')restrict(result.detail.remaining_seconds);throw new Error(typeof result.detail==='string'?result.detail:result.detail?.message||'İşlem başarısız');}return result;};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const number=id=>'#'+String(id).padStart(4,'0');
  function styles(){if(document.getElementById('supportLiveStyle'))return;const s=document.createElement('style');s.id='supportLiveStyle';s.textContent=`
    .support-window{position:fixed;right:16px;bottom:20px;z-index:22500;width:min(440px,calc(100vw - 32px));max-height:85dvh;overflow:auto;box-sizing:border-box;border:1px solid #c4a2ff66;border-radius:24px;background:#20162de8;backdrop-filter:blur(20px);color:#f7f1ff;box-shadow:0 24px 80px #0009;padding:20px;font:14px/1.5 system-ui}
    .support-window header{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-bottom:12px}.support-window button{border:1px solid #ffffff26;border-radius:12px;background:#ffffff10;color:#fff;padding:10px 14px;cursor:pointer}.support-window button.primary{background:#7e4fce}.support-window button:disabled{opacity:.5;cursor:wait}.support-window textarea,.support-window input,.support-window select{width:100%;box-sizing:border-box;background:#0c0813;color:#fff;border:1px solid #ffffff25;border-radius:12px;padding:11px;margin:6px 0;font:inherit}.support-window textarea{min-height:76px;resize:vertical}.support-window small{display:block;color:#c5b7d3}.support-actions{display:flex;gap:8px;margin-top:14px}.support-actions button{flex:1}.support-message{padding:12px;margin:8px 0;border-radius:15px;background:#ffffff08;overflow-wrap:anywhere}.support-message.own{background:#8150cc30}.support-message p{white-space:pre-wrap;margin:4px 0}.support-message small{text-align:right;font-size:10px}.support-media{width:90px;height:90px;object-fit:cover;border-radius:12px;cursor:pointer;margin:4px}.support-history{max-height:38dvh;overflow:auto;overscroll-behavior:contain}.support-lightbox{position:fixed;inset:0;z-index:24000;display:grid;place-items:center;background:#06030bee;padding:20px}.support-lightbox img,.support-lightbox video{max-width:95vw;max-height:88dvh;object-fit:contain}.support-lightbox button{position:absolute;right:16px;top:16px;background:#261c38;color:#fff;border:1px solid #fff5;border-radius:50%;width:44px;height:44px;font-size:26px}.support-window [data-error]{color:#ffabbf}.support-ticket-list{display:grid;gap:8px}.support-ticket-list button{padding:14px;border-radius:14px;border:1px solid #fff2;background:#21162d;color:#fff;text-align:left}.support-status{padding:12px;border-radius:14px;background:#ffffff07;white-space:pre-wrap}.support-rating-stars{display:flex;gap:6px}.support-rating-stars button{font-size:22px;padding:7px}.support-rating-stars [aria-pressed=true]{color:#ffd96b;background:#ffd96b18}@media(max-width:520px){.support-window{right:8px;bottom:10px;width:calc(100vw - 16px);padding:16px}}
  `;document.head.append(s);}
  function windowBox(title,close){styles();const panel=document.createElement('section');panel.className='support-window';panel.setAttribute('role','dialog');panel.setAttribute('aria-label',title);panel.innerHTML='<header><b>'+esc(title)+'</b><button data-close aria-label="Kapat">×</button></header><div data-body></div>';panel.querySelector('[data-close]').onclick=close||(()=>panel.remove());document.body.append(panel);return panel;}
  function info(text){const panel=windowBox('ErisChat Destek');const p=document.createElement('p');p.textContent=text;panel.querySelector('[data-body]').append(p);return panel;}
  function preview(src){if(!/^data:(image\/(jpeg|png|webp)|video\/(mp4|webm));base64,/.test(src))return;const overlay=document.createElement('div');overlay.className='support-lightbox';const media=document.createElement(src.startsWith('data:video/')?'video':'img');media.src=src;if(media.tagName==='VIDEO')media.controls=true;else media.alt='Destek kanıtı';const close=document.createElement('button');close.textContent='×';close.setAttribute('aria-label','Kanıtı kapat');close.onclick=()=>{if(media.tagName==='VIDEO')media.pause();overlay.remove()};overlay.append(media,close);document.body.append(overlay);}
  function mediaList(target,sources){for(const src of sources||[]){if(!/^data:(image|video)\//.test(src))continue;const item=document.createElement(src.startsWith('data:video/')?'video':'img');item.src=src;item.className='support-media';if(item.tagName==='VIDEO'){item.muted=true;item.preload='metadata';}else item.alt='Destek kanıtı';item.onclick=()=>preview(src);target.append(item);}}
  async function run(button,fn){button.disabled=true;try{await fn();}catch(error){window.toast?.(error.message);}finally{if(button.isConnected)button.disabled=false;}}
  function button(target,label,fn,primary=false){const b=document.createElement('button');b.type='button';b.textContent=label;if(primary)b.className='primary';b.onclick=()=>run(b,fn);target.append(b);return b;}
  function mount(){const root=document.getElementById('supportLiveMount');if(!root||root.dataset.ready==='live3')return;root.dataset.ready='live3';root.innerHTML='<div class="card" style="padding:16px"><b>Destek merkezi</b><p>Talebini ilet, müşteri temsilcinle canlı görüş.</p><button class="primary" data-new>＋ Yeni talep</button></div><div class="support-ticket-list" data-list style="margin-top:12px"></div>';root.querySelector('[data-new]').onclick=newTicket;styles();}
  function snapshot(){
    // This is an in-app visual record; it does not capture the device or other apps.
    const root=document.querySelector('#erisRoomSurface.show')||document.querySelector('.view.show');
    const canvas=document.createElement('canvas');canvas.width=900;canvas.height=900;const ctx=canvas.getContext('2d');ctx.fillStyle='#130e1c';ctx.fillRect(0,0,900,900);ctx.fillStyle='#ceb2ff';ctx.font='bold 24px system-ui';ctx.fillText('ErisChat · Uygulama anlık kaydı',30,48);ctx.font='16px system-ui';ctx.fillText(new Date().toLocaleString('tr-TR'),30,80);ctx.fillStyle='#f7f1ff';ctx.font='18px system-ui';let y=120;const text=(root?.innerText||'Destek merkezi').slice(0,3000);for(const line of text.split(/\n/)){for(let i=0;i<line.length;i+=65){ctx.fillText(line.slice(i,i+65),30,y);y+=25;if(y>860)break;}if(y>860)break;}return canvas.toDataURL('image/jpeg',.75);
  }
  async function attachments(files){const list=[...files];const videos=list.filter(f=>f.type.startsWith('video/'));if(list.length>3||(videos.length&&(videos.length!==1||list.length!==1)))throw new Error('En fazla 3 fotoğraf veya 1 video ekle.');return Promise.all(list.map(file=>new Promise((resolve,reject)=>{if(!['image/jpeg','image/png','image/webp','video/mp4','video/webm'].includes(file.type))return reject(new Error('JPEG, PNG, WebP, MP4 veya WebM seç.'));if(file.size>(file.type.startsWith('video/')?8*1024*1024:1500000))return reject(new Error('Fotoğraf en fazla 1,5 MB; video en fazla 8 MB olabilir.'));const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Dosya okunamadı.'));reader.readAsDataURL(file);})));}
  function newTicket(){const captured=snapshot(),room=window.ErisCurrentRoomId||null;const panel=windowBox('Yeni destek talebi');panel.querySelector('[data-body]').innerHTML='<form><label>Kategori<select name="category"><option value="account">Hesap</option><option value="payment">Ödeme</option><option value="room">Oda</option><option value="safety">Güvenlik / Şikâyet</option><option value="other">Diğer</option></select></label><label>Konu<input name="subject" required maxlength="120"></label><label>Sorunu anlat<textarea name="message" required minlength="3" maxlength="4000"></textarea></label><label>Kanıt: 3 fotoğraf veya 1 video<input type="file" name="evidence" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" multiple></label><button class="primary" type="submit">Talebi gönder</button><p data-error role="alert"></p></form>';const form=panel.querySelector('form');form.onsubmit=async e=>{e.preventDefault();const submit=form.querySelector('button');submit.disabled=true;try{await req('/support/tickets',{method:'POST',body:JSON.stringify({category:form.elements.category.value,subject:form.elements.subject.value,message:form.elements.message.value,attachments:await attachments(form.elements.evidence.files),security_snapshot:captured,context_room_id:room})});panel.remove();await loadList();window.toast?.('Destek talebin iletildi.');}catch(error){form.querySelector('[data-error]').textContent=error.message;}finally{submit.disabled=false;}};}
  async function loadList(){mount();const root=document.getElementById('supportLiveMount');if(!root)return;const list=root.querySelector('[data-list]');if(!token()){list.textContent='Destek için giriş yap.';return;}try{const rows=await req(adminList?'/support/live/inbox':'/support/tickets');list.replaceChildren();if(!rows.length){list.textContent=adminList?'Sana atanmış talep bulunmuyor.':'Henüz destek talebin yok.';return;}for(const t of rows){button(list,t.number+' · '+t.subject+' · '+({pending:'Bekliyor',awaiting_ready:'Hazırlık onayı',active:'Canlı görüşme',closed:'Kapandı'}[t.phase]||t.status),()=>openTicket(t.id,adminList));}}catch(error){list.textContent=error.message;}}
  async function openTicket(id,agent=false){const ticket=await req('/support/live/tickets/'+id);if(box)box.remove();current={id,agent,signature:null,phase:null};box=windowBox('Destek '+number(id),()=>finish());draw(ticket);}
  function draw(t){if(!box||!current||current.id!==t.id)return;const previous=current.phase;current.phase=t.phase;const body=box.querySelector('[data-body]');let history=body.querySelector('[data-history]');if(!history){body.innerHTML='<div data-meta></div><div class="support-history" data-history></div><div data-controls></div>';history=body.querySelector('[data-history]');}const meta=body.querySelector('[data-meta]');meta.textContent=current.agent?t.customer_name+' · '+t.customer_id+' · '+t.subject:t.subject+' · Müşteri Temsilcisi';
    const nearBottom=history.scrollHeight-history.scrollTop-history.clientHeight<60;history.replaceChildren();for(const m of t.messages||[]){const own=current.agent?m.sender_role!=='USER':m.sender_role==='USER';const card=document.createElement('article');card.className='support-message'+(own?' own':'');const who=document.createElement('b');who.textContent=m.sender_role==='USER'?(current.agent?t.customer_name:'Sen'):'Müşteri Temsilcisi';const p=document.createElement('p');p.textContent=m.message;const when=document.createElement('small');when.textContent=new Date(m.created_at).toLocaleString('tr-TR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})+(own&&m.id?' · '+(m.read?'✓✓ Okundu':'✓ Gönderildi'):'');card.append(who,p);mediaList(card,m.attachments);history.append(card);}if(current.agent&&t.snapshot){const evidence=document.createElement('div');evidence.textContent='Anlık uygulama kaydı';mediaList(evidence,[t.snapshot]);history.append(evidence);}if(current.agent&&t.server_context){const details=document.createElement('details');const label=document.createElement('summary');label.textContent='Sunucu olay kaydı';const pre=document.createElement('pre');pre.style.cssText='white-space:pre-wrap;font-size:11px';pre.textContent=JSON.stringify(t.server_context,null,2);details.append(label,pre);history.append(details);}if(nearBottom)history.scrollTop=history.scrollHeight;
    const controls=body.querySelector('[data-controls]');if(controls.dataset.phase!==t.phase){controls.dataset.phase=t.phase;controls.replaceChildren();if(t.phase==='pending'){if(current.agent){const reason=document.createElement('p');reason.textContent=t.message;controls.append(reason);const actions=document.createElement('div');actions.className='support-actions';button(actions,'Kabul et',async()=>{const fresh=await req('/support/live/tickets/'+t.id+'/accept',{method:'POST'});draw(fresh);},true);button(actions,'Müsait değilim',async()=>{const r=await req('/support/live/tickets/'+t.id+'/decline',{method:'POST'});dismiss();if(r.restriction_seconds){restrict(r.restriction_seconds);await window.closeRealRoom?.();}else info('1 dakika boyunca yeni talep atanmayacak.');});controls.append(actions);}else controls.textContent='Talebin müşteri temsilcisine yönlendiriliyor.';}
      else if(t.phase==='awaiting_ready'){if(current.agent)controls.textContent='Müşterinin Hazırım onayı bekleniyor.';else{const text=document.createElement('p');text.textContent='Destek talebiniz yetkili müşteri temsilciniz tarafından kabul edilmiştir. Hazırlanan canlı desteğe bağlanacaksınız.';controls.append(text);const actions=document.createElement('div');actions.className='support-actions';button(actions,'Hazırım',async()=>draw(await req('/support/live/tickets/'+t.id+'/ready',{method:'POST',body:JSON.stringify({ready:true})})),true);button(actions,'Hazır değilim',async()=>draw(await req('/support/live/tickets/'+t.id+'/ready',{method:'POST',body:JSON.stringify({ready:false})})));controls.append(actions);}}
      else if(t.phase==='active'){const form=document.createElement('form');form.innerHTML='<textarea name="message" maxlength="4000" placeholder="Mesajını yaz" required></textarea>'+(current.agent?'':'<label>＋ Fotoğraf / video<input type="file" name="evidence" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" multiple></label>')+'<button class="primary" type="submit">Gönder</button><p data-error role="alert"></p>';form.onsubmit=async e=>{e.preventDefault();const submit=form.querySelector('button');submit.disabled=true;try{const files=current.agent?[]:await attachments(form.elements.evidence.files);const fresh=await req(current.agent?'/admin/tickets/'+t.id+'/message':'/support/tickets/'+t.id+'/messages',{method:'POST',body:JSON.stringify({message:form.elements.message.value,attachments:files})});form.reset();draw(fresh);}catch(error){form.querySelector('[data-error]').textContent=error.message;}finally{submit.disabled=false;}};controls.append(form);}
    }
    if(t.phase==='closed'){
      if(previous&&previous!=='closed'){
        const wasAgent=current.agent;dismiss();
        if(wasAgent)info(t.closed_by==='not_ready'?'Müşteriniz müsait olmadığından dolayı destek talebi sonlandırılmıştır. Keyifli çalışmalar dileriz.':'Müşterimiz ile ilgilendiğiniz zaman ayırdığınız için teşekkür ederiz. İyi çalışmalar.');
        else {const notice=t.closed_by==='agent'?'ErisChat ailesi olarak bizimle aranızda olduğunuzdan çok memnunuz '+t.customer_name+'. Herhangi bir talebiniz olduğunda müşteri temsilcilerimiz ile iletişime geçebilirsiniz.':'';if(!t.rated)rating(t.id,notice);else if(notice)info(notice);}
      }else if(!current.agent&&!t.rated&&!controls.querySelector('[data-rate]')){button(controls,'Temsilciyi değerlendir',async()=>rating(t.id)).dataset.rate='';}
      return;
    }
    if(t.phase==='active'&&!document.hidden){const max=Math.max(0,...(t.messages||[]).map(m=>m.id));req('/support/live/tickets/'+t.id+'/read',{method:'POST',body:JSON.stringify({message_id:max})}).catch(()=>{});}
  }
  function dismiss(){box?.remove();box=null;current=null;}
  async function finish(){if(!current)return;if(current.phase==='closed'||(current.agent&&current.phase==='pending')){dismiss();return;}const id=current.id;if(!confirm('Destek talebini sonlandırmak istiyor musun?'))return;const t=await req('/support/live/tickets/'+id+'/close',{method:'POST'});draw(t);await loadList();}
  function rating(id,notice=""){if(document.querySelector('[data-rating-id="'+id+'"]'))return;const panel=windowBox('Müşteri temsilcimizi değerlendirir misiniz?');panel.dataset.ratingId=id;const body=panel.querySelector('[data-body]');body.innerHTML=(notice?'<p>'+esc(notice)+'</p>':'')+'<p>Değerlendirmeniz bizim için önemlidir. İstersen bu pencereyi kapatabilirsin.</p><div class="support-rating-stars"></div><textarea maxlength="1000" placeholder="Yorumun (isteğe bağlı)"></textarea><div class="support-actions"></div>';let score=0;const stars=body.querySelector('.support-rating-stars');for(let n=1;n<=5;n++){const b=document.createElement('button');b.textContent='★';b.setAttribute('aria-label',n+' yıldız');b.setAttribute('aria-pressed','false');b.onclick=()=>{score=n;[...stars.children].forEach((s,i)=>s.setAttribute('aria-pressed',String(i<n)));};stars.append(b);}button(body.querySelector('.support-actions'),'Gönder',async()=>{if(!score)throw new Error('1–5 arasında puan seç.');await req('/support/live/tickets/'+id+'/rating',{method:'POST',body:JSON.stringify({score,comment:body.querySelector('textarea').value})});panel.remove();window.toast?.('Değerlendirmen kaydedildi.');},true);}
  function restrict(seconds){restrictedUntil=Math.max(restrictedUntil,Date.now()+seconds*1000);showRestriction();}
  function showRestriction(){const left=Math.max(0,Math.ceil((restrictedUntil-Date.now())/1000));if(!left)return;if(restrictionBox?.isConnected)return;restrictionBox=windowBox('İşlevler geçici olarak kısıtlandı',()=>{restrictionBox.remove();restrictionBox=null;});restrictionBox.dataset.restriction='';restrictionBox.querySelector('[data-body]').className='support-status';updateRestriction();}
  function updateRestriction(){const left=Math.max(0,Math.ceil((restrictedUntil-Date.now())/1000));if(!left){restrictionBox?.remove();restrictionBox=null;return;}if(restrictionBox?.isConnected)restrictionBox.querySelector('[data-body]').textContent='Müşteri taleplerine gereken özeni göstermediğiniz için normal işlevleriniz (Kalan Süre: '+left+' saniye) boyunca yasaklanmıştır.';}
  async function pulse(){if(polling||!token()||document.hidden)return;polling=true;try{if(identity!==token()){identity=token();role=null;roleAt=0;heartbeatAt=0;announced.clear();restrictedUntil=0;restrictionBox?.remove();dismiss();document.querySelectorAll('.support-window,.support-lightbox').forEach(p=>p.remove());adminList=false;}if(Date.now()-roleAt>60000){roleAt=Date.now();try{role=(await req('/admin/me')).role;}catch{role=null;}}if(role&&Date.now()-heartbeatAt>5000){heartbeatAt=Date.now();const presence=await req('/support/live/presence',{method:'POST',body:'{"active":true}'});if(presence.restriction_seconds)restrictedUntil=Date.now()+presence.restriction_seconds*1000;}
      const own=await req('/support/tickets');const assigned=role?await req('/support/live/inbox'):[];
      if(current){const state=await req('/support/live/tickets/'+current.id+'/state');const signature=JSON.stringify(state);if(signature!==current.signature){current.signature=signature;draw(await req('/support/live/tickets/'+current.id));}}
      if(!current&&!document.querySelector('[data-rating-id]')){const incoming=assigned.find(t=>t.phase==='pending'&&!announced.has('offer-'+t.id));if(incoming){announced.add('offer-'+incoming.id);await openTicket(incoming.id,true);}else{const ongoing=assigned.find(t=>['awaiting_ready','active'].includes(t.phase)&&!announced.has('agent-'+t.id));if(ongoing){announced.add('agent-'+ongoing.id);await openTicket(ongoing.id,true);}const next=!current&&own.find(t=>['awaiting_ready','active'].includes(t.phase)&&!announced.has(t.phase+'-'+t.id));if(next){announced.add(next.phase+'-'+next.id);await openTicket(next.id,false);}}}
    }catch(error){if(current&&error.message==='Bu talep size atanmadı')dismiss();}finally{polling=false;}}
  document.addEventListener('click',e=>{if(Date.now()>=restrictedUntil||e.target.closest('.support-window,.support-lightbox')||e.target.closest('.eris-admin-overlay,.eris-admin-menu'))return;const action=e.target.closest('button,a,[onclick]');if(!action)return;e.preventDefault();e.stopImmediatePropagation();showRestriction();},true);
  document.addEventListener('visibilitychange',()=>{if(role&&token())req('/support/live/presence',{method:'POST',body:JSON.stringify({active:!document.hidden})}).catch(()=>{});if(!document.hidden)pulse();});
  window.addEventListener('erischat:auth',()=>{if(!token()){identity='';role=null;announced.clear();restrictedUntil=0;restrictionBox?.remove();dismiss();document.querySelectorAll('.support-window,.support-lightbox').forEach(p=>p.remove());adminList=false;loadList();}else pulse();});
  window.ErisSupport={open(){adminList=false;mount();window.showView?.('support');loadList();},openAdmin(){adminList=true;mount();window.showView?.('support');loadList();pulse();},load:loadList,restrict};
  window.addEventListener('load',()=>{mount();pulse();});setInterval(pulse,2500);setInterval(updateRestriction,1000);
})();
