const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/tmp/chromium-eris',args:['--no-sandbox']});try{const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.setDefaultTimeout(5000);p.on('pageerror',e=>errors.push(e.message));const dir=path.resolve(__dirname,'../frontend');await p.route('https://eris.test/**',r=>{const f=path.join(dir,new URL(r.request().url()).pathname);if(fs.existsSync(f)&&fs.statSync(f).isFile())return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.json')?'application/json':f.endsWith('.png')?'image/png':f.endsWith('.wav')?'audio/wav':'text/plain'});return r.fulfill({body:'<html><body></body></html>',contentType:'text/html'})});await p.goto('https://eris.test');
await p.evaluate(()=>{document.documentElement.className='eris-adaptive';document.body.innerHTML='<main class="app"></main><section id="erisRoomSurface" class="show room-layout-v6 room-screen-fit"><div class="eris-room-quick-actions"><button id="erisRoomGift">Hediye</button></div><div class="eris-room-compose"><button id="erisRoomGiftInline">Hediye gönder</button></div></section>';document.querySelector('#erisRoomSurface').style.cssText='position:fixed;inset:0;z-index:30000;background:#211a30';window.ErisCurrentRoomId='fixture';window.calls=[];window.ErisPlatform={getMe:async()=>({lidya:100000}),api:async(u,o)=>{if(o){calls.push(o);return {}}return [{user_id:7,nickname:'Test'}]},messageGifts:async()=>[{id:1,gift_key:'1',name:'Zeytin Dalı',price:1,unit_price:1,image_url:'/gift-effects/items/001.png'}]};window.ErisRoomGift={catalog:async()=>[{id:1,gift_key:'1',name:'Zeytin Dalı',price:1,image_url:'/gift-effects/items/001.png'}]};window.ErisApiTransport={poll:()=>{}};});
for(const file of ['room-screen-fit.css','room-menu-polish.css','agora-gifts.css','messages-polish.css','gift-stage.css'])await p.addStyleTag({path:path.join(dir,file)});
await p.addScriptTag({path:path.join(dir,'room-gift-ui-live.js')});await p.addScriptTag({path:path.join(dir,'room-hardening.js')});await p.addScriptTag({path:path.join(dir,'room-modern-controls.js')});await p.evaluate(()=>dispatchEvent(new CustomEvent('erischat:room-opened')));
for(const id of ['erisRoomGift','erisRoomGiftInline']){await p.locator('#'+id).click();await p.waitForSelector('.egp-gift');for(const [width,height] of [[320,640],[390,844],[844,390]]){await p.setViewportSize({width,height});assert.equal(await p.locator('#erischatGiftPanel').evaluate(el=>{const r=el.getBoundingClientRect();return r.left>=0&&r.top>=0&&r.right<=innerWidth&&r.bottom<=innerHeight}),true,'picker inside viewport');}await p.setViewportSize({width:390,height:844});assert.equal(await p.locator('#erischatGiftPanel').evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+30))}),true,'room panel must be clickable above shade');await p.locator('.egp-close').click();assert.equal(await p.locator('#erisGiftPickerShade').evaluate(el=>el.hidden),true)}
await p.addScriptTag({path:path.join(dir,'agora-gifts.js')});await p.addScriptTag({path:path.join(dir,'gift-stage.js')});await p.locator('#erisRoomGift').click();await p.waitForSelector('.egp-gift');await p.locator('[data-preview="1"]').click();await p.waitForSelector('.eris-gift-cinema[data-mode="preview"]');
async function assertPreview(){assert.equal(await p.locator('.eris-gift-cinema').evaluate(el=>{const z=Number(getComputedStyle(el).zIndex),picker=document.querySelector('#erischatGiftPanel.show'),dm=document.querySelector('.dm-gift-sheet');return (!picker||z>Number(getComputedStyle(picker).zIndex))&&(!dm||z>Number(getComputedStyle(dm).zIndex))}),true);assert.equal(await p.locator('.gift-cinema-tools [data-skip]').evaluate(el=>{const r=el.getBoundingClientRect();return el===document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)}),true);assert.equal(await p.evaluate(()=>calls.length),0)}
await assertPreview();await p.screenshot({path:process.env.GIFT_LAYER_SCREENSHOT||'/tmp/gift-layer-room.png'});await p.locator('.gift-cinema-tools [data-skip]').click();assert.equal(await p.locator('#erischatGiftPanel').isVisible(),true);await p.locator('.egp-close').click();
await p.evaluate(()=>{document.querySelector('#erisRoomSurface').remove();document.body.classList.remove('eris-room-screen-active')});await p.addScriptTag({content:fs.readFileSync(path.join(dir,'dm-live.js'),'utf8').replace('let activeConversationId = null;','let activeConversationId = "fixture";')});await p.evaluate(()=>ErisChatDM.openGiftSheet());await p.waitForSelector('.dm-gift-sheet .gift-preview-button');await p.locator('.dm-gift-sheet .gift-preview-button').first().click();await p.waitForSelector('.eris-gift-cinema[data-mode="preview"]');await assertPreview();await p.locator('.gift-cinema-tools [data-skip]').click();assert.equal(await p.locator('.dm-gift-sheet').isVisible(),true);
assert.deepEqual(errors,[]);console.log('PASS: actual room top/inline controls; late hardening CSS; clickable picker above shade; actual room and DM previews above dialogs; close returns to picker; no preview POST.');}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
