const {chromium}=require('playwright'),fs=require('fs'),assert=require('node:assert/strict');
(async()=>{
const b=await chromium.launch({executablePath:process.env.ERIS_CHROMIUM_EXECUTABLE,args:['--no-sandbox'],headless:true});const p=await b.newPage({viewport:{width:393,height:760}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
const html=fs.readFileSync('frontend/erischat-main.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<link\b[^>]*>/gi,'');await p.route('https://eris.test/**',r=>r.fulfill({contentType:'text/html',body:html}));await p.goto('https://eris.test/');
await p.evaluate(()=>{window.rows=[{id:'1',user_id:'u',nickname:'Kaan',caption:'Bir güzel anı '.repeat(20),created_at:'2026-10-10T09:00:00Z',audience:'public',is_mine:true}];window.fail=false;window.ErisAuth={getMe:async()=>({id:'u'})};window.ErisPlatform={myPosts:async()=>{if(fail)throw Error('Bağlantı kurulamadı');return rows},api:async()=>({})};window.ErisSocialMedia={icon:()=>'<svg viewBox="0 0 24 24"><path d="M4 4h16v16H4Z"/></svg>'};});
for(const name of ['social-feed-live.js','profile-hub.js'])await p.addScriptTag({content:fs.readFileSync('frontend/'+name,'utf8')});await p.evaluate(()=>ErisProfileHub.show('posts'));await p.waitForSelector('.eph-posts-list .ec-social-post');await p.click('.eph-posts-list [data-options-toggle]');assert.equal(await p.locator('.eph-posts-list [data-edit] span').innerText(),'Gönderiyi düzenle');
for(const width of [320,393,768]){await p.setViewportSize({width,height:760});const rects=await p.locator('.eph-posts-list .ec-social-post,.eph-posts-list [data-post-options] button').evaluateAll(xs=>xs.map(x=>({l:x.getBoundingClientRect().left,r:x.getBoundingClientRect().right})));assert(rects.every(x=>x.l>=0&&x.r<=width+1),JSON.stringify(rects));}
await p.evaluate(async()=>{fail=true;await ErisSocialFeed.loadMine(document.querySelector('[data-posts-list]'))});assert.equal(await p.locator('.eph-posts-error button').innerText(),'Tekrar dene');await p.evaluate(()=>{fail=false;rows=[]});await p.click('.eph-posts-error button');await p.waitForSelector('.ec-empty-art');assert.equal(await p.locator('[data-posts-list]').getAttribute('aria-busy'),'false');assert.deepEqual(errors,[]);console.log('PASS: owner actions, 3 widths, failure/retry, empty state');await b.close();
})();
