const {chromium}=require('playwright'),fs=require('fs'),assert=require('node:assert/strict');
(async()=>{
 const b=await chromium.launch({executablePath:process.env.ERIS_CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader'],headless:true});const p=await b.newPage({viewport:{width:393,height:760}});
 const html=fs.readFileSync('frontend/erischat-main.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<link\b[^>]*>/gi,'');await p.route('https://eris.test/**',r=>r.fulfill({contentType:'text/html',body:html}));await p.goto('https://eris.test/');
 for(const name of ['home-part1.css','device-layout.css','app-shell.css'])if(fs.existsSync('frontend/'+name))await p.addStyleTag({content:fs.readFileSync('frontend/'+name,'utf8')});
 await p.evaluate(()=>{window.me={nickname:'Kaan',public_id:'1234567890',first_name:'Kaan',last_name:'Altay',bio:'Merhaba',lidya:500};window.updates=[];window.renames=[];window.ErisAuth={getMe:async()=>me};window.ErisProfile={update:async data=>{updates.push(data);return {...me,...data}},refresh(){}};window.ErisPlatform={api:async(path,opts)=>{renames.push({path,body:JSON.parse(opts.body)});return {...me,nickname:JSON.parse(opts.body).nickname,lidya:350}}};});
 await p.addScriptTag({content:fs.readFileSync('frontend/profile-hub.js','utf8')});await p.evaluate(()=>ErisProfileHub.show('info'));await p.waitForSelector('.eph-info-form');assert.equal(await p.locator('[data-save]').isDisabled(),true);await p.fill('[data-first]','Yeni');await p.click('[data-save]');assert.equal(await p.evaluate(()=>updates.length),1);assert.equal(await p.locator('[data-save]').isDisabled(),true);
 await p.fill('[data-nickname]','YeniKaan');assert.equal(await p.locator('[data-rename]').isDisabled(),true);await p.check('[data-consent]');await p.click('[data-rename]');assert.deepEqual(await p.evaluate(()=>renames),[{path:'/me/nickname',body:{nickname:'YeniKaan'}}]);assert.equal(await p.locator('[data-rename]').isDisabled(),true);assert.equal(await p.locator('.eph-info-summary [data-name]').innerText(),'YeniKaan');
 for(const width of [320,393,768]){await p.setViewportSize({width,height:760});const items=await p.locator('.eph-info-form input,.eph-info-form textarea,.eph-rename-form input:not([type=checkbox]),[data-rename]').evaluateAll(xs=>xs.map(x=>({left:x.getBoundingClientRect().left,right:x.getBoundingClientRect().right})));assert(items.every(x=>x.left>=0&&x.right<=width+1),JSON.stringify(items));}
 await p.setViewportSize({width:393,height:760});if(process.env.ERIS_TEST_SCREENSHOTS)await p.screenshot({path:'profile-info-after.png'});console.log('PASS: saving, fee consent, rename endpoint, 3 viewport widths');await b.close();
})();
