const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});try{
const page=await browser.newPage({viewport:{width:390,height:844}}),dir=path.resolve(__dirname,'../frontend'),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('https://eris.test/**',r=>{const f=path.join(dir,new URL(r.request().url()).pathname);return r.fulfill({body:fs.existsSync(f)&&fs.statSync(f).isFile()?fs.readFileSync(f):'<html><head></head><body></body></html>',contentType:f.endsWith('.png')?'image/png':'text/html'})});await page.goto('https://eris.test/');
const catalog=JSON.parse(fs.readFileSync(path.join(__dirname,'reward-fixture.json')));await page.evaluate(items=>{window.ErisApiTransport={poll:()=>{}};window.rewardItems=items;window.requests=[];window.ErisAuth={user:{id:1,nickname:'Kaan',avatar:'👤'}};window.ErisPlatform={api:async(url,options)=>{if(options){requests.push(JSON.parse(options.body));await new Promise(r=>setTimeout(r,70));return {}}return {level:6,items:rewardItems}}}},catalog);
const html=fs.readFileSync(path.join(dir,'erischat-main.html'),'utf8');for(const m of html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g))await page.addStyleTag({content:m[1]});for(const f of ['relationship-modern.css','relationship-rewards.css'])await page.addStyleTag({path:path.join(dir,f)});await page.addScriptTag({path:path.join(dir,'relationship-live.js')});
await page.evaluate(()=>ErisRelationship.showRewards());await page.waitForSelector('.rel-reward-card');assert.equal(await page.locator('.rel-reward-card').count(),26);
for(const [width,height] of [[320,640],[390,844],[768,1024],[844,390]]){await page.setViewportSize({width,height});assert.ok(await page.locator('.rel-body').evaluate(e=>e.scrollWidth<=e.clientWidth+1));assert.ok(await page.locator('.rel-reward-card').evaluateAll(ns=>ns.every(e=>e.scrollWidth<=e.clientWidth+1)));assert.ok(await page.locator('.rel-reward-filters button').evaluateAll(ns=>ns.every(e=>e.scrollWidth<=e.clientWidth+1)))}
await page.setViewportSize({width:390,height:844});for(let n=1;n<=12;n++){await page.getByLabel('Ödül seviyesi').selectOption(String(n));assert.equal(await page.locator('.rel-reward-card:not([data-reward-type="ring"])').count(),2)}await page.getByLabel('Ödül seviyesi').selectOption('0');await page.getByRole('button',{name:'Kilitli',exact:true}).click();assert.equal(await page.locator('.rel-reward-card').count(),13);assert.equal(await page.locator('.rel-reward-card .rel-primary').count(),0);await page.getByRole('button',{name:'Kazanılanlar',exact:true}).click();assert.equal(await page.locator('.rel-reward-card').count(),13);
await page.locator('[data-reward-type="frame"] .rel-reward-preview').first().click();await page.waitForSelector('.rel-frame-demo-avatar');await page.locator('.rel-overlay').last().locator('.rel-close').click();await page.locator('[data-reward-type="bubble"] .rel-reward-preview').first().click();assert.equal(await page.locator('.rel-reward-bubble-demo').count(),1);await page.locator('.rel-overlay').last().locator('.rel-close').click();await page.screenshot({path:'/tmp/reward-menu.png'});
await page.locator('[data-reward-type="frame"] .rel-primary').first().evaluate(e=>{e.click();e.click()});await page.waitForFunction(()=>requests.length===1);assert.equal(await page.evaluate(()=>requests[0].kind),'frame');assert.match(await page.evaluate(()=>requests[0].asset_key),/cerceve-male-l2/);assert.deepEqual(errors,[]);console.log('PASS: 12 levels, two personal rewards, locked/owned filters, four viewport widths, frame/bubble previews, equip and repeat guard.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
