const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});try{
const page=await browser.newPage({viewport:{width:390,height:844}}),dir=path.resolve(__dirname,'../frontend'),errors=[];page.setDefaultTimeout(5000);page.on('pageerror',e=>errors.push(e.message));
await page.route('https://eris.test/**',route=>{const file=path.join(dir,new URL(route.request().url()).pathname);if(fs.existsSync(file)&&fs.statSync(file).isFile())return route.fulfill({body:fs.readFileSync(file),contentType:file.endsWith('.png')?'image/png':'text/plain'});return route.fulfill({body:'<!doctype html><html><head></head><body></body></html>',contentType:'text/html'})});await page.goto('https://eris.test/');
await page.evaluate(()=>{window.house={id:'h1',level:4,days:10,is_owner:true,male:{id:1,nickname:'Kaan'},female:{id:2,nickname:'Filiz'},ring:'copper-1',owned_rings:[{key:'copper-1',source:'purchased',asset:'./relationship-assets/copper-1.png'},{key:'silver-2',source:'purchased',asset:'./relationship-assets/silver-2.png'},{key:'level-1',source:'level',asset:'./relationship-assets/rewards/ring-1.png'}]};window.requests=[];window.fail=false;window.ErisApiTransport={poll:()=>{}};window.ErisPlatform={api:async(url,options)=>{if(options){requests.push({url,body:JSON.parse(options.body)});await new Promise(r=>setTimeout(r,80));if(fail)throw Error('Bakiye yetersiz');return {}}if(url==='/relationship/catalog')return {rings:['copper','silver','gold'].flatMap((category)=>Array.from({length:20},(_,i)=>({key:category+'-'+(i+1),category,price:{copper:1200,silver:2100,gold:2800}[category],asset:'./relationship-assets/'+category+'-'+(i+1)+'.png'})))};if(url==='/relationship/me')return {active:house,requests:[]};return {}}}});
const html=fs.readFileSync(path.join(dir,'erischat-main.html'),'utf8');for(const match of html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g))await page.addStyleTag({content:match[1]});
await page.addStyleTag({path:path.join(dir,'relationship-modern.css')});await page.addStyleTag({path:path.join(dir,'relationship-rings.css')});await page.addScriptTag({path:path.join(dir,'ring-art-live.js')});await page.addScriptTag({path:path.join(dir,'relationship-live.js')});
const open=async()=>{await page.evaluate(()=>ErisRelationship.open());await page.waitForSelector('.rel-home-ring');await page.locator('.rel-home-ring').click();await page.waitForSelector('.rel-ring-tabs button');await page.waitForFunction(()=>document.querySelector('.rel-ring-summary')?.textContent.includes('yüzük'))};
await open();assert.equal(await page.locator('.rel-jewel-card').count(),2);assert.equal(await page.getByRole('button',{name:'Takılı',exact:true}).isDisabled(),true);
for(const [width,height] of [[320,640],[390,844],[768,1024],[844,390]]){await page.setViewportSize({width,height});await page.getByRole('tab',{name:'Bakır',exact:true}).click();assert.equal(await page.locator('.rel-jewel-card').count(),20);assert.ok(await page.locator('.rel-ring-page .rel-body').evaluate(el=>el.scrollWidth<=el.clientWidth),'body overflow');assert.ok(await page.locator('.rel-ring-tabs button').evaluateAll(nodes=>nodes.every(n=>getComputedStyle(n).whiteSpace==='nowrap'&&n.scrollWidth<=n.clientWidth+1)),'tab text fits');assert.ok(await page.locator('.rel-jewel-card').evaluateAll(nodes=>nodes.every(n=>n.scrollWidth<=n.clientWidth+1)),'card fits')}
await page.setViewportSize({width:390,height:844});await page.locator('.rel-jewel-preview').first().click();await page.waitForFunction(()=>document.querySelector('.rel-jewel-large')?.naturalWidth===512);assert.equal(await page.evaluate(()=>requests.length),0,'preview is free');await page.screenshot({path:process.env.RING_PREVIEW_SCREENSHOT||'/tmp/ring-preview.png'});await page.locator('.rel-overlay').last().locator('.rel-close').click();await page.screenshot({path:process.env.RING_SCREENSHOT||'/tmp/ring-menu.png'});
await page.locator('.rel-jewel-card').nth(2).locator('.rel-jewel-action').click();await page.locator('.rel-overlay').last().getByRole('button',{name:'Satın al',exact:true}).evaluate(el=>{el.click();el.click()});await page.waitForFunction(()=>requests.length===1);assert.equal(await page.evaluate(()=>requests[0].url),'/relationship/ring');assert.equal(await page.evaluate(()=>requests[0].body.item),'copper-3');assert.ok(await page.evaluate(()=>requests[0].body.request_key));await page.waitForTimeout(150);
await open();await page.locator('.rel-jewel-card').nth(1).locator('.rel-jewel-action').click();await page.waitForTimeout(150);assert.deepEqual(await page.evaluate(()=>requests.at(-1)),{url:'/relationship/ring/equip',body:{ring:'silver-2'}});
await open();await page.getByRole('tab',{name:'Seviye',exact:true}).click();assert.equal(await page.locator('.rel-jewel-card').count(),1);await page.locator('.rel-jewel-preview').click();assert.match(await page.locator('.rel-jewel-large').getAttribute('src'),/modern\/rings\/level-1/);await page.locator('.rel-overlay').last().locator('.rel-close').click();await page.locator('.rel-ring-page .rel-close').click();
await page.evaluate(()=>{house.level=1;house.needs_first_copper=true;house.ring=null;house.owned_rings=[]});await open();assert.equal(await page.locator('.rel-ring-empty').count(),1);await page.getByRole('tab',{name:'Gümüş',exact:true}).click();assert.equal(await page.locator('.rel-jewel-action:disabled').count(),20);await page.getByRole('tab',{name:'Altın',exact:true}).click();assert.equal(await page.locator('.rel-jewel-action:disabled').count(),20);await page.getByRole('tab',{name:'Bakır',exact:true}).click();assert.equal(await page.locator('.rel-jewel-action:disabled').count(),0);await page.locator('.rel-jewel-action').first().click();await page.evaluate(()=>fail=true);const buy=page.locator('.rel-overlay').last().getByRole('button',{name:'Satın al',exact:true});await buy.click();await page.waitForFunction(()=>document.querySelector('.rel-overlay:last-child .rel-error')?.textContent.includes('Bakiye'));const requestKey=await page.evaluate(()=>requests.at(-1).body.request_key);await buy.click();await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>requests.at(-1).body.request_key),requestKey,'retry same transaction key');await page.locator('.rel-overlay').last().locator('.rel-close').click();await page.locator('.rel-ring-page .rel-close').click();await page.evaluate(()=>{fail=false;house.level=4;house.needs_first_copper=false;house.ring='gold-1';house.owned_rings=[{key:'gold-1',source:'purchased',asset:'./relationship-assets/gold-1.png'}];ErisRelationship.open()});
await page.waitForTimeout(100);await page.locator('.rel-house-menu-toggle').click();await page.getByRole('button',{name:'♥ Evlilik teklif et',exact:true}).click();await page.getByRole('button',{name:'Evlilik teklifiniz için yüzük seçiniz',exact:true}).click();await page.waitForSelector('.rel-ring-tabs button');assert.equal(await page.locator('.rel-ring-tabs button').count(),1);await page.locator('.rel-jewel-action').first().click();assert.match(await page.locator('[data-preview]').innerText(),/0/);await page.locator('.rel-overlay').last().locator('textarea').fill('Birlikte nice yıllara');await page.getByRole('button',{name:'Teklifi gönder',exact:true}).click();await page.getByRole('button',{name:'Satın al ve teklif et',exact:true}).click();await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>requests.at(-1).url),'/relationship/marriage');assert.equal(await page.evaluate(()=>requests.at(-1).body.ring),'gold-1');
await page.evaluate(()=>{const area=document.createElement('div');area.id='collection-fixture';area.innerHTML='<img src="./relationship-assets/gold-20.png"><img src="./relationship-assets/rewards/ring-2.png"><img src="./other-ring.png">';document.body.append(area)});await page.waitForFunction(()=>document.querySelector('#collection-fixture img')?.src.includes('modern/rings/gold-20'));assert.match(await page.locator('#collection-fixture img').nth(1).getAttribute('src'),/modern\/rings\/level-2/);assert.equal(await page.locator('#collection-fixture img').nth(2).getAttribute('src'),'./other-ring.png');
const checks=await page.evaluate(async()=>{const names=[...['copper','silver','gold'].flatMap(m=>Array.from({length:20},(_,i)=>m+'-'+(i+1))),'level-1','level-2'],out=[];for(const name of names){const im=new Image();im.src='/relationship-assets/modern/rings/'+name+'.png';await im.decode();const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d');ctx.drawImage(im,0,0);const a=ctx.getImageData(0,0,512,512).data;let edge=0,visible=0;for(let y=0;y<512;y++)for(let x=0;x<512;x++){const alpha=a[(y*512+x)*4+3];if(alpha)visible++;if((x<30||y<30||x>=482||y>=482)&&alpha)edge++}out.push({name,width:im.naturalWidth,edge,visible})}return out});assert.equal(checks.length,62);for(const item of checks){assert.equal(item.width,512);assert.equal(item.edge,0,item.name+' safe margins');assert.ok(item.visible>10000,item.name+' nonempty')}assert.deepEqual(errors,[]);console.log('PASS: 62 transparent ring assets; responsive tabs/cards; preview; buy/equip; repeat guard; retry key; gold/first-copper locks; marriage owned ring; collection art mapping.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
