const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/tmp/chromium-eris',args:['--no-sandbox']});try{const p=await browser.newPage();await p.route('https://eris.test/**',r=>r.fulfill({contentType:'text/html',body:`<html class="eris-adaptive" style="--app-top:0px;--eris-safe-top:0px;--eris-safe-left:0px;--eris-safe-right:0px;--eris-viewport-left:0px;--eris-usable-height:100dvh"><body><main class="app"><nav class="nav">Alt menü</nav></main><div id="erisRoomSurface" class="room-layout-v6 show" style="position:fixed;inset:0"><div class="eris-room-top" style="position:absolute;display:flex;width:100%"><div class="eris-room-emblem">⌂</div><div class="eris-room-title"><b>Sohbet</b><small>ID: 123</small></div><button id="erisRoomLevel">Seviye 8</button></div><div id="erisLiveSeats" class="eris-room-stage" style="position:absolute;left:0;right:0;display:grid"></div><div class="eris-room-chat" style="position:absolute;left:0;right:0"><div class="eris-room-activity">24 koltuk</div><div id="erisLiveChat">Mesajlar</div><div class="eris-room-compose"><input id="erisLiveInput"><button id="erisRoomEmojiButton">☺</button><button id="erisRoomMicInline">Mic</button><button id="erisRoomAudioOutput">Ses</button><button id="erisRoomGiftInline">Hediye</button><button id="erisLiveSend">Gönder</button></div></div></div></body></html>`}));await p.goto('https://eris.test');await p.evaluate(()=>{
 window.ErisCurrentRoomId='r';window.ErisCurrentUserId='z';window.__erisRoomPermissions={current_user_seat:null};window.__erisRoomSocket={readyState:1,send(){}};window.cfg={ice_servers:[{urls:'stun:test'}],seat_number:null};window.ErisPlatform={api:async()=>({...cfg})};window.pcs=[];window.RTCPeerConnection=class{constructor(){pcs.push(this);this.signalingState='stable'}close(){}setConfiguration(){}};
 Object.defineProperty(HTMLMediaElement.prototype,'srcObject',{configurable:true,get(){return this._media},set(v){this._media=v}});window.allowPlay=false;HTMLMediaElement.prototype.play=async function(){if(!allowPlay)throw new DOMException('Blocked','NotAllowedError')};HTMLMediaElement.prototype.pause=function(){};
 window.captureCount=0;window.stopped=0;Object.defineProperty(navigator,'mediaDevices',{value:{getUserMedia:()=>{captureCount++;return new Promise(resolve=>{window.captureResolve=()=>resolve({getTracks:()=>[{stop(){stopped++}}],getAudioTracks:()=>[]})})}}});
 for(let n=1;n<=24;n++){const b=document.createElement('button');b.className='eris-seat empty';b.innerHTML='<span class="seat-pod"><span class="seat-ava"></span></span>';document.querySelector('#erisLiveSeats').append(b)}
 });
 await p.addStyleTag({path:path.resolve(__dirname,'../frontend/device-layout.css')});await p.addStyleTag({path:path.resolve(__dirname,'../frontend/room-modern-audio.css')});await p.addScriptTag({path:path.resolve(__dirname,'../frontend/room-rtc-live.js')});await p.addScriptTag({path:path.resolve(__dirname,'../frontend/room-modern-audio.js')});
 await p.evaluate(()=>ErisRoomRTC.message({type:'rtc_ready',user_id:'z',peers:['a']}));assert.equal(await p.evaluate(()=>captureCount),0);
 await p.evaluate(()=>pcs[0].ontrack({track:{kind:'audio',addEventListener(){}},streams:[{getAudioTracks:()=>[]}]}));await p.waitForFunction(()=>ErisRoomRTC.state().blocked);assert.equal(await p.locator('#erisRoomAudioResume').isVisible(),true);
 await p.evaluate(async()=>{allowPlay=true;await ErisRoomRTC.toggleOutput()});await p.waitForFunction(()=>!ErisRoomRTC.state().blocked);assert.equal(await p.evaluate(()=>ErisRoomRTC.state().output),true);
 await p.evaluate(()=>{cfg.seat_number=1;__erisRoomPermissions.current_user_seat=1;ErisRoomRTC.syncSeatMicrophone()});await p.waitForFunction(()=>captureCount===1);await p.evaluate(()=>{cfg.seat_number=null;__erisRoomPermissions.current_user_seat=null;captureResolve()});await p.waitForFunction(()=>!ErisRoomRTC.state().pending);assert.equal(await p.evaluate(()=>stopped),1);assert.equal(await p.evaluate(()=>ErisRoomRTC.state().microphone),false);
 await p.evaluate(()=>{cfg.seat_number=2;__erisRoomPermissions.current_user_seat=2;ErisRoomRTC.syncSeatMicrophone()});await p.waitForFunction(()=>captureCount===2);await p.evaluate(()=>captureResolve());await p.waitForFunction(()=>ErisRoomRTC.state().microphone);await p.evaluate(()=>{cfg.seat_number=null;__erisRoomPermissions.current_user_seat=null;ErisRoomRTC.syncSeatMicrophone()});await p.waitForFunction(()=>!ErisRoomRTC.state().microphone);assert.equal(await p.evaluate(()=>stopped),2);
 for(const [width,height] of [[320,640],[390,844],[768,900],[844,390]]){await p.setViewportSize({width,height});await p.waitForTimeout(30);const result=await p.evaluate(()=>{const root=document.querySelector('#erisRoomSurface').getBoundingClientRect();const compose=document.querySelector('.eris-room-compose').getBoundingClientRect();return {overflow:document.documentElement.scrollWidth>innerWidth,inside:compose.left>=root.left&&compose.right<=root.right&&compose.bottom<=root.bottom,buttons:[...document.querySelectorAll('.eris-room-compose button')].every(b=>b.getBoundingClientRect().right<=root.right)}});assert.deepEqual(result,{overflow:false,inside:true,buttons:true});}
 assert.equal(await p.locator('.nav').isVisible(),false);await p.evaluate(()=>document.querySelector('#erisRoomSurface').style.display='none');await p.waitForFunction(()=>!document.body.classList.contains('eris-room-visible'));assert.equal(await p.locator('.nav').isVisible(),true);await p.evaluate(()=>ErisRoomRTC.leaveRoom());console.log('PASS: mobile composer, nav restore, automatic listener, blocked audio retry, seat-exit capture protection');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
