const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/tmp/chromium-eris',args:['--no-sandbox']});try{const p=await browser.newPage();await p.route('https://eris.test/**',r=>r.fulfill({contentType:'text/html',body:`<html><head><meta charset="UTF-8"><style>*{box-sizing:border-box}body{margin:0;font-family:system-ui;color:white}button{font:inherit;color:white}#erisRoomSurface{position:fixed;inset:0;z-index:900;overflow:hidden}.eris-room-top{position:absolute;display:flex}.eris-room-wall{background:linear-gradient(#213648,#121523)}.eris-room-chat{position:absolute}.eris-room-activity{padding:10px}.eris-seat{border-radius:50%;border:1px solid #aaa;background:#ffffff05}.seat-name{position:absolute;font-size:9px;top:100%;white-space:nowrap}.eris-room-title small{display:block}.nav{position:fixed;bottom:0}</style></head><body><main class="app"><div>Profil</div><nav class="nav">Çıkış yap</nav></main><div id="erisRoomSurface" class="show room-layout-v6 room-modern-audio room-menu-polished"><div class="eris-room-wall"></div><div class="eris-room-top"><button id="erisRoomMinimize">⌂</button><div class="eris-room-title"><b>Sohbet</b><small>ID:857530799581</small><button id="erisRoomFollow">＋ Odayı takip et</button></div><button id="erisRoomLevel"><b>Seviye 8</b><small>20 koltuk</small></button><button id="erisRoomMoreTop">•••</button><button id="erisRoomLeaveTop">↪</button></div><button id="erisRoomContributionButton" style="position:absolute">Oda katkısı</button><div class="eris-room-quick-actions"><button id="erisRoomGift">♢</button><button id="erisRoomMusic">♫</button><button id="erisRoomWallpaper">▣</button></div><div class="eris-room-stage" id="erisLiveSeats" data-seat-count="20"></div><div class="eris-room-chat"><div class="eris-room-activity">0 / 20 koltuk dolu · 1 kişi odada</div><div id="erisLiveChat">ErisChat: Odaya geldi</div><div class="eris-room-compose"><input id="erisLiveInput" placeholder="Odaya mesaj yaz…"><button id="erisRoomEmojiButton">☺</button><button id="erisRoomMicInline">🎙</button><button id="erisRoomAudioOutput">🔊</button><button id="erisRoomGiftInline">♢</button><button id="erisLiveSend">Gönder</button></div></div></div></body></html>`}));await p.goto('https://eris.test');await p.evaluate(()=>{window.ErisChatAndroid={};window.ErisCurrentRoomId='r';for(let n=0;n<20;n++){const seat=document.createElement('button');seat.className='eris-seat';seat.innerHTML='<b class="seat-name">Koltuk '+(n+1)+'</b>';document.querySelector('#erisLiveSeats').append(seat)}});
 const f=n=>path.resolve(__dirname,'../frontend/'+n);
 for(const n of ['room-layout-v6.css','device-layout.css','room-modern-audio.css','room-menu-polish.css','room-screen-fit.css'])await p.addStyleTag({path:f(n)});
 await p.addScriptTag({path:f('room-menu-polish.js')});await p.addScriptTag({path:f('device-layout.js')});await p.addScriptTag({path:f('room-screen-fit.js')});await p.waitForFunction(()=>document.body.classList.contains('eris-room-screen-active'));
 async function verify(width,height){await p.setViewportSize({width,height});await p.waitForTimeout(100);const result=await p.evaluate(()=>{const s=document.querySelector('#erisRoomSurface').getBoundingClientRect(),t=document.querySelector('.eris-room-title').getBoundingClientRect(),c=document.querySelector('.eris-room-compose').getBoundingClientRect(),buttons=[...document.querySelectorAll('.eris-room-top button,.eris-room-compose button')].filter(el=>getComputedStyle(el).display!=='none');return {room:s.top===0&&s.bottom===innerHeight&&s.width===innerWidth,title:t.top>=28&&t.bottom<=document.querySelector('.eris-room-top').getBoundingClientRect().bottom,compose:c.bottom<=s.bottom&&c.left>=s.left&&c.right<=s.right,buttons:buttons.every(el=>{const r=el.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight}),noOverlap:[...document.querySelectorAll('.eris-room-compose button')].every((el,i,all)=>all.slice(i+1).every(other=>{const a=el.getBoundingClientRect(),b=other.getBoundingClientRect();return a.right<=b.left||b.right<=a.left||a.bottom<=b.top||b.bottom<=a.top})),noProfile:getComputedStyle(document.querySelector('.app')).visibility==='hidden'}});assert.deepEqual(result,{room:true,title:true,compose:true,buttons:true,noOverlap:true,noProfile:true});}
 for(const [w,h] of [[320,640],[390,844],[768,1024],[844,390]])await verify(w,h);
 await p.setViewportSize({width:320,height:700});await p.locator('#erisLiveInput').focus();await verify(320,340);assert.equal(await p.evaluate(()=>ErisDeviceLayout.metrics().keyboard),true);
 await p.evaluate(()=>document.querySelector('#erisRoomSurface').style.setProperty('display','none','important'));await p.waitForFunction(()=>!document.body.classList.contains('eris-room-screen-active'));assert.equal(await p.locator('.app').isVisible(),true);
 await p.evaluate(()=>{document.querySelector('#erisRoomSurface').style.setProperty('display','block','important');document.querySelector('#erisLiveInput').blur()});await verify(390,844);
 await p.evaluate(()=>{for(let n=20;n<24;n++){const b=document.createElement('button');b.className='eris-seat';document.querySelector('#erisLiveSeats').append(b)}window.dispatchEvent(new Event('erischat:room-state-updated'))});await verify(390,844);assert.equal(await p.locator('#erisLiveSeats').evaluate(el=>el.scrollHeight<=el.clientHeight),true);if(process.env.ROOM_FIT_SCREENSHOT)await p.screenshot({path:process.env.ROOM_FIT_SCREENSHOT});console.log('PASS: complete viewport coverage, native status/header separation, follow button bounds, footer fit, 320/390/768 and landscape, keyboard resize and minimize restore');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
