const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/tmp/chromium-eris',args:['--no-sandbox']});try{const p=await b.newPage();await p.route('https://eris.test/**',r=>r.fulfill({body:'<html><head><style>*{box-sizing:border-box}body{margin:0;background:#090711;color:white}button{color:inherit}#erisRoomSurface{position:fixed;inset:0} .eris-room-top{display:flex;align-items:center}</style></head><body><div id="erisRoomSurface" class="show room-layout-v6 room-modern-audio"><div class="eris-room-wall"></div><div class="eris-room-top"><div class="eris-room-emblem">⌂</div><div class="eris-room-title"><b id="erisLiveTitle">Sohbet</b><small>ID:123</small></div></div><div class="eris-room-quick-actions"><button id="erisRoomGift">Hediye</button><button id="erisRoomMusic">Müzik</button><button id="erisRoomWallpaper">Duvar</button></div><div id="erisLiveSeats"></div><div class="eris-room-compose"><input id="erisLiveInput"><button id="erisLiveSend">Gönder</button></div></div></body></html>',contentType:'text/html'}));await p.goto('https://eris.test');await p.evaluate(()=>{
 window.calls=[];window.owner=true;window.ErisCurrentRoomId='r';window.ErisCurrentUserId='u';window.__erisRoomPermissions={is_owner:true};window.ErisRoom={get:async()=>({id:'r',public_id:'1234567890',name:'Sohbet',level:8,seat_count:24,is_owner:owner}),users:async()=>[]};window.ErisRoomRTC={toggle:()=>calls.push('mic'),toggleOutput:()=>calls.push('audio')};window.ErisPlatform={getMe:async()=>({lidya:10000}),api:async url=>url.includes('members')?[]:url.includes('leaderboard')?[]:url.includes('music')?[]:url.includes('wallpaper')?{items:[],prices:{1:1,7:5,30:18}}:{}};window.ErisRoomGift={catalog:async()=>[{name:'Test',gift_key:'Test',price:10,image_url:'https://eris.test/gift.png'}]};window.ErisLudo={open:()=>calls.push('ludo')};window.ErisUno={open:()=>calls.push('uno')};window.ErisOkey101={open:()=>calls.push('okey')};window.closeRealRoom=()=>calls.push('exit');window.toast=()=>{};
 });
 const f=name=>path.resolve(__dirname,'../frontend/'+name);
 for(const name of ['room-reference-ui.js','room-music-ui.js','room-wallpaper-live.js','room-gift-ui-live.js','room-modern-controls.js'])await p.addScriptTag({path:f(name)});
 await p.addStyleTag({path:f('room-modern-audio.css')});await p.addStyleTag({path:f('room-menu-polish.css')});await p.addScriptTag({path:f('room-menu-polish.js')});await p.evaluate(()=>window.dispatchEvent(new CustomEvent('erischat:room-opened',{detail:{room:{id:'r'}}})));
 await p.locator('#erisRoomMicInline .erm-icon').waitFor();await p.locator('#erisRoomMicInline').click();assert.deepEqual(await p.evaluate(()=>calls),['mic']);
 await p.evaluate(()=>{const mic=document.querySelector('#erisRoomMicInline');mic.textContent='🎙️';mic.setAttribute('aria-pressed','true')});await p.locator('#erisRoomMicInline .erm-icon').waitFor();
 await p.evaluate(()=>ErisRoomCenterMenu());await p.locator('[data-v5=theme] .erm-icon').waitFor();assert.equal(await p.locator('[data-v5] .erm-icon').count(),await p.locator('[data-v5]').count());await p.locator('[data-v5=uno]').click();assert.equal(await p.evaluate(()=>calls.at(-1)),'uno');
 for(const [width,height] of [[320,640],[390,844],[768,900],[844,390]]){await p.setViewportSize({width,height});await p.evaluate(()=>ErisRoomCenterMenu());const fit=await p.locator('.room-v5-dialog').evaluate(el=>{const r=el.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight&&el.scrollWidth<=el.clientWidth});assert.equal(fit,true);await p.locator('.room-center-close').click();}
 await p.evaluate(()=>{owner=false;__erisRoomPermissions={};return ErisRoomCenterMenu()});assert.equal(await p.locator('[data-v5=theme]').count(),0);assert.equal(await p.locator('[data-v5=settings]').count(),0);await p.locator('.room-center-close').click();
 await p.evaluate(()=>ErisChatMusic.open());await p.locator('#erisMusicPanel [data-close] .erm-icon').waitFor();await p.locator('#erisMusicPanel [data-close]').click();assert.equal(await p.locator('#erisMusicPanel').isVisible(),false);
 await p.evaluate(()=>openRoomGift('r'));await p.locator('.egp-select').waitFor();assert.equal(await p.locator('#erischatGiftPanel .egp-grid').evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length),3);await p.locator('.egp-select').click();assert.equal(await p.locator('.egp-send').count(),1);await p.locator('#erischatGiftPanel .egp-close').click();assert.equal(await p.locator('#erischatGiftPanel').isVisible(),false);
 await p.evaluate(()=>ErisChatRoomWallpaper.open('r',{}));await p.locator('#erisRoomWallpaperModal [data-close] .erm-icon').waitFor();assert.equal(await p.locator('#erisRoomWallpaperModal').evaluate(el=>Number(getComputedStyle(el).zIndex)),40070);await p.locator('#erisRoomWallpaperModal [data-close]').click();assert.equal(await p.locator('#erisRoomWallpaperModal').count(),0);
 await p.locator('#erisRoomContributionButton').click();await p.locator('#erisRoomContribution .rc-close .erm-icon').waitFor();assert.equal(await p.locator('#erisRoomContribution').isVisible(),true);await p.locator('#erisRoomContribution .rc-close').click();assert.equal(await p.locator('#erisRoomContribution').isVisible(),false);
 await p.setViewportSize({width:390,height:844});await p.evaluate(()=>{owner=true;return ErisRoomCenterMenu()});await p.locator('[data-v5=theme] .erm-icon').waitFor();if(process.env.ROOM_MENU_SCREENSHOT)await p.screenshot({path:process.env.ROOM_MENU_SCREENSHOT});
 console.log('PASS: real room center owner/visitor menus, preserved game/mic handlers, late RTC icon updates, music close, 3-column gift selection, mobile/landscape menu bounds');
 }finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
