plugins {
    id 'com.android.application'
}

android {
    namespace 'com.erischat.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.erischat.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    signingConfigs {
        erischat {
            storeFile file("../erischat-release.jks")
            storePassword System.getenv("ERISCHAT_KEYSTORE_PASSWORD")
            keyAlias "erischat"
            keyPassword System.getenv("ERISCHAT_KEY_PASSWORD")
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.erischat
        }
        release {
            signingConfig signingConfigs.erischat
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "androidx.credentials:credentials:1.7.0-alpha03"
    implementation "androidx.credentials:credentials-play-services-auth:1.7.0-alpha03"
    implementation "com.google.android.libraries.identity.googleid:googleid:1.1.1"
}
